### ISSUE TITLE
Weylus not working on old tablets.

### ISSUE THREAD

**Issue by r11b22** [H-M-H/Weylus#100]
I have been trying to use a left over tablet from Samsung as a drawing tablet I tried to use weylus for this but it doesn't give me any display outputs. I tested it on my phone and it does work there. I also read something about it not working on older ios versions. Could this be the same problem?

android version: 4.1.2

devices: Samsung galaxy note 10.1, windows.

browsers tested: chrome, default internet app.

**Comment by r11b22** [comment]
I fixed the issue by using another browser.

**Comment by H-M-H** [comment]
Yes, this is very likely the problem. Weylus requires some modernish browser APIs to work. You could try getting LineageOS working, there is an unofficial build available here: https://forum.xda-developers.com/t/lineageos-18-1-android-11-for-gt-n8000-gt-n8005-gt-n8010-gt-n8013-gt-n8020-alpha.4206063/
As this is based on Android 11 I'd expect Weylus to work with it, that is, if said build is stable enough. But as you describe the tablet as left over, I guess you can afford some experiments.
