### ISSUE TITLE
[Feature request] Fullscreen button

### ISSUE THREAD

**Issue by ar-nelson** [H-M-H/Weylus#101]
Weylus is a great project, but I'm having some trouble with it on my Galaxy Note 8.

I have to use it in Firefox, because the video flickers constantly in Chrome. Normally that would be fine, because Firefox is my default mobile browser anyway... but mobile Firefox doesn't support hiding the toolbar for web app links, so the toolbar is always visible at the top of the screen.

Would it be possible to add a Fullscreen button to the Weylus sidebar menu, that just makes the page fullscreen using the browser's fullscreen API?

**Comment by H-M-H** [comment]
> the video flickers constantly in Chrome

I assume you have tried changing the frame interval as well as the resolution to get rid of the flickering and it didn't work? Perhaps this is worth filing a bug report for chrome.

> add a Fullscreen button

Making the video/drawing area fullscreen is pretty easy, but the last time I tried to implement it, it didn't work well with capturing input events. I guess I will give it another look.

If you do not want to wait for me, feel free to do some experiments yourself and modify the web page served by Weylus.

```console
$ weylus --help
weylus 0.11.2

USAGE:
    weylus [FLAGS] [OPTIONS]

FLAGS:
...
        --print-access-html    Print access.html served by Weylus.
        --print-index-html     Print template of index.html served by Weylus.
        --print-lib-js         Print lib.js served by Weylus.
        --print-style-css      Print style.css served by Weylus.
...

OPTIONS:
...
        --custom-access-html <custom-access-html>    Use custom access.html to be served by Weylus.
        --custom-index-html <custom-index-html>      Use custom template of index.html to be served by Weylus.
        --custom-lib-js <custom-lib-js>              Use custom lib.js to be served by Weylus.
        --custom-style-css <custom-style-css>        Use custom style.css to be served by Weylus.
...
```

**Comment by H-M-H** [comment]
Implemented for non iOS/IPadOS devices, feel free to try the latest build: https://github.com/H-M-H/Weylus/actions/runs/1086844219#artifacts

**Comment by gzqx** [comment]
It seems that on IOS/iPadOS browsers, the only possible way to get full-screen is to scroll down. Is it possible to get full-screen by simulating this behavior or add some blank space for scrolling down?

**Comment by H-M-H** [comment]
The only reliable way I know to get fullscreen working on iOS/iPadOS is to bookmark Weylus to your home screen.

**Comment by gzqx** [comment]
Oh this works, thanks!

**Comment by amitnovick** [comment]
> The only reliable way I know to get fullscreen working on iOS/iPadOS is to bookmark Weylus to your home screen.

Thanks for the suggestion!

from what I tried, this feature isn't available in every browser in iOS/iPadOS (I tried Brave)

Works on Safari for me
