### ISSUE TITLE
Feature request : start weylus hidden

### ISSUE THREAD

**Issue by mfauvain** [H-M-H/Weylus#103]
Hi, very nice tool thx. can you add a cli param --hidden to start weylus hidden pls?

**Comment by mfauvain** [comment]
Thx! Don't know how to get the build from your page though...

**Comment by H-M-H** [comment]
Just scroll down to artifacts, you will find download links there.

**Comment by mfauvain** [comment]
Ah, indeed..
just ran it, but `--hidden` argument is not accepted :
`error: Found argument '--hidden' which wasn't expected, or isn't valid in this context`
and it is not mentioned in the `--help`

**Comment by mfauvain** [comment]
works perfect. thx.
