### ISSUE TITLE
Disable Screen

### ISSUE THREAD

**Issue by CodingLappen** [H-M-H/Weylus#106]
Hello, 
I would like to disable the video on tablet, it's distracting, because I'd rather  look at my monitor while using it because of the high latency.

**Comment by parkerlreed** [comment]
Just use the "Enable video" checkbox...

**Comment by CodingLappen** [comment]
> 
> 
> Just use the "Enable video" checkbox...

There is no Enable video checkbox...

**Comment by H-M-H** [comment]
There is in the menu that opens in the browser once the page has been loaded.
