### ISSUE TITLE
Weylus does not work if I use it in a second external monitor

### ISSUE THREAD

**Issue by All3xJ** [H-M-H/Weylus#108]
Video of the bug: https://streamable.com/9pkj5i
Distro: ArchLinux
DE: GNOME Wayland
weylus 0.11.2

**Comment by H-M-H** [comment]
This is a known problem on Wayland, Weylus works fine on X11. Sadly Wayland made some design decisions that make it impossible to get the position of a window or screen within the whole desktop via the Wayland protocol, which is needed for proper input mapping. Actually Wayland does not even support recording the screen and every compositor is on its own. There is, however, a de-facto standard for screen recording developed by flatpak: https://github.com/flatpak/xdg-desktop-portal. Unfortunately also without a way to determine window/monitor positions. I have filed some issues there but so far it does not seem there is any interest to change things. I am closing this in favor of #3, have a look for more details.
