### ISSUE TITLE
Stupid question but how do I draw

### ISSUE THREAD

**Issue by Stinky188** [H-M-H/Weylus#109]
I am using this on a Samsung tablet on Firefox and it detects me moving my finger on the screen fine but I can't "click" to start drawing.
Is there an option I need to toggle?

**Comment by H-M-H** [comment]
Which program do you use for drawing, you may need to configure how input is handled? Something else that may be a problem is if your tablet doesn't detect pressure and sets it to 0. In that case setting a minimum pressure in the browser menu might help.

**Comment by H-M-H** [comment]
Please comment if you still have troubles.
