### ISSUE TITLE
Error installing Weylus_0.7.0_amd64.deb on Debian stable

### ISSUE THREAD

**Issue by Mestelan** [H-M-H/Weylus#11]
Hello,

The .deb fails to install on Debian stable. Is it maybe intended for Ubuntu, or Debian testing/unstable?

`sudo apt install ./Weylus_0.7.0_amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'weylus' instead of './Weylus_0.7.0_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 weylus : Depends: libgcc1 (>= 1:8.4.0) but 1:8.3.0-6 is to be installed
          Depends: libstdc++6 (>= 8.4.0) but 8.3.0-6 is to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by H-M-H** [comment]
> Is it maybe intended for Ubuntu

Right now yes, but I will try to build it on Debian stable.

**Comment by H-M-H** [comment]
Can you try if [Linux-deb.zip](https://github.com/H-M-H/Weylus/files/4773281/Linux-deb.zip) works?

**Comment by Mestelan** [comment]
Thank you. This .deb installs all right.

However, I get an error when running the program (and by the way, I get this same error when running the [linux binary](https://github.com/H-M-H/Weylus/releases/download/v0.7.0/linux.zip), or a binary built from the Docker container):

```
weylus                    
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CError: code: 1 message: Cannot get client list properties. _NET_CLIENT_LIST: Invalid type of _NET_CLIENT_LIST property. or _WIN_CLIENT_LIST: Invalid type of _WIN_CLIENT_LIST property.', src/gui.rs:229:39
stack backtrace:
   0:     0x562afb3e9595 - <unknown>
   1:     0x562afb3246ac - <unknown>
   2:     0x562afb3e8b54 - <unknown>
   3:     0x562afb3e83a5 - <unknown>
   4:     0x562afb3e7941 - <unknown>
   5:     0x562afb3e74d8 - <unknown>
   6:     0x562afb322950 - <unknown>
   7:     0x562afb325772 - <unknown>
   8:     0x562afb47602a - <unknown>
   9:     0x562afc1297c3 - <unknown>
  10:     0x562afc105768 - <unknown>
  11:     0x562afb46a3c4 - <unknown>
  12:     0x562afb3196bb - <unknown>
  13:     0x562afb3f3403 - <unknown>
  14:     0x562afb319d8f - <unknown>
  15:     0x7f26f0e1a09b - __libc_start_main
  16:     0x562afb302b9a - <unknown>
  17:                0x0 - <unknown>
```

**Comment by H-M-H** [comment]
It seems your window manager does not support [Extended Window Manager Hints](https://specifications.freedesktop.org/wm-spec/latest/) which are required to get a list of windows to capture. Which desktop environment do you use? You can also try the latest master now, I just pushed some changes to avoid crashing if querying the list fails.

**Comment by Mestelan** [comment]
Thank you; with this new build, the app launches all right. 

I am on XMonad, where I had not explicitly activated [EWMH support](https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/src/XMonad.Hooks.EwmhDesktops.html). After doing so, I can indeed control the mouse from the phone.

Thanks for clarifying, and for the fix. I think we can close this issue.
