### ISSUE TITLE
Lagging on HiDPI screen

### ISSUE THREAD

**Issue by denis-khizhniak** [H-M-H/Weylus#110]
I have  huge lagging while using the application on HiDPI screen of my laptop until I set the resolution to something like 1920x1080. Is there a way to optimize the execution on high resolutions?

I tried several options in the settings including VAAPI, NVENC and limiting maximum resolution on the device (tried iPad and mobile phone), none of them gave any visible improvements.

My configuration:
GPU:  GeForce RTX 2080 SUPER Mobile / Max-Q
OS: Fedora (I've modified a bit Dockerfile to build rpm package for my distribution - cargo install cargo-rpm, cargo rpm build
Tested devices: iPad Air 2020, Huawei P30 Pro

**Comment by H-M-H** [comment]
A few things to watch out for / to try:
- If using VAAPI or NVENC make sure Weylus does not fallback to software encoding. You can verify that by looking at the log: Something like this `INFO weylus::log: Video: 1920x1080@libx264 pix_fmt: yuv420p` means Weylus is doing software encoding, `INFO Video: 1920x1080@h264_nvenc pix_fmt: bgr0` means NVENC is actually used.
- Run Weylus (latest master) with `WEYLUS_LOG_LEVEL=TRACE weylus` and check if the test sources you can select in the capture selector are also slow. For 4K without downscaling using NVENC I still get about 20 fps on my XPS 15.
- Make sure the frame rate is not too high, paradoxically some browsers do not handle frame rates > 60 smoothly.
- If you are running Wayland (I think fedora has that as default?), you might want to check if the lagging persists using X11.

But I have to admit that limiting the maximum resolution does not help is rather strange, I'd expect that to help at least a little.

**Comment by denis-khizhniak** [comment]
Thank you @H-M-H,

I will look today for the logs and check the rest points you've mentioned.
I'll update on the results.

**Comment by denis-khizhniak** [comment]
Well, I have some results but cannot say that they are really helpful.

Most of the time I get FPS somewhere in between 25 and 30, but sometime it can get up to 56 and yet drop till 3.
Immediately after the connection of the device I get the following 2 error lines:
```
XRequest.130: BadAccess (attempt to access private resource denied) 0x264
XRequest.130: BadShmSeg (invalid shared segment parameter) 0x2c00001
```
 I looked for the definition of the software/hardware rendering and I found this when I enabled VAAPI:
```
Output #0, mp4, to '(null)':
  Stream #0:0: Video: h264 (High), vaapi_vld, 3840x2160, q=2-31
INFO weylus::log: Video: 3840x2160@h264_vaapi pix_fmt: bgr0
```
I assume it is working as expected.

But looks like NVENC is not working for me (because of CUDA?)
```
[h264_nvenc @ 0x7f81f4001cc0] dl_fn->cuda_dl->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
DEBUG weylus::log: Could not open codec: Unknown error occurred!
[libx264 @ 0x7f81f404cb40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
...
[libx264 @ 0x7f81f4057480] 264 - core 163 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=15 lookahead_threads=15 sliced_threads=1 slices=15 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=12 keyint_min=1 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to '(null)':
  Stream #0:0: Video: h264, yuv420p, 1722x968, q=2-31
INFO weylus::log: Video: 1722x968@libx264 pix_fmt: yuv420p
```

I forgot to mention that I even tried with a disabled Video but lagging persisted. Basically it looks like it's loosing connection for 1-2 seconds and then you can smoothly draw for the same 1-2 seconds and then again drop of the connection for a while and so on. 

The other important note is that I'm using X11 not Wayland.

Would appreciate further guidance in resolving the issue.

**Comment by H-M-H** [comment]
> I forgot to mention that I even tried with a disabled Video but lagging persisted.

So this is most likely actually unrelated to video encoding! But something which is confusing me is that the lagging goes away if you reduce the resolution, despite not streaming video?! Also, if you are running latest master, try if the energy saving option does anything for you.

> Basically it looks like it's loosing connection for 1-2 seconds and then you can smoothly draw for the same 1-2 seconds and then again drop of the connection for a while and so on.

That does sound like a network problem. To check if it's a network problem you could try connecting to Weylus on the machine you are running it on and compare that to the "lagginess" you get connecting with a tablet.  If it is not a network problem it may be the input queue getting congested, in which case you could verify this by checking the "lagginess" with and without drawing something.

**Comment by denis-khizhniak** [comment]
Unfortunately, power saving options did nothing for me. My normal mode is "Balanced" and I tried with Performance and Power Saver for complete picture. No luck here.
![image](https://user-images.githubusercontent.com/4676695/132858592-b03af7c2-0320-44b1-b57f-9fdbed5c0fcf.png)

> That does sound like a network problem. To check if it's a network problem you could try connecting to Weylus on the machine you are running it on and compare that to the "lagginess" you get connecting with a tablet. If it is not a network problem it may be the input queue getting congested, in which case you could verify this by checking the "lagginess" with and without drawing something.
With that I cannot do much because when I select Xournal or anything else as a Capture then as soon as my pointer gets in the wokring area of the tab the active window switches to "captured" application. Though I can hover the mouse with selected Weylus connected tab over the top bar of the browser and I've noticed that the movement of the cursor is choppy. But it's different from the experience with drawing - apart from periodically stopping like it's always choppy.  

Don't know is this information helpful for further investigation. Maybe the process of mapping the input data from one resolution to a higher HiDPi resolution is slow.
Is there anything yet to try?

**Comment by H-M-H** [comment]
I was a busy with other things the last days, so I am only now coming back to this.
> power saving options did nothing for me. My normal mode is "Balanced" and I tried with Performance and Power Saver for complete picture

What I meant is the checkbox in the browser interface of the latest master, it disables webGL rendering of the stuff you are drawing, which can lag on some devices.
Something else you seem to not have checked yet is whether the video test source (see https://github.com/H-M-H/Weylus/issues/110#issuecomment-915996799) is also laggy.

To completely bypass any input processing you can try this:
https://github.com/H-M-H/Weylus/issues/87#issuecomment-850481361

I'd like to isolate the cause of the lagging like this but as of now it is very unclear to me where this is coming from.

**Comment by denis-khizhniak** [comment]
Hi @H-M-H , I think we can close this issue for now. 
Previously I checked [#110 (comment)](https://github.com/H-M-H/Weylus/issues/110#issuecomment-915996799) and there was no fallback to software encoding.
I didn't try https://github.com/H-M-H/Weylus/issues/87#issuecomment-850481361 however the issue seemed like fixed after I've added the service ***mdns*** which is udp port 5353 in the firewall for current network zone. I'm not sure though is this service resolved the issue with Weylus or there was some system update which helped.
