### ISSUE TITLE
Weylus registering new input system for each connection 

### ISSUE THREAD

**Issue by matthiasneuner** [H-M-H/Weylus#112]
Hi, it seems that Weylus registers a new input device for each ingoing connection, which leads to a situation where e.g., Xournal++ looks like this:
![image](https://user-images.githubusercontent.com/16517038/133879702-a3928ef2-53ee-469c-b7b7-3427c1a5b91d.png)

Is there any way to avoid this?

**Comment by H-M-H** [comment]
Currently there is no way to avoid this. But I have to admit that I am not really happy with this myself. The reason it is here is to distinguish multiple connected devices, but I guess as this is a pretty rare use case I might remove this behavior.

Ideally each browser would generate a unique identifier to be used as device suffix. But as this is nothing else than browser fingerprinting it probably won't work in a way I'd like.

If you can build Weylus yourself, this is the code responsible for naming the input devices:
https://github.com/H-M-H/Weylus/blob/a89b7f481b82e96b1ae3e1586e683e22f7fefffa/src/input/uinput_device.rs#L54-L78

**Comment by matthiasneuner** [comment]
Alright, I understand.
Is there a clean way to delete all devices?

**Comment by H-M-H** [comment]
You can just delete the entries from `.xournalpp/settings.xml`, it's not exactly what I'd call a clean solution though.

**Comment by H-M-H** [comment]
Alright I have changed things a little and by default suffixes are gone now, optionally a device name can be set to distinguish devices, you can try the latest master which includes these changes here: https://github.com/H-M-H/Weylus/actions/runs/1265786002#artifacts

**Comment by H-M-H** [comment]
This has been released, closing.
