### ISSUE TITLE
Intel UHD620 requires manually setting WEYLUS_VAAPI_DEVICE=/dev/dri/renderD129

### ISSUE THREAD

**Issue by matthiasneuner** [H-M-H/Weylus#113]
In order to leverage VAAPI on my Matebook X Pro with Intel UHD 620, I need to manually set WEYLUS_VAAPI_DEVICE=/dev/dri/renderD129 .
Not a big deal, but I want to leave this here for others which may want to use VAAPI.

**Comment by H-M-H** [comment]
Thanks for figuring this out, I guess I might add a small note to the readme!

**Comment by H-M-H** [comment]
I added setting `WEYLUS_VAAPI_DEVICE=/dev/dri/renderD129` as a hint in case VAAPI doesn't work to the Readme.
