### ISSUE TITLE
Cannot draw correctly

### ISSUE THREAD

**Issue by Mandofskii** [H-M-H/Weylus#116]
Hi,
Working on windows 7, I can draw on Paint, but sadly, on PowerPoint and Pdf annotator, it draws only a point at the location I started to touch the tablet with the stylus.

**Comment by H-M-H** [comment]
Thanks for the report, others have mentioned this problem too. Unfortunately for everyone on Windows: I personally do not use Windows and thus don't really need Weylus to work on Windows at all or even well. Additionally I also can't do proper testing like this and generally working for Windows specific things is a pain for me. That's also why I probably won't fix this.

But that doesn't mean I don't want this to be fixed. See #17 for technical details on how things ideally should be.
