### ISSUE TITLE
Framerate

### ISSUE THREAD

**Issue by YukKevChuHau** [H-M-H/Weylus#117]
Hello,

What's the best way to increase framerate? The client browser shows maximum 29fps. But, I have the 2nd display using a dummy mDP plug set to 59.97/60hz. Weylus also has VAAPI enabled. These are my system specs:

![image](https://user-images.githubusercontent.com/92200990/137575875-af37b1a2-7dba-4aa1-936c-12e0922ced23.png)

![image](https://user-images.githubusercontent.com/92200990/137575950-490e8b64-dded-4a74-838a-033dfba85606.png)

**Comment by H-M-H** [comment]
By default Weylus limits the framerate to about 30fps, to increase your framerate lower the `Min Frame Interval` in the browser settings. But keep in mind that this will only reduce throttling and you may not be able to achieve 60fps if your hardware can't keep up with encoding the video stream.

**Comment by H-M-H** [comment]
> Also, how does the Lower latency (possibly choppy) checkbox affect performance?

During playback in the browser Weylus tries to seek to the end of the video to minimize latency; browsers report a [`readyState`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/readyState) that indicates how much of the video stream is buffered. If said checkbox is checked Weylus tries seeking on a lower `readyState` `HAVE_FUTURE_DATA` which some browsers, notably firefox, don't really like and in my experiments I got choppy playback. If the checkbox is unchecked Weylus only seeks to the end of the video if the `readyState` is `HAVE_ENOUGH_DATA`, which results in higher latency but smooth playback.
