### ISSUE TITLE
When connecting to server: XShmExtension does not support shared memory pixmaps

### ISSUE THREAD

**Issue by TheTimeWalker** [H-M-H/Weylus#12]
After upgrading to v0.7.0, Weylus does not work anymore and won't start any video stream. Trying to connect with the server, the logs give:

```ERROR weylus::websocket: Failed to create stream handler: CError: code: 1 message: This version of XShmExtension does not support shared memory pixmaps!```

v0.6.2 works fine so there was a change between these versions that broke it.

System: Manjaro Linux
GPU: Nvidia GTX 1070

**Comment by H-M-H** [comment]
Thanks for the report! This should be fixed with [v0.7.1](https://github.com/H-M-H/Weylus/releases/tag/v0.7.1).

**Comment by TheTimeWalker** [comment]
Can confirm that this is fixed in v0.7.1. Thanks for the quick fix!
