### ISSUE TITLE
Crashing when Device Connects

### ISSUE THREAD

**Issue by NewoIsTaken** [H-M-H/Weylus#121]
I have Weylus v0.11.3 installed via `weylus-bin` from the AUR. Whenever I press "Login," Weylus prints out [this](https://pastebin.com/WaLRUx2m) error.

Please let me know if there's anything else I need to provide.

**Comment by H-M-H** [comment]
Thanks for the report, I am looking into it. Also note that pastebin currently says: `Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it.`.

**Comment by H-M-H** [comment]
Alright, please try v0.11.4.

**Comment by NewoIsTaken** [comment]
> Thanks for the report, I am looking into it. Also note that pastebin currently says: `Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it.`.

Oops. I have updated the permissions for it. I will check the new version in a bit.

**Comment by NewoIsTaken** [comment]
v0.11.4 works!
