### ISSUE TITLE
Crashes when trying to use VAAPI acceleration

### ISSUE THREAD

**Issue by 500cc** [H-M-H/Weylus#123]
Version: 0.11.4
OS: Arch Linux

When I exec `weylus --no-gui --try-vaapi` , it crashes right after I try to connect my tablet. It runs perfectly with `weylus --no-gui`.

Here is the log (I got this by running `WEYLUS_LOG_LEVEL=TRACE weylus --no-gui --try-vaapi`).
https://pastebin.com/aFLB4gpV

**Comment by H-M-H** [comment]
Thanks for the report!

This is probably related to #62, some AMD drivers report support for pixel formats that they do not actually support. Please check if the build here: https://github.com/H-M-H/Weylus/actions/runs/1411810508#artifacts already fixes things.

**Comment by 500cc** [comment]
That build worked fine. Thanks a lot for your help!

**Comment by H-M-H** [comment]
Excellent!
