### ISSUE TITLE
Buildung on Raspberry pi OS 32 bit stops at fltk "expected `u64`, found `u32`"

### ISSUE THREAD

**Issue by saturn-hh** [H-M-H/Weylus#129]
First of all: Thank you for this great software and the work you invested.

I try to get it working on Raspberry pi os but I had no luck on the 32 bit version. On the 64 bit version weylus is working but the os is still in beta and I have problems using it with different screens.

So I kindly want to ask if it is possible to release a version for 32 bit. 

If I try to build weylus with

cargo build --release --features ffmpeg-system

The process stops at 

```
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1285ae84e5963aae/fltk-1.2.19/src/window.rs:406:56
    |
406 |                 XMapWindow(crate::app::display() as _, self.raw_handle());
    |                                                        ^^^^^^^^^^^^^^^^^
    |                                                        |
    |                                                        expected `u64`, found `u32`
    |                                                        help: you can convert an `u32` to `u64`: `self.raw_handle().into()`

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1285ae84e5963aae/fltk-1.2.19/src/window.rs:435:58
    |
435 |                 XUnmapWindow(crate::app::display() as _, self.raw_handle());
    |                                                          ^^^^^^^^^^^^^^^^^
    |                                                          |
    |                                                          expected `u64`, found `u32`
    |                                                          help: you can convert an `u32` to `u64`: `self.raw_handle().into()`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `fltk`.
```
Thank you in advance.

Regards

Alexander

**Comment by H-M-H** [comment]
This is a problem with the gui library [fltk](https://github.com/fltk-rs/fltk-rs) Weylus uses. Please open an issue there. If you need a solution quickly: Weylus supports running without a gui, so you could remove all gui related code:
https://github.com/H-M-H/Weylus/blob/e23d3b9133abbe7e43e27b15aecfa436158b8033/Cargo.toml#L23
https://github.com/H-M-H/Weylus/blob/e23d3b9133abbe7e43e27b15aecfa436158b8033/src/main.rs#L18
https://github.com/H-M-H/Weylus/blob/e23d3b9133abbe7e43e27b15aecfa436158b8033/src/main.rs#L71

**Comment by MoAlyousef** [comment]
Hello

This should be fixed in fltk 1.2.20

**Comment by H-M-H** [comment]
@MoAlyousef: Awesome, thank you very much! How did you even find this issue? To be honest I am amazed at the level of support you provide for your library!

@saturn-hh try building with the latest version of Weylus/fltk, lets hope this is everything required to get a working 32bit build.

**Comment by MoAlyousef** [comment]
Thank you!
It was actually a coincidence. I regularly search for recently updated issues related to fltk on github, focusing on vcpkg (where I contribute to the portfile) and fltk repos. It's easier than just watching the repos since I won't get bombarded with notifications.

**Comment by saturn-hh** [comment]
It's working!
I'm not familiar with compiling rust source code, so I started downloading libraries in the raspberry pi os. But the solution is much simpler. I updatet the git code with git pull and voila: Code is compiling and running!

Thank you again for the quick response and solution of my issue.
