### ISSUE TITLE
Cannot capture window contents if window not fully on screen

### ISSUE THREAD

**Issue by rschroll** [H-M-H/Weylus#13]
If Weylus is attempting to capture a single window, and that window is not fully on screen, it fails to capture any window contents.  The video output will freeze, or be completely black if just starting up, and the message
```
XRequest.130: BadMatch (invalid parameter attributes) 0x4a0000a
```
will be printed out repeatedly (I'm guessing once per frame).  When the window is moved back on screen, the video picks up correctly.  Input continues to work correctly, although the cursor is restricted to stay on the screen.

Admittedly, I don't know what the right behavior is here.  I don't know if the offscreen portion of the window is actually rendered, so there may be no data to capture.  I'd be fine with a message informing me that it can't work until the window is fully on screen.  But if you don't notice that a window is hanging a few pixels over the edge, it can be confusing to figure out why nothing's working.

This is seen on Ubuntu 20.04 with the Gnome DE running on X.

Please let me know if there's additional troubleshooting I can do.

**Comment by H-M-H** [comment]
Thanks for the report! The situation can indeed be improved. I just implemented capturing windows off screen using Xcomposite if available. The only problem left is that drop down menus are not visible if the window is not completely inside the screen area, but I think it is impossible to fix this too. 

Additionally I improved the error messages if capturing fails.

**Comment by rschroll** [comment]
I've built master and confirmed that it solves the problem.  Do you want me to close the issue, or do you prefer to leave it open until it's fixed in a release?

**Comment by H-M-H** [comment]
Thanks for the confirmation!
