### ISSUE TITLE
wont work or capture

### ISSUE THREAD

**Issue by howell66** [H-M-H/Weylus#130]
hi im on linux and im using a samsung glaxy to draw on but it wont work 
on anything like captureing the screen or the touch pad either 
and the options wont show up

**Comment by H-M-H** [comment]
Have you made sure your firewall is not interfering? If this is not it, please include the output of `WEYLUS_LOG_LEVEL="DEBUG" weylus`.

**Comment by howell66** [comment]
no i havent and im not sure how to check that

**Comment by H-M-H** [comment]
That depends on your system, `ufw` is a popular firewall (-frontend), check the [Readme](https://github.com/H-M-H/Weylus#running) on how to whitelist the ports Weylus needs.

**Comment by howell66** [comment]
oh it worked!!! thank you! :D

**Comment by H-M-H** [comment]
Alright, next time have a closer look at the Readme before opening an issue then :)
