### ISSUE TITLE
Failing to compile with wsl

### ISSUE THREAD

**Issue by Schischu** [H-M-H/Weylus#131]
Hi I am failing to compile the current master with wsl

Install WSL for Ubuntu
Follow https://ubuntu.com/wsl

Install Rust for WSL
See: https://www.rust-lang.org/tools/install
WSL:
```curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh```

Install dependencies
`sudo apt-get install gcc pkgconf`

`sudo apt-get install -y libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev \
libxfixes-dev libxtst-dev libxrandr-dev libxcomposite-dev libxi-dev libxv-dev autoconf libtool-bin \
nvidia-cuda-dev pkg-config libdrm-dev libpango1.0-dev libgstreamer1.0-dev \
libgstreamer-plugins-base1.0-dev libdbus-1-dev libx264-dev`

Patch build.rs to not build tsc as described here
```https://github.com/H-M-H/Weylus/issues/17#issuecomment-978003096```

Copy deps for ffmesg as described here
```https://github.com/H-M-H/Weylus/issues/17#issuecomment-978003096```

Replace lib.rs as described here
```https://github.com/H-M-H/Weylus/issues/17#issuecomment-978003096```
www/static/lib.js -> www/static/lib.js 

EDIT: Fix indexmap on WSL
`export CARGO_FEATURE_STD=1`

Run 
```cargo build```

Fails at h2, indexmap
```ubuntu@DESKTOP-TA3P90N:/mnt/c/Users/matth/Documents/Development/Weylus$ cargo clean
ubuntu@DESKTOP-TA3P90N:/mnt/c/Users/matth/Documents/Development/Weylus$ cargo build
   Compiling proc-macro2 v1.0.33
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.82
   Compiling libc v0.2.109
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.131
   Compiling serde v1.0.131
   Compiling autocfg v1.0.1
   Compiling pkg-config v0.3.23
   Compiling unicode-segmentation v1.8.0
   Compiling strum v0.18.0
   Compiling version-compare v0.0.10
   Compiling log v0.4.14
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.3.2
   Compiling byteorder v1.4.3
   Compiling futures-core v0.3.18
   Compiling memchr v2.4.1
   Compiling version_check v0.9.3
   Compiling slab v0.4.5
   Compiling autocfg v0.1.7
   Compiling pin-project-lite v0.2.7
   Compiling futures-task v0.3.18
   Compiling rand_core v0.4.2
   Compiling either v1.6.1
   Compiling adler32 v1.2.0
   Compiling rustc-serialize v0.3.24
   Compiling futures-util v0.3.18
   Compiling crossbeam-utils v0.8.5
   Compiling unicode-xid v0.0.3
   Compiling pin-utils v0.1.0
   Compiling term v0.4.6
   Compiling futures-channel v0.3.18
   Compiling proc-macro2 v0.4.30
   Compiling anyhow v1.0.51
   Compiling bitflags v0.5.0
   Compiling crossbeam-epoch v0.9.5
   Compiling typenum v1.14.0
   Compiling tinyvec_macros v0.1.0
   Compiling crc32fast v1.3.0
   Compiling unicode-xid v0.1.0
   Compiling regex-syntax v0.6.25
   Compiling matches v0.1.9
   Compiling itoa v0.4.8
   Compiling rayon-core v1.9.1
   Compiling scopeguard v1.1.0
   Compiling cc v1.0.72
   Compiling once_cell v1.8.0
   Compiling getrandom v0.1.16
   Compiling unicode-bidi v0.3.7
   Compiling cfg-if v0.1.10
   Compiling syn v0.15.44
   Compiling fnv v1.0.7
   Compiling httparse v1.5.1
   Compiling bytes v0.5.6
   Compiling num-derive v0.2.5
   Compiling gstreamer v0.16.7
   Compiling version_check v0.1.5
   Compiling pnet_base v0.26.0
   Compiling color_quant v1.1.0
   Compiling ucd-trie v0.1.3
   Compiling ryu v1.0.6
   Compiling paste v1.0.6
   Compiling byte-tools v0.3.1
   Compiling glob v0.2.11
   Compiling muldiv v0.2.1
   Compiling pin-project-lite v0.1.12
   Compiling futures-sink v0.3.18
   Compiling serde_json v1.0.72
   Compiling maplit v1.0.2
   Compiling pretty-hex v0.2.1
   Compiling bytes v1.1.0
   Compiling lzw v0.10.0
   Compiling gstreamer-base v0.16.5
   Compiling unicode-width v0.1.9
   Compiling hashbrown v0.11.2
   Compiling percent-encoding v1.0.1
   Compiling opaque-debug v0.2.3
   Compiling fake-simd v0.1.2
   Compiling ansi_term v0.12.1
   Compiling safemem v0.3.3
   Compiling ppv-lite86 v0.2.15
   Compiling language-tags v0.2.2
   Compiling scoped_threadpool v0.1.9
   Compiling gstreamer-app v0.16.5
   Compiling pnet v0.26.0
   Compiling percent-encoding v2.1.0
   Compiling gstreamer-video v0.16.7
   Compiling bytemuck v1.7.2
   Compiling typeable v0.1.2
   Compiling strsim v0.8.0
   Compiling traitobject v0.1.0
   Compiling try-lock v0.2.3
   Compiling quick-error v2.0.1
   Compiling tower-service v0.3.1
   Compiling httpdate v0.3.2
   Compiling checked_int_cast v1.0.0
   Compiling tracing-core v0.1.21
   Compiling sharded-slab v0.1.4
   Compiling base64 v0.10.1
   Compiling heck v0.3.3
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling memoffset v0.6.5
   Compiling num-rational v0.3.2
   Compiling num-iter v0.1.42
   Compiling rayon v1.5.1
   Compiling num-rational v0.2.4
   Compiling indexmap v1.7.0
   Compiling itertools v0.9.0
   Compiling deflate v0.7.20
   Compiling miniz_oxide v0.3.7
   Compiling deflate v0.8.6
   Compiling inflate v0.4.5
   Compiling libdbus-sys v0.2.2
   Compiling x11 v2.19.1
   Compiling autopilot v0.4.0 (https://github.com/H-M-H/autopilot-rs.git?rev=63eed09c715bfb665bb23172a3930a528e11691c#63eed09c)
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling syntex_pos v0.42.0
   Compiling tinyvec v1.5.1
   Compiling thread_local v1.1.3
   Compiling cmake v0.1.46
   Compiling unicase v1.4.2
   Compiling pnet_macros_support v0.26.0
   Compiling pest v2.1.3
   Compiling block-padding v0.1.5
   Compiling gif v0.10.3
   Compiling textwrap v0.11.0
   Compiling http v0.2.5
   Compiling base64 v0.9.3
   Compiling form_urlencoded v1.0.1
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.1
   Compiling unicode-normalization v0.1.19
   Compiling fltk-sys v1.2.20
   Compiling pest_meta v2.1.3
   Compiling log v0.3.9
   Compiling want v0.3.0
   Compiling aho-corasick v0.7.18
   Compiling crossbeam-channel v0.5.1
   Compiling http-body v0.3.1
   Compiling quote v1.0.10
   Compiling quote v0.6.13
   Compiling png v0.16.8
   Compiling png v0.15.3
   Compiling num_cpus v1.13.0
   Compiling net2 v0.2.37
   Compiling iovec v0.1.4
   Compiling pnet_sys v0.26.0
   Compiling rand_os v0.1.3
   Compiling time v0.1.43
   Compiling atty v0.2.14
   Compiling dirs-sys v0.3.6
   Compiling socket2 v0.3.19
   Compiling idna v0.1.5
   Compiling idna v0.2.3
   Compiling syntex_errors v0.42.0
   Compiling mime v0.2.6
   Compiling rand_core v0.5.1
   Compiling regex v1.5.4
   Compiling mio v0.6.23
   Compiling clap v2.34.0
   Compiling dirs v3.0.2
   Compiling weylus v0.11.4 (/mnt/c/Users/matth/Documents/Development/Weylus)
   Compiling dbus v0.9.5
   Compiling url v2.2.2
   Compiling crossbeam-deque v0.8.1
   Compiling syntex_syntax v0.42.0
   Compiling url v1.7.2
   Compiling rand_chacha v0.2.2
   Compiling rand v0.7.3
   Compiling hyper v0.10.16
   Compiling image v0.23.14
   Compiling pest_generator v2.1.3
   Compiling qrcode v0.12.0
   Compiling jpeg-decoder v0.1.22
   Compiling fltk v1.2.20
   Compiling syntex v0.42.2
   Compiling generic-array v0.12.4
   Compiling pnet_macros v0.26.0
   Compiling digest v0.8.1
   Compiling block-buffer v0.7.3
   Compiling sha-1 v0.8.2
   Compiling thiserror-impl v1.0.30
   Compiling strum_macros v0.18.0
   Compiling futures-macro v0.3.18
   Compiling tokio-macros v0.2.6
   Compiling pin-project-internal v1.0.8
   Compiling tracing-attributes v0.1.18
   Compiling pest_derive v2.1.0
   Compiling websocket-base v0.26.2
   Compiling websocket v0.26.2
   Compiling structopt-derive v0.4.18
   Compiling pnet_packet v0.26.0
   Compiling tiff v0.3.1
   Compiling image v0.22.5
   Compiling tokio v0.2.25
   Compiling tokio-util v0.3.1
   Compiling futures-executor v0.3.18
   Compiling pin-project v1.0.8
   Compiling tracing v0.1.29
   Compiling thiserror v1.0.30
   Compiling tracing-futures v0.2.5
   Compiling h2 v0.2.7
   Compiling structopt v0.3.25
error[E0107]: this struct takes 3 generic arguments but 2 generic arguments were supplied
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.2.7/src/proto/streams/store.rs:15:10
   |
15 |     ids: IndexMap<StreamId, SlabIndex>,
   |          ^^^^^^^^ --------  --------- supplied 2 generic arguments
   |          |
   |          expected 3 generic arguments
   |
note: struct defined here, with 3 generic parameters: `K`, `V`, `S`
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/indexmap-1.7.0/src/map.rs:76:12
   |
76 | pub struct IndexMap<K, V, S> {
   |            ^^^^^^^^ -  -  -
help: add missing generic argument
   |
15 |     ids: IndexMap<StreamId, SlabIndex, S>,
   |                                      +++

For more information about this error, try `rustc --explain E0107`.
error: could not compile `h2` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed```

Any idea? Seems to be an uncommon issue.

**Comment by Schischu** [comment]
Just found a workaround:
export CARGO_FEATURE_STD=1

**Comment by Schischu** [comment]
libx264-dev is also necessary in the dependencies. I update apt-get from the first post to reflect this.

Unfortunately lots of linking errors with the ffmpeg prebuild:
[stdout.log](https://github.com/H-M-H/Weylus/files/7699879/stdout.log)

```error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/deps/weylus-eb084b983b11b064.weylus.5f54695d-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/deps" "-L" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/build/weylus-de6a1f99f4d152cf/out" "-L" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/build/weylus-de6a1f99f4d152cf/out" "-L" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/build/weylus-de6a1f99f4d152cf/out" "-L" "deps/dist/lib" "-L" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/build/weylus-de6a1f99f4d152cf/out" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/build/fltk-sys-bbbc0e686b2e5821/out/build" "-L" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/build/fltk-sys-bbbc0e686b2e5821/out/build/Release" "-L" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/build/fltk-sys-bbbc0e686b2e5821/out/lib" "-L" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/build/fltk-sys-bbbc0e686b2e5821/out/lib64" "-L" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/build/fltk-sys-bbbc0e686b2e5821/out/lib/Release" "-L" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/build/fltk-sys-bbbc0e686b2e5821/out/lib64/Release" "-L" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lerror" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-llog" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lvideo" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lavcodec" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lavdevice" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lavfilter" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lavformat" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lavutil" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lpostproc" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lswresample" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lswscale" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lx264" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-llinux" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-lX11" "-lXext" "-lXrandr" "-lXfixes" "-lXcomposite" "-lXi" "-lva" "-lva-drm" "-lva-x11" "-ldrm" "-Wl,-Bstatic" "/tmp/rustcqd568n/libfltk_sys-380ee010f8c090e3.rlib" "-Wl,--start-group" "-Wl,--end-group" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-2a0b2a4f96acb821.rlib" "-Wl,-Bdynamic" "-lgstvideo-1.0" "-lgstbase-1.0" "-lgstreamer-1.0" "-lgobject-2.0" "-lglib-2.0" "-lX11" "-lXtst" "-lpng" "-lpthread" "-lX11" "-lXext" "-lXinerama" "-lXcursor" "-lXrender" "-lXfixes" "-lXft" "-lfontconfig" "-lgstapp-1.0" "-lgstbase-1.0" "-lgstreamer-1.0" "-lgobject-2.0" "-lglib-2.0" "-lgstbase-1.0" "-lgstreamer-1.0" "-lgobject-2.0" "-lglib-2.0" "-lgstreamer-1.0" "-lgobject-2.0" "-lglib-2.0" "-lgobject-2.0" "-lglib-2.0" "-ldbus-1" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/mnt/c/Users/matth/Documents/Development/Weylus/target/release/deps/weylus-eb084b983b11b064" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /usr/bin/ld: deps/dist/lib/libavdevice.a(libavdevice/file_open.o):(.text$mn+0x0): multiple definition of `av_fopen_utf8'; deps/dist/lib/libavcodec.a(libavcodec/file_open.o):(.text$mn+0x0): first defined here
          /usr/bin/ld: deps/dist/lib/libavdevice.a(libavdevice/file_open.o):(.text$mn+0x0): multiple definition of `ff_open'; deps/dist/lib/libavcodec.a(libavcodec/file_open.o):(.text$mn+0x0): first defined here
...
          /usr/bin/ld: deps/dist/lib/libavcodec.a(libavcodec/x86/vp9dsp_init_12bpp.o):(.xdata[$unwind$put_8tap_regular_64hv_12_sse2]+0x18): more undefined references to `__GSHandlerCheck' follow
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

warning: `weylus` (bin "weylus") generated 3 warnings
error: could not compile `weylus` due to previous error; 3 warnings emitted
```

**Comment by H-M-H** [comment]
As your are building via WSL which is essentially a Linux Virtual Machine, in your case running Ubuntu,  https://github.com/H-M-H/Weylus/issues/17#issuecomment-978003096 is not applicable as this is for compiling the Windows version of Weylus as opposed to building a Linux version on Windows using WSL. Delete `deps/dist` and rebuild, this should compile a Linux version of ffmpeg and x264 and solve your linking errors.

**Comment by H-M-H** [comment]
Assuming you actually want to build a version of Weylus that natively runs on Windows, do not use WSL (except you want to cross compile via mingw (you probably don't)).

**Comment by Schischu** [comment]
@H-M-H, I see. Indeed I want to build a native version for Windows. So if not WSL2 what else to use? Cygwin?

**Comment by H-M-H** [comment]
Install rust native for Windows: https://forge.rust-lang.org/infra/other-installation-methods.html (for example via the installer or http://chocolatey.org/), then follow the instructions in https://github.com/H-M-H/Weylus/issues/17#issuecomment-978003096. A unix like environment with stuff like bash is only required for building ffmpeg (yes, you can not build ffmpeg on Windows without bash...).

I assume you are looking into touch support for Windows, thanks for that!

**Comment by Schischu** [comment]
Thanks. Now the build went so smoothly that I am quite annoyed at the lost 2h cause of my using WSL.....

**Comment by H-M-H** [comment]
I included uploading of build artifacts for ffmpeg and typescript into the master branch, so if in the future you need an up to date version of the ffmpeg libs or `lib.js`, you can download `Windows-deps`.
