### ISSUE TITLE
Can't Change Monitor

### ISSUE THREAD

**Issue by Xanth0k1d** [H-M-H/Weylus#135]
Hi, thanks for this awesome software.
I can't seem to change the monitor I want to share, only screen available is Desktop(autopilot)
![image](https://user-images.githubusercontent.com/34358644/148684827-06d385fd-a7a9-455b-a27b-f05da8a3ef74.png)
Host is Windows 11

**Comment by Xanth0k1d** [comment]
My bad, this does not work on windows or Mac

**Comment by H-M-H** [comment]
This is being worked on in #128, if you feel adventurous you can download an experimental build here: https://github.com/H-M-H/Weylus/suites/4839038746/artifacts/137400212
