### ISSUE TITLE
Old Android devices not working

### ISSUE THREAD

**Issue by UmTiozinQualquer** [H-M-H/Weylus#137]
I'm not sure if this is the right place to take notice of this, mostly because its an very specific problem.

So, i have this old samsung tablet (Android 3.2) from when i was younger and stuff
Recently i found it and thought to myself if i could use it for something, and i saw this project and as the tablet has a quite big screen i decided to try to use it.

When i put the link on it, it kinda connects but it doesn't?

Even thought on the tablet screen in connected, the console says nothing about an device connecting

![capture_01](https://user-images.githubusercontent.com/67398127/149240102-40ab8c15-fbf5-4458-aa8a-4ce65c7f9407.png)

I tried Firefox and the Internet Explorer, and on the Internet Explorer i could mess around with the settings even though it changed nothing (Firefox just straight up did not work)
I am not really sure what is causing the problem, it looks like the tablet just doesn't load the 'Video" but theoretically it should work, as i found an developer forum from android saying it is compatible with H.264 (https://developer.android.com/guide/topics/media/media-formats#video-codecs)

And i tried with an old samsung phone (Android 5.X) on Chrome and it worked fine
I thought about trying to install Chrome on the tablet but i couldn't find an old enough version to be compatible

I am not sure on how to resolve this problem, mostly because i'm very new on code and stuff, and not even sure if there is an solution
But hey, if there's someway to make this E-Waste somewhat usefull i would be very happy
I appreciate if you read this far

**Comment by H-M-H** [comment]
Thanks for the report!

Unfortunately Weylus requires a relatively modern browser to work. The video is streamed via websockets and [Media Source Extensions](https://caniuse.com/?search=mediasource) are required to feed the data obtained from the websocket into the video element. It appears that the browsers available to you don't support that.

If at all possible try to get a more recent browser running on your tablet. If that does not work and you want to do some hacking yourself, it is pretty easy to write a custom client for Weylus and at least mirroring your screen shouldn't be too hard, for details see my comment here: https://github.com/H-M-H/Weylus/issues/136#issuecomment-1009388808

**Comment by UmTiozinQualquer** [comment]
Thanks you, i'll try that
Wish me luck on it!
