### ISSUE TITLE
Pointer geometry wrong with multiple displays

### ISSUE THREAD

**Issue by rschroll** [H-M-H/Weylus#14]
If I launch Weylus with multiple displays active, the geometry calculation for the pointer is wrong.  It appears that the total desktop size is being mixed up with a single display size.  Both my primary and secondary monitors have the same resolution.  If I have these set up side-by-side, Weylus positions the cursor at half the x position that it should.  This happens regardless of whether I am capturing the whole desktop, a single display, or a single window.  If I have the displays set up vertically, the cursor is placed at half the y position that it should.

Interestingly, only the display geometry at Weylus's start matters.  If adjust the displays after Weylus is running, the problem remains.  Or if I start Weylus with only a single display active, it works perfectly when I add another display.

This is seen running 0.7.1 on Ubuntu 20.04 with the Gnome DE on X.

Please let me know if there's additional debugging I can provide.

**Comment by H-M-H** [comment]
Thanks for the report, it looks like the inputs are only mapped to one of your monitors even though they should be mapped to the whole desktop. Apparently this default mapping is not the same on all Desktop Environments (it works for me). A solution is probably to explicitly map inputs to the whole desktop. If you find out how to do this it can probably be added to Weylus.

This can probably be done with xinput as described here: https://wiki.archlinux.org/index.php/Calibrating_Touchscreen

For debugging purposes: The output of
```
xrandr
xinput list-props "Weylus"
xinput list-props "Weylus Touch"
xinput list-props "Weylus Mouse"
```
is probably helpful.

**Comment by H-M-H** [comment]
Reference for myself, this is how xinput does it:
```c
static int
apply_matrix(Display *dpy, int deviceid, Matrix *m)
{
    Atom prop_float, prop_matrix;

    union {
        unsigned char *c;
        float *f;
    } data;
    int format_return;
    Atom type_return;
    unsigned long nitems;
    unsigned long bytes_after;

    int rc;

    prop_float = XInternAtom(dpy, "FLOAT", False);
    prop_matrix = XInternAtom(dpy, "Coordinate Transformation Matrix", False);

    if (!prop_float)
    {
        fprintf(stderr, "Float atom not found. This server is too old.\n");
        return EXIT_FAILURE;
    }
    if (!prop_matrix)
    {
        fprintf(stderr, "Coordinate transformation matrix not found. This "
                "server is too old\n");
        return EXIT_FAILURE;
    }

    rc = XIGetProperty(dpy, deviceid, prop_matrix, 0, 9, False, prop_float,
                       &type_return, &format_return, &nitems, &bytes_after,
                       &data.c);
    if (rc != Success || prop_float != type_return || format_return != 32 ||
        nitems != 9 || bytes_after != 0)
    {
        fprintf(stderr, "Failed to retrieve current property values\n");
        return EXIT_FAILURE;
    }

    memcpy(data.f, m->m, sizeof(m->m));

    XIChangeProperty(dpy, deviceid, prop_matrix, prop_float,
                     format_return, PropModeReplace, data.c, nitems);

    XFree(data.c);

    return EXIT_SUCCESS;
}
```

**Comment by rschroll** [comment]
[`xrandr` with a single monitor active](https://github.com/H-M-H/Weylus/files/4777408/xrandr.1monitor.txt)
[`xrandr` with both monitors active](https://github.com/H-M-H/Weylus/files/4777409/xrandr.2monitors.txt)


[`xinput list-props "Weylus"`](https://github.com/H-M-H/Weylus/files/4777404/xinput.weylus.txt) was the same when Weylus was started in the two different monitor configurations.

[`xinput list-props "Weylus Mouse"`](https://github.com/H-M-H/Weylus/files/4777405/xinput.weylusmouse.txt) was the same when Weylus was started in the two different monitor configurations.

[`xinput list-props "Weylus Touch"`](https://github.com/H-M-H/Weylus/files/4777406/xinput.weylustouch.1monitor.txt) when Weylus was launched with a single monitor active.  This did not change when the second monitor was activated.
[`xinput list-props "Weylus Touch"`](https://github.com/H-M-H/Weylus/files/4777407/xinput.weylustouch.2monitors.txt) when Weylus was launched with both monitors active.  In this case, the geometry was wrong.  The only difference seems to be in the xx component of the coordinate transformation matrix.

**Comment by H-M-H** [comment]
Thanks! Ok, in this case please check if `xinput set-prop "Weylus Touch" --type=float "Coordinate Transformation Matrix" 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000` corrects the geometry.

**Comment by rschroll** [comment]
Yep, that fixes it!

It's probably moot at this point, but I just thought to check that mouse on the tablet works correctly.  It's only the touch interface that was misscaled.  (This makes sense given that I saw the "Weylus Mouse" properties didn't change with the number of monitors.

**Comment by H-M-H** [comment]
Great, please try if it works out of the box now, I added setting correct mapping with: https://github.com/H-M-H/Weylus/commit/efc8b15867f4840ad7f4beecbc111f963f5d7e7f

**Comment by rschroll** [comment]
No joy, I'm afraid.  I built 09001fd, since it happened to be the HEAD at the time I pulled it.  This seems to have the same problem before.  I could correct it by once again setting the xx element of the transformation matrix to 1 from 0.5.

I'm worried that I messed up which binary I was using, so I can try again to be sure.  I don't know how reproducible the builds are, but I built inside of docker and got a md5sum of `97621dbcc67135c12b0176e3b4e1752e`.  Don't know if that makes sense to check against your results?

**Comment by H-M-H** [comment]
Please run Weylus like this then: `WEYLUS_LOG_LEVEL=TRACE weylus` it will display additional log messages if setting the coord. transform succeeds of fails.

**Comment by rschroll** [comment]
It's definitely something else jumping in and messing things up.  First, the trace output definitely shows the mapping working.

```
INFO Found more than one IP address for browsers to connect to,
INFO other urls are:
INFO http://172.17.0.1:1701
INFO Webserver listening at 0.0.0.0:1701...
INFO Client connected: 192.168.1.75:45898
TRACE Failed to map input device to screen: CError: code: 2 message: Device with name: Weylus Mouse - 192.168.1.75:41632 not found!
TRACE Failed to map input device to screen: CError: code: 2 message: Device with name: Weylus Touch - 192.168.1.75:41632 not found!
TRACE Failed to map input device to screen: CError: code: 2 message: Device with name: Weylus Mouse - 192.168.1.75:41632 not found!
TRACE Failed to map input device to screen: CError: code: 2 message: Device with name: Weylus Touch - 192.168.1.75:41632 not found!
TRACE Failed to map input device to screen: CError: code: 2 message: Device with name: Weylus Mouse - 192.168.1.75:41632 not found!
TRACE Failed to map input device to screen: CError: code: 2 message: Device with name: Weylus Touch - 192.168.1.75:41632 not found!
TRACE Failed to map input device to screen: CError: code: 2 message: Device with name: Weylus Touch - 192.168.1.75:41632 not found!
TRACE Succeeded mapping input devices to screen!
```

So I ran a `xinput list-props` in a loop.  When the touch device first appears it has the proper value.  But after six cycles through the loop (run with `while true`), it changes to the wrong value.  I'm not sure what's doing this, and I've never used a stylus or touch device with this computer before, so I don't know where to start to look.  I don't see any obvious values to change in the Gnome control center.

I tried changing the polling interval in the thread from 10ms to 1s, with the hope that this would allow the incorrect setting to "win", and Weylus to correct things afterwards.  This worked (in one test, at least), but it's ugly and leaves a race condition in the code. If you want to fix in this in Weylus, maybe the best approach would be to add a "Fix geometry" button to the GUI that would trigger this.  But it's also fair to say that this is an Ubuntu / Gnome problem.  I can keep digging and report back if I find anything.

**Comment by H-M-H** [comment]
Nice debugging! You could try grepping `/etc/X11` for `TransformationMatrix`, according to `man xorg.conf` this could be the culprit.

>  I can keep digging and report back if I find anything.

Please do :)

**Comment by rschroll** [comment]
Some tidbits:
- Nothing obvious anywhere in `/etc`.  `/etc/X11` is particularly empty, but I think that's part of the trend to move configuration out of files and into reactive tools.
- The bottom of [this (old) page](https://wiki.ubuntu.com/X/InputCoordinateTransformation) points out the transformation I'm seeing as the way to map stylus input to a single screen.  And in most cases this is probably reasonable behavior.  I suspect something is trying to be friendly here.
- There's an `xinput map-to-output` command that will automatically set this matrix.  I've been looking for a call to that, but no luck yet.
- The gnome control center has [an option](https://askubuntu.com/a/1092075) to map a tablet input to one monitor.  But I'm seeing "No tablet detected" even when Weylus is active.  Perhaps this is selected by default, and I can't turn it off.  The fact that the section is titled "Wacom tablet" doesn't make me particularly confident that this is a general tool.

**Comment by H-M-H** [comment]
Too bad, until a proper solution is found I will go with working around this by just sleeping 3 seconds and then forcing the correct mapping https://github.com/H-M-H/Weylus/commit/c9c0bbd502417f52763700ba64912280b8af1126.

**Comment by rschroll** [comment]
Thanks!  I've built from this version and it works ... for my finger.  However, when I happened to try with a stylus, the geometry was wrong again.  (I hadn't tested separately, as I had assumed they were the same.)  I notice that there's now a "Weylus Stylus" device, and sure enough, its transformation matrix was wrong.  `xinput set-prop` set it right.  I tried mimicking the existing code for mouse and touch resetting with the stylus, but it didn't seem to work.  I wouldn't rule out user error, though, so I'm happy to try again if it seems like it should work.

**Comment by H-M-H** [comment]
For some reason setting `Coordinate Transformation Matrix` does work neither programmatically  nor via xinput for the Stylus device on my system, but setting `libinput Calibration Matrix` has the desired effect. I just pushed some changes implementing that, maybe it works for you too. If not, can you give me the output of `xinput list` and `xinput list-props` for the Weylus devices?

**Comment by rschroll** [comment]
No luck, I'm afraid.  FWIW, my stylus listing doesn't have a Calibration Matrix, only a transformation matrix.  When I set it with `xinput`, it works.  In case it matters:
```
$ xinput version
xinput version 1.6.3
XI version on server: 2.3
```

[xinput.txt](https://github.com/H-M-H/Weylus/files/4795236/xinput.txt)
[xinput.mouse.txt](https://github.com/H-M-H/Weylus/files/4795232/xinput.mouse.txt)
[xinput.stylus.txt](https://github.com/H-M-H/Weylus/files/4795234/xinput.stylus.txt)
[xinput.touch.txt](https://github.com/H-M-H/Weylus/files/4795235/xinput.touch.txt)

**Comment by H-M-H** [comment]
Ok, I think I know what's happening and I think it is stupid. Looking at the list `xinput` gives you there are two stylus devices: `Weylus Stylus - 192.168.1.75:35440` and `Weylus Stylus - 192.168.1.75:35440 Pen (0)`. Some tests on my machine show that only `Weylus Stylus - 192.168.1.75:35440 Pen (0)` has a configurable `Coordinate Transformation Matrix`, which is why setting it programmatically did not work as the code attempts to alter the `Coordinate Transformation Matrix` of `Weylus Stylus - 192.168.1.75:35440` without the `Pen (0)` in its name.
To make things worse it looks like `Weylus Stylus - 192.168.1.75:35440 Pen (0)` only appears after there has been some input, so either (random?) input has to be simulated or the Matrix has to be set after the first input of the stylus (probably needs some sleeping too).
There has to be a better way to do this, I really do not like where this is going...

Thanks for your patience by the way.

**Comment by rschroll** [comment]
That does it!  I've tested both 83aa4a5 and current master, and the geometry is correct for both.  Thanks for all the work!

**Comment by H-M-H** [comment]
Great, that is a relieve!
