### ISSUE TITLE
Not working on Windows 11

### ISSUE THREAD

**Issue by ehabcharek** [H-M-H/Weylus#140]
I haven't been able to get Weylus to work on my computer, running Windows 11
when I run the service, it shows this
![image](https://user-images.githubusercontent.com/8967433/151917513-e6bb20d0-72bf-488b-ae64-d21cdff23197.png)
which I know is incorrect because Weylus has worked for me on manjaro at work out of the box, and it didn't look like this

and when I stop it and run again it gives me this error: 
`ERROR Webserver error: Failed to start webserver: error creating server listener: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
INFO Shutting down websocket: 0.0.0.0:9001`

are there any system settings I should be adjusting?

**Comment by H-M-H** [comment]
Thanks for the report, it seems Windows 11 doesn't like binding on `0.0.0.0`. This is supposed to make Weylus listen on all network interfaces available, which apparently is not permitted. Try changing the `Bind Address` field to the actual IP-Address of your computer. You can find out your IP by typing `ipconfig` into `cmd.exe`.

**Comment by ehabcharek** [comment]
that worked, thank you!
altho, it's very laggy unfortunately. Not nearly as usable as linux, even on the same wifi network
while I'm here, I have a question, completely unrelated to the topic so I apologize about that. Is it possible to emulate middle and right mouse buttons with the stylus and 1/2 finger presses? it would be useful for panning in painting and 3D applications

**Comment by H-M-H** [comment]
> altho, it's very laggy unfortunately

I am not surprised, I have put quite some work into making it fast on Linux, this is not the case for the windows version. But you can try the binary from this build: https://github.com/H-M-H/Weylus/actions/runs/1658407211 It should make encoding quite a bit faster.

Emulating button presses with the stylus is somewhat complicated, see https://github.com/H-M-H/Weylus/issues/66 for example. Basically browser support for stylus buttons is rather poor.

**Comment by ehabcharek** [comment]
thank you for the link, it works much better!
Lack of pressure sensitivity aside, I can definitely work with this now!

**Comment by ehabcharek** [comment]
ah nvm, using the windows ink API makes it possible to use pressure!
