### ISSUE TITLE
Feature Request, Stylus Hover

### ISSUE THREAD

**Issue by lukeycold** [H-M-H/Weylus#142]
I'm not sure if this is doable since I don't know if the API mentioned in the readme supports it. But I have a Galaxy Tab S7 and it works great. However, the biggest issue I have is that the mouse doesn't move around when I hover the pen over the screen like it would in other applications on windows. So it would be really helpful to add hover support for pens capable of doing hover like the S-Pen. If it's not possible I understand.

**Comment by H-M-H** [comment]
Actually Weylus already supports hovering. The API for pointerevents supports hovering just fine and Weylus forwards theses events using uinput and can simulate hovering. That is, as long as the browser actually implements the API properly and sends the correct events.

Personally I have a device that used to not send those events properly but that's changed a few months ago and now I do have proof that hovering actually works, with a correct implementation that is.

In turn this unfortunately means, there is not much I can do to add support for hovering for other devices.

**Comment by michcio1234** [comment]
@H-M-H could you please let us know what device and browser you're using to make it work?

**Comment by H-M-H** [comment]
I do not typically use the device in combination with Weylus except for testing. It's an Onyx Boox Note 2 running version 3.2.3. Both Firefox (Fennec) as well as Chrome work fine for hovering.

**Comment by MicaelJarniac** [comment]
@lukeycold what browser app were you using? And did you manage to get it to work?

I've just purchased a Galaxy Tab S8, but it didn't arrive yet.

**Comment by lukeycold** [comment]
I just saw your comments, thank you! I'll try it when I get home!

**Comment by lukeycold** [comment]
> Actually Weylus already supports hovering. The API for pointerevents supports hovering just fine and Weylus forwards theses events using uinput and can simulate hovering. That is, as long as the browser actually implements the API properly and sends the correct events.
> 
> Personally I have a device that used to not send those events properly but that's changed a few months ago and now I do have proof that hovering actually works, with a correct implementation that is.
> 
> In turn this unfortunately means, there is not much I can do to add support for hovering for other devices.

You are so helpful. Thank you for expressing your limits of what you are able to do. However, all I wanted was something that worked. I was using Brave on my Galaxy Tab S7 and I guess it didn't have the stylus support properly implemented. So I figured that the next best thing for general software compatibility would be FireFox. And would you believe it? It worked! I can't express how thankful I am for this. I've searched a full year for something that would work for a drawing tablet with a tablet on Linux. Only to come out striking out with this being the closest thing to what I could get with no hover. But now you have finally made this a reality. So thank you so much for just explaining to me such a simple workaround!

**Comment by MicaelJarniac** [comment]
I tested it on another tablet of mine, an ONYX BOOX Note Air, and I do get hover on Firefox, but not on Chrome.

**Comment by MicaelJarniac** [comment]
@lukeycold can you confirm pen pressure is working on Firefox? For me, on Chrome I get pen pressure but no hover, and on Firefox I get no pen pressure but hover.

**Comment by lukeycold** [comment]
Oh, I see what you mean. I thought it was because I hadn't set up uinput yet, but I can only use pressure on chrome vs hover on Firefox. That is odd. Are there any browsers that have different results?

**Comment by lukeycold** [comment]
> @lukeycold can you confirm pen pressure is working on Firefox? For me, on Chrome I get pen pressure but no hover, and on Firefox I get no pen pressure but hover.

I checked several browsers and the only one that seems to have both work is the UC Browser but it doesn't have video working. I can live with it but it isn't great. I wonder if Firefox has an extension that could fix this issue in the app itself.

**Comment by MicaelJarniac** [comment]
I've opened an issue to try to find what's the best browser: #178
