### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by suzabelle** [H-M-H/Weylus#143]
Hi, this works great, except that I was wondering if it could do the opposite.
I installed it on my MacBook Air, and used QR scanner on iPad. So the iPad is mirroring the MacBook.
Can I do the opposite, like in your demo - use the MacBook as a mirror to the iPad?

**Comment by H-M-H** [comment]
Weylus only mirrors your MacBook to the iPad. That's also what's happening in the demo. There you can see that Xournal++ which is running on the laptop is controlled via the iPad, which only mirrors my laptop screen.

If all you want to do is stream your iPad screen to your MacBook have a look at QuickTime, which supports streaming from your iPad.
