### ISSUE TITLE
Feature request: Multitouch for Windows <3

### ISSUE THREAD

**Issue by ItsCubeTime** [H-M-H/Weylus#145]
Feature request: Multitouch for Windows <3

**Comment by H-M-H** [comment]
This is or at least was being worked on in https://github.com/H-M-H/Weylus/issues/17 and https://github.com/H-M-H/Weylus/pull/128. Unfortunately I am pretty busy with other things right now and this will have to wait a little longer.

**Comment by ItsCubeTime** [comment]
> This is or at least was being worked on in #17 and #128. Unfortunately I am pretty busy with other things right now and this will have to wait a little longer.

Thanks for the reply :) Me and some friends are getting into mobile development, multi-touch support would let us use Weylus to do faster game testing

**Comment by qdlmcfresh** [comment]
Hey @ItsCubeTime if you are still interested you can try out this build. https://github.com/H-M-H/Weylus/actions/runs/2400915797
