### ISSUE TITLE
Weylus on boot

### ISSUE THREAD

**Issue by qcgilbert** [H-M-H/Weylus#147]
Trying to get weylus to start on boot using systemd.  Weylus login screen and can log in but screen is blank, Capture dropdown only shows Desktop (autopilot).  Refresh list does nothing.  Below is the contents of my systemd unit file.

[Unit]
Description=Weylus Remote Desktop
After=graphical.target

[Service]
Type=oneshot
ExecStart=/usr/bin/weylus --auto-start --no-gui --try-nvenc --access-code ####
Environment=DISPLAY=:1

[Install]
WantedBy=default.target

Logs show the following:
`weylus[1628]: Authorization required, but no authorization protocol specified
Mar 19 16:06:50 cg-pc weylus[1628]: thread '<unnamed>' panicked at 'Can't open X display. Is it currently running?', /home/bob/.cargo/git/checkouts/autopilot-rs-fed2c>`

**Comment by parkerlreed** [comment]
When you login that kills the X server and spawns a new one. You need to launch Weylus from your X session as a systemctl user service and not system wide. 

If you don't want auto login you would have to keep what you have now and relaunch it as the user.

**Comment by H-M-H** [comment]
@parkerlreed thanks for answering! @qcgilbert I hope this resolves your issue, if not comment and I will reopen this.
