### ISSUE TITLE
Touch screen Failed！！！

### ISSUE THREAD

**Issue by crownclownwl** [H-M-H/Weylus#148]
When you refresh the page for the first time, you can use the touch screen, and after 3 seconds, you can't use it

this is my pc terminal info when Weylus to run：
![image](https://user-images.githubusercontent.com/11539526/161433212-1462b40d-8e9d-4041-884e-cdbe46c64eb8.png)

Other features are good, only touch the screen is not good to make

This is my HardInfo
![image](https://user-images.githubusercontent.com/11539526/161433267-e4f15acc-9004-4c73-bca7-ba011df1950a.png)

the cpu is  intel 11th 1165G7
the GPU is Nvidia max450 2GB
the memory is 8GB + 32 GB DDR4

The receiving device is HarmonyOS（华为鸿蒙） 2.0，honour v6 tablet（Based on Android 10 system）
The tablet's browser is Firefox 98.3.0(Build @2015870329), and I tried to edge browser too。

**Comment by crownclownwl** [comment]
this is program info：
```shell
INFO Webserver listening at 0.0.0.0:1701...
INFO Found more than one IP address for browsers to connect to,
INFO other urls are:
INFO http://192.168.250.1:1701
INFO Client connected. address=192.168.1.4:60812
INFO WS-Client authenticated! address=192.168.1.4:60812
INFO using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
INFO profile Constrained Baseline, level 6.1, 4:2:0, 8-bit
INFO 264 - core 163 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=8 lookahead_threads=8 sliced_threads=1 slices=8 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=12 keyint_min=1 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
INFO Video: 1774x998@libx264 pix_fmt: yuv420p
```

**Comment by H-M-H** [comment]
Thanks for the report, please try again and run Weylus like this `WEYLUS_LOG_LEVEL="DEBUG" weylus` and post the log!
