### ISSUE TITLE
Mouse don't move in osu

### ISSUE THREAD

**Issue by xbyte3** [H-M-H/Weylus#152]
If I switch to osu I can't move the mouse. (via tablet)

**Comment by xbyte3** [comment]
> 

Oh, that works. Thanks

**Comment by H-M-H** [comment]
@norinorin thanks for the hint! It seems there are quite some osu! players using Weylus. I've added this hint to the FAQ.

**Comment by norinorin** [comment]
No problem! I had some fun playing with Weylus (also set my first 300pp using it, for any osu! players reading this kekw) until I got my current tablet.
