### ISSUE TITLE
macOS doesn't show mouse pointer

### ISSUE THREAD

**Issue by Marion-China** [H-M-H/Weylus#153]
macOS Monterey does not display the mouse pointer, but can display and control

**Comment by H-M-H** [comment]
Thanks for the report! Unfortunately this is an issue with the library [autopilot](https://github.com/autopilot-rs/autopilot-rs) which by the looks of it has been abandoned. I'd love to replace it with another library but I have yet to find a suitable one.

I am already using a fork with some fixes: https://github.com/H-M-H/autopilot-rs/

If anyone is interested into looking into this, this code is responsible for mouse input on macOS: https://github.com/H-M-H/autopilot-rs/blob/63eed09c715bfb665bb23172a3930a528e11691c/src/mouse.rs#L135-L199

**Comment by Marion-China** [comment]
> 谢谢你的报告！不幸的是，这是图书馆[自动驾驶仪](https://github.com/autopilot-rs/autopilot-rs)的问题，从外观上看，它已被放弃。我很想把它换成另一个图书馆，但我还没有找到一个合适的图书馆。
> 
> 我已经在使用带有一些修复方法的叉子：https://github.com/H-M-H/autopilot-rs/
> 
> 如果有人有兴趣调查此事，此代码负责macOS上的鼠标输入：https://github.com/H-M-H/autopilot-rs/blob/63eed09c715bfb665bb23172a3930a528e11691c/src/mouse.rs#L135-L199

How do I put https://github.com/H-M-H/autopilot-rs/blob/63eed09c715bfb665bb23172a3930a528e11691c/src/mouse.rs#L135-L199 into Weylus?

**Comment by Marion-China** [comment]
> Thanks for the report! Unfortunately this is an issue with the library [autopilot](https://github.com/autopilot-rs/autopilot-rs) which by the looks of it has been abandoned. I'd love to replace it with another library but I have yet to find a suitable one.
> 
> I am already using a fork with some fixes: https://github.com/H-M-H/autopilot-rs/
> 
> If anyone is interested into looking into this, this code is responsible for mouse input on macOS: https://github.com/H-M-H/autopilot-rs/blob/63eed09c715bfb665bb23172a3930a528e11691c/src/mouse.rs#L135-L199

How do I put https://github.com/H-M-H/autopilot-rs/blob/63eed09c715bfb665bb23172a3930a528e11691c/src/mouse.rs#L135-L199 into Weylus?

**Comment by Marion-China** [comment]
This problem is difficult and currently I use the tool that comes with macOS to solve it

**Comment by subashz** [comment]
@Marion-China which tool ??
