### ISSUE TITLE
Is there a touchpad mode?

### ISSUE THREAD

**Issue by kvinwang** [H-M-H/Weylus#158]
Thanks very much for making this fantastic project. I've runing Waylus under my pocket windows device.
It can transfer mouse events from the browser to the remote PC. Is it possible to simulate a traditional touchpad so that we can use a smartphone instead of a hardware mouse?

**Comment by kvinwang** [comment]
![IMG_20220524_093850](https://user-images.githubusercontent.com/6442159/169931321-c5115b23-7fe0-479f-bdb9-2a2750e08eef.jpg)

This is the use case.

**Comment by AzzieDev** [comment]
I was wondering this, as I was impulsively using it as a touchpad when trying it out, and of course, the cursor would jump.

So far, I can't successfully pinch to zoom, which you can even do with a modern touchpad.

**Comment by Kibbitzer** [comment]
Any news in regards to the implementation of relative mode, as mentioned in #98?
