### ISSUE TITLE
thread '<unnamed>' panicked at 'index out of bounds - Windows 10

### ISSUE THREAD

**Issue by seffplusplus** [H-M-H/Weylus#16]
Setup:
```
- Windows 10 LTSC 1809 (17763.1217)
- Intel Core i5 - 8250U
- Intel UHD Graphics 620 (deactivated dGPU)
- Weylus v0.7.1
```
Steps:

1.  Execute `weylus.exe`
2.  Allow weylus on Windows Firewall, start listening
3.  Once connected on client, receive error:
```
[2mJun 15 17:01:46.289[0m [32m INFO[0m weylus::web: Webserver listening at 0.0.0.0:1701...
[2mJun 15 17:02:00.762[0m [32m INFO[0m weylus::web: Client connected: 127.0.0.1:50340
[libx264 @ 000001BD3CCCA5C0] MB rate (3600000000) > level limit (16711680)
[libx264 @ 000001BD3CCCA5C0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000001BD3CCCA5C0] profile Constrained Baseline, level 6.2, 4:2:0, 8-bit
[libx264 @ 000001BD3CCCA5C0] 264 - core 159 r2999 296494a - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=8 lookahead_threads=8 sliced_threads=1 slices=8 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=12 keyint_min=1 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to '(null)':
    Stream #0:0: Video: h264, yuv420p, 1280x720, q=2-31
thread '<unnamed>' panicked at 'index out of bounds: the len is 921600 but the index is 921600', src\screen_capture\generic.rs:47:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by H-M-H** [comment]
Thanks for your report, you are the first person I know of who actually ran Weylus on Windows! Unfortunately I can not reproduce the error with wine, so I depend on your help to debug this. I just built a [debug version](https://github.com/H-M-H/Weylus/suites/799971724/artifacts/8617935) of Weylus that prints out some more information. Can you please copy its output here?

**Comment by seffplusplus** [comment]
Now this is weird... Your debug version works out of the box, I guess this is how it is supposed to behave?
```
[2mJun 15 19:34:27.928[0m [32m INFO[0m weylus::web: Webserver listening at 0.0.0.0:1701...
[2mJun 15 19:34:29.163[0m [32m INFO[0m weylus::web: Client connected: 192.168.0.44:34835
[libx264 @ 00000258EFC733C0] MB rate (5700000000) > level limit (16711680)
[libx264 @ 00000258EFC733C0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 00000258EFC733C0] profile Constrained Baseline, level 6.2, 4:2:0, 8-bit
[libx264 @ 00000258EFC733C0] 264 - core 159 r2999 296494a - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=8 lookahead_threads=8 sliced_threads=1 slices=8 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=12 keyint_min=1 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to '(null)':
    Stream #0:0: Video: h264, yuv420p, 1600x900, q=2-31
[2mJun 15 19:34:29.570[0m [35mTRACE[0m weylus::screen_capture::generic: Converting rgb to yuv.
[2mJun 15 19:34:29.570[0m [35mTRACE[0m weylus::screen_capture::generic: width: 1600 height: 900 y.len(): 1440000 u.len(): 720000 v.len(): 720000 y_line_size: 1600 u_line_size: 800 v_line_size: 800 img.width: 1600 img.height: 900
[2mJun 15 19:34:30.211[0m [35mTRACE[0m weylus::screen_capture::generic: Converting rgb to yuv.
[2mJun 15 19:34:30.211[0m [35mTRACE[0m weylus::screen_capture::generic: width: 1600 height: 900 y.len(): 1440000 u.len(): 720000 v.len(): 720000 y_line_size: 1600 u_line_size: 800 v_line_size: 800 img.width: 1600 img.height: 900
[2mJun 15 19:34:30.862[0m [35mTRACE[0m weylus::screen_capture::generic: Converting rgb to yuv.
[2mJun 15 19:34:30.862[0m [35mTRACE[0m weylus::screen_capture::generic: width: 1600 height: 900 y.len(): 1440000 u.len(): 720000 v.len(): 720000 y_line_size: 1600 u_line_size: 800 v_line_size: 800 img.width: 1600 img.height: 900
[2mJun 15 19:34:31.531[0m [35mTRACE[0m weylus::screen_capture::generic: Converting rgb to yuv.
[2mJun 15 19:34:31.531[0m [35mTRACE[0m weylus::screen_capture::generic: width: 1600 height: 900 y.len(): 1440000 u.len(): 720000 v.len(): 720000 y_line_size: 1600 u_line_size: 800 v_line_size: 800 img.width: 1600 img.height: 900
[2mJun 15 19:34:32.092[0m [35mTRACE[0m weylus::stream_handler: Pointerevent: {"PointerEvent":{"event_type":"pointerdown","pointer_id":2,"timestamp":2968300,"is_primary":true,"pointer_type":"touch","button":1,"buttons":1,"x":0.4921875,"y":0.47800927691989475,"movement_x":0,"movement_y":0,"pressure":1,"tilt_x":0,"tilt_y":0,"width":0.00047495913143358597,"height":0.00047495913143358597,"twist":0}}
[2mJun 15 19:34:32.151[0m [35mTRACE[0m weylus::stream_handler: Pointerevent: {"PointerEvent":{"event_type":"pointermove","pointer_id":2,"timestamp":3015300,"is_primary":true,"pointer_type":"touch","button":0,"buttons":1,"x":0.4927083492279053,"y":0.47800927691989475,"movement_x":0,"movement_y":0,"pressure":1,"tilt_x":0,"tilt_y":0,"width":0.00047495913143358597,"height":0.00047495913143358597,"twist":0}}
```

and goes on until server shutdown
```
[2mJun 15 19:36:17.932[0m [32m INFO[0m weylus::web: Webserver shutdown!
[2mJun 15 19:36:17.952[0m [32m INFO[0m weylus::websocket: Shutting down websocket: 0.0.0.0:9002
[2mJun 15 19:36:17.952[0m [32m INFO[0m weylus::websocket: Shutting down websocket: 0.0.0.0:9001
[2mJun 15 19:36:18.025[0m [33m WARN[0m weylus::stream_handler: Error sending video: An established connection was aborted by the software in your host machine. (os error 10053)
[2mJun 15 19:36:18.294[0m [35mTRACE[0m weylus::screen_capture::generic: Converting rgb to yuv.
[2mJun 15 19:36:18.294[0m [35mTRACE[0m weylus::screen_capture::generic: width: 1600 height: 900 y.len(): 1440000 u.len(): 720000 v.len(): 720000 y_line_size: 1600 u_line_size: 800 v_line_size: 800 img.width: 1600 img.height: 900
[2mJun 15 19:36:18.682[0m [33m WARN[0m weylus::stream_handler: Error sending video: An established connection was aborted by the software in your host machine. (os error 10053)
[2mJun 15 19:36:18.944[0m [35mTRACE[0m weylus::screen_capture::generic: Converting rgb to yuv.
[2mJun 15 19:36:18.946[0m [35mTRACE[0m weylus::screen_capture::generic: width: 1600 height: 900 y.len(): 1440000 u.len(): 720000 v.len(): 720000 y_line_size: 1600 u_line_size: 800 v_line_size: 800 img.width: 1600 img.height: 900
[2mJun 15 19:36:19.330[0m [33m WARN[0m weylus::stream_handler: Error sending video: An established connection was aborted by the software in your host machine. (os error 10053)
[2mJun 15 19:36:19.330[0m [33m WARN[0m weylus::websocket: Error reading message from websocket, closing (WebSocketError: I/O failure)
[2mJun 15 19:36:19.330[0m [33m WARN[0m weylus::stream_handler: Error sending video: An established connection was aborted by the software in your host machine. (os error 10053)
[libx264 @ 00000258EFC733C0] frame I:14    Avg QP:20.36  size:111281
[libx264 @ 00000258EFC733C0] frame P:152   Avg QP:22.90  size:  8578
[libx264 @ 00000258EFC733C0] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 00000258EFC733C0] mb P  I16..4:  5.8%  0.0%  0.0%  P16..4:  3.6%  0.0%  0.0%  0.0%  0.0%    skip:90.6%
[libx264 @ 00000258EFC733C0] coded y,uvDC,uvAC intra: 22.2% 17.3% 12.9% inter: 1.4% 1.5% 0.9%
[libx264 @ 00000258EFC733C0] i16 v,h,dc,p: 45% 38% 13%  5%
[libx264 @ 00000258EFC733C0] i8c dc,h,v,p: 73% 18%  8%  2%
[libx264 @ 00000258EFC733C0] kb/s:137913776.00
```

So my first impressions:
-Mouse capturing works
-There's some lag (750 ms more or less)
-It looks like every click causes a right and left click simultaneously

However, when streaming to my `iPad Air` with `iOS 10.3.3` and `Firefox Version 14.0 (12646)` the client remains with a blue-ish screen. Here's the ouput:
```
[2mJun 15 19:44:31.234[0m [32m INFO[0m weylus::web: Webserver listening at 0.0.0.0:1701...
[2mJun 15 19:44:33.954[0m [32m INFO[0m weylus::web: Client connected: 192.168.0.131:53278
```

**Comment by H-M-H** [comment]
> Now this is weird... Your debug version works out of the box

I already suspected what was going wrong and sneaked a fix into the debug build :)

You can try a release build here: https://github.com/H-M-H/Weylus/suites/800226395/artifacts/8623856 it should be considerably faster.

> It looks like every click causes a right and left click simultaneously

That is probably a bug in the library I use to generate mouse clicks or for some reason your browsers is sending right and left click simultaneously, to check if this is the case you can run Weylus like this: `WEYLUS_LOG_LEVEL=TRACE weylus.exe`. This will printout all events sent from the browser, if you see anything different than 0 or 1 for `button` or `buttons` the browser is at fault.

> However, when streaming to my iPad Air with iOS 10.3.3 and Firefox Version 14.0 (12646) the client remains with a blue-ish screen.

Does reloading the page help?

One more thing: Do you get colored output in your console or do you see those neat � characters? I should probably disable colored output on windows if it is not actually colored.

**Comment by seffplusplus** [comment]
> , to check if this is the case you can run Weylus like this: WEYLUS_LOG_LEVEL=TRACE weylus.exe

Did you mean `.\weylus.exe WEYLUS_LOG_LEVEL=TRACE` ? Output remains the same.... Otherwise Powershell/CMD throws a CommandNotFound error. Notice that I'm using your release build. It's faster indeed :)

> Does reloading the page help?

Not at all. This only happens in my iPad. Android phone and localhost work OK.

Is Stylus Support in your plans? That would be a deal breaker. Nice work

**Comment by seffplusplus** [comment]
I realize your utility uses `PointerEvents`. According to [this](https://github.com/facebook/react/issues/12901#issuecomment-392180459) such functionality is not part of Apple's WebToolKit for my iPad version. Could that explain the lack of streaming? I should be able to see the stream at least I guess?

**Comment by H-M-H** [comment]
> Did you mean .\weylus.exe WEYLUS_LOG_LEVEL=TRACE ?

Ha, right your are on windows and you set environment variables differently there, try:
```
set WEYLUS_LOG_LEVEL="TRACE"
.\weylus.exe
```

> Is Stylus Support in your plans? That would be a huge add-on.

I do not run windows myself, so it is hard to test this and I do not plan to add support myself. But I will open another issue with instructions how one would go about it, so maybe someone else can pickup the work.

> not part of Apple's WebToolKit for my iPad version

The stream should be visible as the lack of PointerEvents can only crash processing those but not the video stream. However, maybe some other feature regarding video streaming is not supported on your iPad version. The code is straight forward, if you want to have a look here it is: https://github.com/H-M-H/Weylus/blob/a0e14cb3931f3ffd4ed08607097410a37f6b57cc/ts/lib.ts . The issue you linked proposes to use some polyfill library but if possible I would like to avoid adding any javascript dependencies. Additionally some logs from the browser would be very useful but I have no clue how remote debugging works on iOS.

**Comment by seffplusplus** [comment]
> But I will open another issue with instructions how one would go about it, so maybe someone else can pickup the work.

That would be awesome.

> but I have no clue how remote debugging works on iOS.

I'll try to report back on a few days

**Comment by H-M-H** [comment]
> I'll try to report back on a few days

Alright thanks for your help :)

**Comment by H-M-H** [comment]
Closing this as the original issue has been solved.
