### ISSUE TITLE
Set the wmclass

### ISSUE THREAD

**Issue by linsui** [H-M-H/Weylus#160]
It uses FLTK as the wmclass so that Gnome can't attach the window with the weylus icon. Thanks!

**Comment by H-M-H** [comment]
Good catch, how does icon matching work with the wmclass, is setting it to "weylus" going to be sufficient?

**Comment by H-M-H** [comment]
Ok done, you can try the latest build here: https://github.com/H-M-H/Weylus/actions/runs/2385800840#artifacts

**Comment by linsui** [comment]
It works well. Thanks!
