### ISSUE TITLE
Mirrored Screen on Android instantly freezes up & causes some other network issues on host?

### ISSUE THREAD

**Issue by awakenedCrowl** [H-M-H/Weylus#163]
Information about my Host System:
Ubuntu [Budgie]
AMD® Ryzen 7 pro 5850u with radeon graphics × 16

Information about my Tablet:
Samsung Galaxy S7 Tab

I have followed the Github's installation process tightly (including configuration of the firewall), and nowhere along the way was I presented with any errors or anything seemingly failing. When I start the connection (within my LAN) with the default settings and try to connect to it with my Tablet (tested both Chrome and Opera), the screen shows up, it works for approximately 1-5 seconds, and then the screen on the tablet freezes up (not the entire tablet, just the mirrored screen on the Browser tab). Weylus shows no error message in it's log, not before and not afterwards, only the usual information regarding the connection, just what you'd expect. After that freeze up happened, I also cannot connect again (it can't reach the host) until I completely reconnect to my Wi-Fi. Which seemingly randomly also sometimes decides to no longer connect to ANYTHING, after the freeze-up of the initial connection, a state which also then persists until I disconnect and reconnect to my Wi-Fi.

Since the log really doesn't give me anything out of the ordinary, not in the Weylus GUI or in the terminal (I hope you believe me, so I won't bother to start another failing connection again and include it for now), I really have no idea what could be the problem here. Normal VNC connections work just fine. Hope someone reading this has a clue what to try, what to search for? 
Cuz this application would really benefit me :)

Oh, also: Yes, both devices are on the exact same network, connected to the same SSID.
Also just checked, ufw is inactive. So I guess that means that it doesn't do anything - if it's off, all ports are unprotected by default, and not all blocked by default? Don't have much experience with it.

Another update: Nevermind, other VNC does apparently have the same problem. Other VNC worked perfectly last time, but now it gives the same issue as Weylus. If you have a clue how to help me regardless, I'd be very grateful.

Thanks in advance

**Comment by H-M-H** [comment]
This indeed sounds hard to believe :) Considering that the VNC you've tested produces the same behavior I think this problem is unrelated to Weylus.

To verify that the issue is indeed related to your WIFI you could try connecting to Weylus via USB with adb as described in the FAQ.

**Comment by awakenedCrowl** [comment]
Yeah, I'll try that (tomorrow probably). Since this obviously seems to be no Weylus related issue, feel free to close it. Should something else arise that DOES indeed relate to Weylus, I'll make another, more organized issue.

Thank you anyway :)

**Comment by H-M-H** [comment]
Alright, good luck!
