### ISSUE TITLE
New Builds

### ISSUE THREAD

**Issue by Papermanzero** [H-M-H/Weylus#171]
Is it possible to get new builds for windows, linux and mac? The latest one is more than one year old and meanwhile there are a lot of features like extended screen for windows which would be pretty cool

**Comment by H-M-H** [comment]
Sure! You can have a look at the commit history and for every commit with a green check you can click on it, then open the Details page and there click at summary. This will open a page where you can download build artifacts.

The builds for the latest master can be found here: https://github.com/H-M-H/Weylus/actions/runs/2786467129#artifacts

The latest build with extra features for windows can be found here: https://github.com/H-M-H/Weylus/actions/runs/2790123039#artifacts
