### ISSUE TITLE
Disabling "Enable Touch" makes it so that the pen doesn't click

### ISSUE THREAD

**Issue by MicaelJarniac** [H-M-H/Weylus#176]
Device: ONYX BOOX Note Air (Android 10)
Browser: Firefox
<details>
<summary>Host</summary>

```
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.19.0-1-rt10-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × AMD Ryzen 3 2200G with Radeon Vega Graphics
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 970/PCIe/SSE2
```
</details>

I tried disabling "Enable Touch" to rest my palm on the screen safely and noticed that I could no longer click with the pen. The cursor would only hover but not click. And the cursor will not follow the pen if I move it while it touches the screen, staying still on the first point of contact.

**Comment by H-M-H** [comment]
Sadly the distinction between pen and touch event is still not implemented on Firefox for Android. I have opened an [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1702482) for that last year, see these comments for more context: https://github.com/H-M-H/Weylus/issues/66#issuecomment-799006598

**Comment by MicaelJarniac** [comment]
I saw those issues yesterday, but I didn't realize this was also related to that. Will close this issue here then since it isn't something that can be fixed on this end.
