### ISSUE TITLE
Ignore touch input

### ISSUE THREAD

**Issue by binomial0** [H-M-H/Weylus#18]
Drawing on my tablet would be way easier if I could rest my hand on the screen and the app ignored the touch events. Several drawing apps for android support this more or less (I still have to watch out not to touch system UI elements). I think Weylus could also support this by filtering on event type, and having a setting to ignore touch events either on the Rust (probably easier) or on the TypeScript (transmits less unnecessary data) side.

**Comment by H-M-H** [comment]
Thanks for the report, actually I already implemented this. You can try a binary form the artifacts generated here https://github.com/H-M-H/Weylus/runs/785354301
