### ISSUE TITLE
Ubuntu 20.04 - cannot start Weylus

### ISSUE THREAD

**Issue by m-beau** [H-M-H/Weylus#221]
Hey there,

upon launching the GUI, the following error message appears:
WARN Failed to read configuration file: No such file or directory (os error 2)

and upon hitting the 'start' button, the following appears:
ERROR Failed to start websocket server: Failed binding to socket: Address already in use (os error 98)

any suggestion? I simply downloaded the executables from the last build, made them executable by running sudo chmod -x ./weylus, then run the app with './weylus'. Thanks for your help.

**Comment by MurilloDaniel** [comment]
WARN Failed to read configuration file: No such file or directory (os error 2) I had the same thing and can't start it too, did you fixed it?

**Comment by TrickBit** [comment]
Seems to do that the first run - change settings to suit, close the app and re-open again and this message is gone (on Ubuntu 22.04 anyway)

**Comment by beroal** [comment]
> and upon hitting the 'start' button, the following appears: ERROR Failed to start websocket server: Failed binding to socket: Address already in use (os error 98)

The TCP port 9001 is commonly used by the Tor daemon. Check whether you run it.

**Comment by H-M-H** [comment]
> ERROR Failed to start websocket server: Failed binding to socket: Address already in use (os error 98)

Try changing the ports in the gui. Some program is already using the standard ports of weylus.
