### ISSUE TITLE
WARN Failed to read configuration file: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by MurilloDaniel** [H-M-H/Weylus#223]
I received this warning in Linux Mint: even after doing like in the git hub instruction. WARN Failed to read configuration file: No such file or directory (os error 2)

**Comment by MurilloDaniel** [comment]
Ok now the error is gone but it doesn't matter cuz I can't connect at all, after I click star and click the QR Code, the page never loads.

**Comment by MurilloDaniel** [comment]
Ok now the error is gone but it doesn't matter cuz I can't connect at all, after I click star and click the QR Code, the page never loads.

**Comment by H-M-H** [comment]
Thanks for the report, if have fixed the original issue about the config warning!

If the page never loads this is most likely a network problem unrelated to Weylus. Can you open the page on the computer that Weylus is running on?

If this is not a network problem, feel free to describe what else you have tried and I will reopen this issue if needed.
