### ISSUE TITLE
Passive stylus not recognized

### ISSUE THREAD

**Issue by marbetschar** [H-M-H/Weylus#225]
Hi there :wave: ,

I'm currently evaluating Weylus in my quest for find a way to put my [ONYX Boox Note Air](https://onyxboox.com/boox_noteair) to use as an external, Android based graphic tablet to be used with a Linux note taking app such as [rnote](https://flathub.org/apps/com.github.flxzt.rnote).

Although connecting and basic navigation works (even multi-touch gestures which is pretty awesome!), Weylus does not seem to be able to distinguish between touch and stylus inputs: Whenever I move the stylus, it moves the paper (tested in rnote and Xournal++ as well) - which is basically the same action as when I use my fingers.

My assumption is, this is due to the passive nature of the stylus of the ONYX Boox Note Air: Its completely passive and therefore I assume that Weylus somehow is unable to tell whether its a finger or a stylus currently interacting with the ONYX Boox Note Air. Is this assumption correct?

If so, is there a way to tell Weylus to always forward "single-touch" events as stylus events? So we could still use multi-touch for zooming/scrolling - but the stylus for drawing?

**Comment by xqft** [comment]
Same issue here with an S-Pen and Tab S6

**Comment by gabmert** [comment]
Have you tested different browsers? See #178

**Comment by marbetschar** [comment]
Interesting, thanks for the heads up @gabmert. I did actually test Weylus in Firefox and wasn't aware that this is a known issue. I will give this a retest then and close the issue for now.

 Meanwhile, I also came across https://github.com/leath-dub/vboox - which works perfectly well via adb :smile:
