### ISSUE TITLE
Build error (Ubuntu 18.04.4 LTS)

### ISSUE THREAD

**Issue by taupalosaurus** [H-M-H/Weylus#23]
Hi,

Apologies if this is not the preferred way to get help for this kind of problem. I am unable to build Weylus on my fairly standard Ubuntu 18 LTS box, due to the following error:

```
The following warnings were emitted during compilation:

warning: tsc failed with exitcode: 2

error: failed to run custom build command for `weylus v0.8.0 (/home/$USER/build/weylus)`

Caused by:
  process didn't exit successfully: `/home/$USER/build/weylus/target/debug/build/weylus-b728f48f484f9563/build-script-build` (exit code: 2)
--- stdout
cargo:rerun-if-changed=ts/lib.ts
tsconfig.json(3,15): error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'esnext'.
tsconfig.json(4,13): error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'esnext', 'dom', 'dom.iterable', 'webworker', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'esnext.array', 'esnext.asynciterable', 'esnext.promise'.
ts/lib.ts(26,64): error TS2339: Property 'forEach' does not exist on type 'NodeListOf<Element>'.
ts/lib.ts(87,35): error TS2495: Type 'IterableIterator<[string, HTMLInputElement]>' is not an array type or a string type.
ts/lib.ts(99,39): error TS2495: Type 'IterableIterator<[string, HTMLInputElement]>' is not an array type or a string type.
ts/lib.ts(190,28): error TS2339: Property 'twist' does not exist on type 'PointerEvent'.
ts/lib.ts(210,31): error TS2339: Property 'includes' does not exist on type 'string[]'.
ts/lib.ts(260,42): error TS2339: Property 'onerror' does not exist on type 'SourceBuffer'.
ts/lib.ts(261,42): error TS2339: Property 'onerror' does not exist on type 'SourceBuffer'.
cargo:warning=tsc failed with exitcode: 2

warning: build failed, waiting for other jobs to finish...
error: build failed
```

I have previously installed all the dependencies mentioned in the readme file, but I'm not familiar enough with this buil pipeline to understand what is going on. Can you please advise on how to fix this ?

Thanks

**Comment by H-M-H** [comment]
It looks like your version of `tsc` is a bit dated. You have three options:
- edit the file `tsconfig.json` and replace each occurrence of 2020 with 2018 and hope it works
- update `tsc`
- use the provided docker image to build Weylus

**Comment by taupalosaurus** [comment]
Thanks. For further reference, it worked well by installing by hand the `node-typescript (3.6.3-1)` package for Ubuntu eoan.

Now that the build is complete, I tried the system, and it is very laggy. Could it be due to the fact that the default target is the debug one ? Can I build in release mode ?

**Comment by H-M-H** [comment]
> Now that the build is complete, I tried the system, and it is very laggy. Could it be due to the fact that the default target is the debug one ? Can I build in release mode ?

Yes, I just updated the readme. To build in release mode run `cargo build --release`.

If you feel adventurous you can also try the nvenc branch: https://github.com/H-M-H/Weylus/tree/nvenc which adds hardware encoding to speed things up. You will need to remove the folder deps/dist to recompile ffmpeg with support for hardware acceleration though.
