### ISSUE TITLE
Weylus 0.11.4 does not connect

### ISSUE THREAD

**Issue by Liniaxx** [H-M-H/Weylus#234]
I used to use Weylus to help with my animation, but since I moved it's now doing nothing.
I've checked everything I could, the IPv4, the WiFi, my iPadOS, the browser version, everything, and it just hasn't worked since I moved. We're connected to the same WiFi, and both Chrome and my iPad are up to date. Even my browser on my computer didn't detect Weylus.
It worked before, and now it doesn't, and there looks like there's literally no fix. Could I get some help?? I need this for my animation practice and stuff, as my touchscreen isn't the best with my software, and I draw better with a pen anyways. ;-;

**Comment by tutacat** [comment]
Check your IP address, open settings > network > connection, and look for the IP address (not the gateway), as it likely changed the IP on a new network.

Also check you are using the same port you set in the program.

A way to test the program is working, on the computer, is using 127.0.0.1:1701, which is the loopback address, so it will only connect to itself.

**Comment by SolAZDev** [comment]
@tutacat  is that why the internet can stop working for the host device? For me once its connected all traffic stops

**Comment by H-M-H** [comment]
> Even my browser on my computer didn't detect Weylus.

Have you tried connecting to http://127.0.0.1:1701 as suggested?

As this seems to be a network issue unrelated to weylus I am closing this for now.
