### ISSUE TITLE
Ip Stream not loading

### ISSUE THREAD

**Issue by alienlethargy** [H-M-H/Weylus#235]
I am trying to use my iPad to connect with my windows computer. When I use my the link that is provided by Weylus on the iPad, I get some variation of a nonloading screen/error. The link works when used on a computer though.

**Comment by tutacat** [comment]
Check what the log says at the bottom of the settings pane on the page, as well as the log in the program. If it says unable to connect, it is probably a connection issue for the ipad's network (wrong wifi or IP). For example, your IP is not 0.0.0.0, it's your local IP (see netstat output in cmd).
If it is just a blank screen with a video error, then it may be an unsupported encoding or unsupported javascript on the ipad browser.

**Comment by alienlethargy** [comment]
> 

Thank you for your answer. 

I actually can not get that far because it is just a "this site cannot be reached" error on my iPad browser anytime I try to load it. I have tested that it works on my computer browser though.

**Comment by H-M-H** [comment]
This sounds like a network problem unrelated to Weylus. Make sure your iPad can connect to you computer.
