### ISSUE TITLE
Wayland stream goes black after client size changes

### ISSUE THREAD

**Issue by matejdro** [H-M-H/Weylus#242]
1. Start Weylus on Sway (Wayland)
2. Open Weylus webpage on any mobile device
3. Stream will work normally
4. Change size of the webpage (for example, toggle fullscreen or rotate the device)

Stream will become black with `Error capturing screen: No buffer available!` error appearing in Weylus.

This is with 6411ba45260859f6ba44eb56ba86af4d5227eab3 build

**Comment by H-M-H** [comment]
Thanks for the report! Please try the latest build: https://github.com/H-M-H/Weylus/actions/runs/11402145420#artifacts

I will reopen this issue, if the problem persist.
