### ISSUE TITLE
[Feature Request] Choose Screen to Stream

### ISSUE THREAD

**Issue by JhowUno** [H-M-H/Weylus#248]
I have 3 monitors, but I can't choose which one I want to stream, many other people may have the same problem, I guess. And I have problems to scroll, some thin scrolls bar are impossible to click, maybe gestures can be implemented to scroll and zoom. Thanks.

**Comment by mzen17** [comment]
I believe this feature is already there.
![image](https://github.com/H-M-H/Weylus/assets/92705460/209ed157-5f18-42b6-9068-2c3e1b9f56e7)

As for the scroll, if you are on Linux, then it depends on the applicaiton. Some (e.g Firefox), requires additional configuration (e.g, MOZ_USE_XINPUT2=1).

If you are on Windows or Mac, it doesn't seem that gestures are supported, unfortunately.
