### ISSUE TITLE
Having issues getting uinput to work on tablet running pmOS

### ISSUE THREAD

**Issue by JetpackJackson** [H-M-H/Weylus#252]
I installed `weylus-bin` from the AUR on my laptop and followed the instructions for creating the `60-weylus.rules` file for both devices but I still get pop ups about how it failed to create a uinput device. Do I need to install Weylus on the tablet as well? Thanks in advance, and please let me know if I need to provide more information.

**Comment by OSsqirat** [comment]
install it tablet ? what are you talking about? here is a vid explains how it's done: 

https://www.youtube.com/watch?v=3uN-yzZK5-M

**Comment by JetpackJackson** [comment]
What I mean is that the tablet gets the "failed to create uinput device" when I connect it to my laptop using the website even though I followed the instructions to set up the computer to do uinput, and I did it on the tablet as well to figure out why it kept popping up. I'll watch the video in a bit.

**Comment by JetpackJackson** [comment]
It works on my phone but not on my tablet. Strange. I'll keep debugging.

**Comment by JetpackJackson** [comment]
Ok I'm ashamed to say the tablet issue could have been on my end, I thought of a few things it could be. However on my phone I can't see my computer screen, it errors with `failed to init screencast`. How should I fix this? I'm running swaywm on Wayland.

**Comment by JetpackJackson** [comment]
Ok on my other computer I don't get that error, however screen casting only works for some pages. I can choose my web browser, weylus app screen, and desktop, however I do not see my notes app, and when I choose desktop (not autopilot) it shows a black screen.

**Comment by JetpackJackson** [comment]
I'm going to close this and open up a new issue for my phone. I think my tab is a lost cause, the screen started glitching out badly when running the webpage. Thank you for your help.
