### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by falhumai96** [H-M-H/Weylus#255]
Hello,

I just want to say this is a great project for allowing me to use a pen-supported device as a drawing tablet for my pc/laptop.

However, I'd like to learn more about the status of this project if it is still maintained or not.

**Comment by H-M-H** [comment]
At the moment I sadly do not have the time to maintain Weylus properly. I might pick it up next year again. But in the mean time everyone is free to fork it.

**Comment by SolAZDev** [comment]
Hello! @H-M-H Sorry to bother, but technically is "next year" albeit not a year from your post. I was wondering if you had considered looking for maintainers, or make it an association where others can contribute and maintain the project?

**Comment by electronstudio** [comment]
I have posted a friendly fork at https://github.com/electronstudio/WeylusCommunityEdition/ for the purpose of collecting all the PRs and building up to date binaries.  No plans to diverge it from the original.

**Comment by H-M-H** [comment]
> Hello! @H-M-H Sorry to bother, but technically is "next year" albeit not a year from your post. I was wondering if you had considered looking for maintainers, or make it an association where others can contribute and maintain the project?

Thanks for the suggestion, I have some time now and indeed decided to look for contributors. For now I will work a little on Weylus myself but for the long term I am looking for other contributors. Especially those who can test on Windows or macOS (I am only using Linux myself). See #287.
