### ISSUE TITLE
Keyboard not working on both Ipad and Android Phone

### ISSUE THREAD

**Issue by KooriKitsune38** [H-M-H/Weylus#256]
I've downloaded the latest release [v.0.11.4](https://github.com/H-M-H/Weylus/releases/tag/v0.11.4), and it seems like the bluetooth keyboard (linked to my ipad/android phone) isn't registering any input.

I tried Safari and Firefox, doesn't change.

So I then downloaded the [v0.11.2](https://github.com/H-M-H/Weylus/releases/tag/v0.11.2) and it apparently is now registering the keyboard and seems to be doing alright.

I also tried [v0.11.3](https://github.com/H-M-H/Weylus/releases/tag/v0.11.3) but it crashes after a few seconds after starting the server... haven't looked much into it, could be a problem with my computer being a mess... not sure...

I would help but my knowledge in programming is close to 0, so this post is mostly to let you know that the previous version apparently registers input while the newest doesn't.

Haven't tried connecting from another pc.

If I can be of any help, I will try my best.

## Hardware:
- Keyboard: [https://www.logitech.com/en-us/products/keyboards/k380-multi-device.920-009600.html](Logitech K380)
- Ipad: Ipad Pro 11' (IOS 17)
- Android Phone: Motorola Edge 30 (Android 13)

**Comment by LautaroRobles** [comment]
Can confirm the same happens with Samsung Tab S8+ keyboard case: 
Keyboard input not working on v0.11.4 but is working on v0.11.2.

**Comment by H-M-H** [comment]
Please try the latest build from master: https://github.com/H-M-H/Weylus/actions/runs/11074571109

**Comment by greencardigan** [comment]
v0.11.4 on Linux Mint.  I was unable to get keyboard input working on two different windows11 laptops using Edge and Chrome. I switched to Firefox and it's working.
