### ISSUE TITLE
would it work with remarkable tablet?

### ISSUE THREAD

**Issue by mihai-satmarean** [H-M-H/Weylus#257]
Hi, great initiative here!,
would it work with remarkable tablet?
Cheers

**Comment by gabmert** [comment]
so far my research says that the remarkable 2 doesn't have a browser - then the answer is no. Maybe you can find something that works for you on this site https://github.com/reHackable/awesome-reMarkable#screen-sharingstreaming

**Comment by H-M-H** [comment]
This is correct. Weylus requires that the input device, in your case the remarkable tablet, has a modern browser. As far as I am aware the remarkable tablet has no browser, so Weylus won't work.
