### ISSUE TITLE
not working in blender

### ISSUE THREAD

**Issue by Yourgrandpa88** [H-M-H/Weylus#262]
i want to draw on blender with my ipad but i am unable to do so .It only draws a dot whenever i drag the pencil on my screen .

**Comment by H-M-H** [comment]
Thanks for the report! Please provide more details, which OS is running on your computer? Have you enabled uinput? Also, please try the latest build from here: https://github.com/H-M-H/Weylus/actions/runs/11402145420#artifacts

If the problem persists, report back and I will reopen this issue.
