### ISSUE TITLE
Desktop is black screen (Ubuntu)

### ISSUE THREAD

**Issue by WolfyRed** [H-M-H/Weylus#265]
Hello. When I turn on the server, and join the URL it provides, I'd expect to see the Desktop on the client. But rather, when I go to Desktop on the browser client, it is a black screen. Interestingly, when I go to any other window that isn't Desktop, that specific window shows up. The full Desktop never shows up on browser client, only most windows.

Version = Weylus 0.11.4
OS = Ubuntu 22.04.4 LTS (64-Bit)
RAM = 7310 MB
CPU = AMD Ryzen 5 4500U with Radeon G

**Comment by H-M-H** [comment]
Thanks for the report! Try enabling support for Wayland in the gui or switch back to X11. Weylus unfortunately does not fully support Wayland yet, see #3 for details.
