### ISSUE TITLE
Error building from AUR (rust error)

### ISSUE THREAD

**Issue by TheDogHusky** [H-M-H/Weylus#267]
Hey!

I'm on arch linux and tried installing Weylus through Yay.
I simply entered `yay -S weylus`.

It built, then errored:
![image](https://github.com/H-M-H/Weylus/assets/74465875/93a9c64e-4284-4c96-ba09-9ed17eeeb380)

Could you fix that?

**Comment by TheDogHusky** [comment]
I installed through Yay with the weylus-bin package instead of weylus.
It would be great still to fix the issue.

**Comment by H-M-H** [comment]
Should be fixed now!
