### ISSUE TITLE
FR: Dark mode

### ISSUE THREAD

**Issue by Zahrun** [H-M-H/Weylus#277]
Support a dark mode for the desktop window content

**Comment by bbb651** [comment]
I've started working on porting the GUI to iced

![image](https://github.com/user-attachments/assets/72a2411c-86e7-4be4-9459-a2099c103b85)

I don't think the maintainer is active but hopefully it can be merged in https://github.com/electronstudio/WeylusCommunityEdition

**Comment by H-M-H** [comment]
Thanks for the suggestion, theme selection has been implemented in https://github.com/H-M-H/Weylus/commit/cb5f360ea3511b2f6e17aedd95e962217d430549.

**Comment by bbb651** [comment]
Nice to see the project still being active :)
I'm almost done with my iced rewrite, are you interested in merging it? I've had a look at the `fltk-theme ` and imo iced still feels nicer (in terms of code it's a bit more concise, ~100 lines less or ~100 lines more if you include theme type boilerplate to convert it and make it serializable for the config)

**Comment by H-M-H** [comment]
I have chosen FLTK because it is lightweight and stable, so far it has done its job very well. While iced may look nicer it is still experimental software and feels a little overkill for the simple GUI of Weylus :). For these reasons I prefer to stick with FLTK.
