### ISSUE TITLE
i cant screen mirror

### ISSUE THREAD

**Issue by Toibidien191** [H-M-H/Weylus#281]
click does register but my screen dont

**Comment by H-M-H** [comment]
Please provide more details! What's your OS, have you tried running `WEYLUS_LOG_LEVEL=TRACE weylus`, what does it output? What else have you tried?

Once more details are provided I will reopen this issue if needed.

**Comment by Toibidien191** [comment]
> Please provide more details! What's your OS, have you tried running `WEYLUS_LOG_LEVEL=TRACE weylus`, what does it output? What else have you tried?
> 
> Once more details are provided I will reopen this issue if needed.

i use iphone 7 plus ios 15.8.1

**Comment by H-M-H** [comment]
Unfortunately iOS is not supported. Only iPadOS will work with Weylus. iOS with version below 17 does not support low latency streaming. Apparently this has changed with iOS 17, but I need to do some further research first.
