### ISSUE TITLE
Link never opens on Android or Ipad

### ISSUE THREAD

**Issue by MurilloDaniel** [H-M-H/Weylus#283]
Once I open Weylus and type the link on my Android phone and Ipad the page never opens, on my Ipad it simply says that it could not connect to the server while on Android it says Address unreacheable.

ps.: I'm on Linux, Nobara

**Comment by Diordany** [comment]
Can you post the output from Weylus after your attempts to connect?

For example (my case):
```
INFO Webserver listening at 127.0.0.1:1701...
INFO Client connected. address=127.0.0.1:53571
INFO WS-Client authenticated! address=127.0.0.1:53571
INFO using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
INFO profile Constrained Baseline, level 6.2, 4:2:0, 8-bit
INFO 264 - core 164 r3108 31e19f9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=8 lookahead_threads=8 sliced_threads=1 slices=8 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=12 keyint_min=1 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
INFO Video: 3602x1156@libx264 pix_fmt: yuv420p
```

And what link you're using to connect.

**Comment by MurilloDaniel** [comment]
> Can you post the output from Weylus after your attempts to connect?
> 
> For example (my case):
> 
> ```
> INFO Webserver listening at 127.0.0.1:1701...
> INFO Client connected. address=127.0.0.1:53571
> INFO WS-Client authenticated! address=127.0.0.1:53571
> INFO using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
> INFO profile Constrained Baseline, level 6.2, 4:2:0, 8-bit
> INFO 264 - core 164 r3108 31e19f9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=8 lookahead_threads=8 sliced_threads=1 slices=8 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=12 keyint_min=1 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
> INFO Video: 3602x1156@libx264 pix_fmt: yuv420p
> ```
> 
> And what link you're using to connect.

That's the thing, there is none, Weylus give no output (It just say this: "INFO Webserver listening at 0.0.0.0:1701..."). The link I'm using is the one that shows in the "Connect your tablet to" box

**Comment by Diordany** [comment]
> The link I'm using is the one that shows in the "Connect your tablet to" box

What link does the box show?

**Comment by MurilloDaniel** [comment]
> > The link I'm using is the one that shows in the "Connect your tablet to" box
> 
> What link does the box show?

I'm not telling you that man. It's fine if you can't help but I'm not giving you the link that directly shows my screen.

**Comment by electronstudio** [comment]
Unless your machine has a public IP address and no firewall - a configuration that I've never seen the days of Trumpet Winsock - that link will not allow anyone to connect to your machine over the internet.  If you are worried, enter something in the "access code" box.

**Comment by MurilloDaniel** [comment]
> Unless your machine has a public IP address and no firewall - a configuration that I've not seen the days of Trumpet Winsock - that link will not allow anyone to connect to your machine over the internet. If you are worried, enter something in the "access code" box.

ok, why did you closed the issue before I could give the link then?

ps.: It's http://192.168.0.114:1701 btw

**Comment by Diordany** [comment]
> ps.: It's http://192.168.0.114:1701 btw

Probably a valid LAN ip. Can you put `192.168.0.114` into the `Bind Address` field instead of `0.0.0.0`, restart Weylus and try to connect again from your tablet?

**Comment by electronstudio** [comment]
> ok, why did you closed the issue before I could give the link then?

Because there's no point have 2 issues discussing the same thing.

What happens if you open the link on the same machine you are running Weylus?

**Comment by Diordany** [comment]
> ok, why did you closed the issue before I could give the link then?

I think it's probably not even an issue with Weylus, let alone a WeylusCOmmunityEdition issue, which @electronstudio already pointed out in the other issue.

**Comment by MurilloDaniel** [comment]
> > ok, why did you closed the issue before I could give the link then?
> 
> Because there's no point have 2 issues discussing the same thing.
> 
> What happens if you open the link on the same machine you are running Weylus?

I tried that since I read in another issue and it worked, opening the localhost link showed my screen but neither my ipad or android did it.

Also Diordany, just tried what you asked and I got same error

**Comment by Diordany** [comment]
> Also Diordany, just tried what you asked and I got same error

Okay, thanks for trying. Can you also try @electronstudio's suggestion:

> What happens if you open the link on the same machine you are running Weylus?

**Comment by Diordany** [comment]
What happens if you open the link on the same machine you are running Weylus?

And on the same machine also try `http://127.0.0.1:1701/`.

**Comment by electronstudio** [comment]
Definitely network issue then.  Could be a firewall.  Post output of command ` sudo iptables -L `

**Comment by MurilloDaniel** [comment]
> > Also Diordany, just tried what you asked and I got same error
> 
> Okay, thanks for trying. Can you also try @electronstudio's suggestion:
> 
> > What happens if you open the link on the same machine you are running Weylus?

I mentioned in my last message, but basically the screen sharing worked if I open the page on the machine running Weylus. If the issue is a network would using a cable fix it? I dunno it if would work since I'm trying on my Ipad though

**Comment by MurilloDaniel** [comment]
> > What happens if you open the link on the same machine you are running Weylus?
> 
> And on the same machine also try `http://127.0.0.1:1701/`.

Didn't worked

**Comment by MurilloDaniel** [comment]
> Definitely network issue then. Could be a firewall. Post output of command `sudo iptables -L`

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by electronstudio** [comment]
There's no firewall on your machine causing it then.  There could be one on your wifi router blocking the connection.  You would need to check the router config.

Is your ipad on the same wifi network as your computer?  What is IP address of ipad?

Yes using a cable might fix it.

**Comment by MurilloDaniel** [comment]
> There's no firewall on your machine causing it then. There could be one on your wifi router blocking the connection. You would need to check the router config.
> 
> Is your ipad on the same wifi network as your computer? What is IP address of ipad?
> 
> Yes using a cable might fix it.

"Is your ipad on the same wifi network as your computer?" - Yes, no idea the Ipad IP adress though

What are the steps to use the cable? I plug in my pc and the Ipad but nothing changes.

**Comment by electronstudio** [comment]
For android you can set up networking over a USB cable with the `adb` command - see the end of the Weylus README for instructions.

For iPad I don't know.  You may have to get a USB->ethernet adapter.

I still think the most likely culprit is your wireless router has some setting that is blocking hosts from communicating with one another.  Public wifi networks are usually configured like this.

You can find the IP address of the iPad on the wifi settings screen, but that's only the first step to investigating network connectivity issues.

**Comment by MurilloDaniel** [comment]
> For android you can set up networking over a USB cable with the `adb` command - see the end of the Weylus README for instructions.
> 
> For iPad I don't know. You may have to get a USB->ethernet adapter.
> 
> I still think the most likely culprit is your wireless router has some setting that is blocking hosts from communicating with one another. Public wifi networks are usually configured like this.
> 
> You can find the IP address of the iPad on the wifi settings screen, but that's only the first step to investigating network connectivity issues.

The only info about Wifi I found is this "74:E1:B6:48:25:44", apart from that there is nothing else related to Wifi on settings.

**Comment by Diordany** [comment]
> For android you can set up networking over a USB cable with the `adb` command - see the end of the Weylus README for instructions.

- Enable USB debugging on your Android device.
- Set your bind address to either `127.0.0.1` or `0.0.0.0` for Weylus.
- Connect your Android tablet through USB.
- run `adb reverse tcp:1701 tcp:1701` and `adb reverse tcp:9001 tcp:9001`.
- Accept on your Android device.
- Connect to `http://127.0.0.1:1701` on your browser on the Android device.

That should be the gist of it.

**Comment by electronstudio** [comment]
![image](https://github.com/user-attachments/assets/379eb8cf-b717-4681-a1a0-8e430cd6717a)

**Comment by MurilloDaniel** [comment]
> ![image](https://private-user-images.githubusercontent.com/7192452/367407214-379eb8cf-b717-4681-a1a0-8e430cd6717a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTIxOTYsIm5iZiI6MTcyNjI1MTg5NiwicGF0aCI6Ii83MTkyNDUyLzM2NzQwNzIxNC0zNzllYjhjZi1iNzE3LTQ2ODEtYTFhMC04ZTQzMGNkNjcxN2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMTgyNDU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTRmYzM1YzUxZTU0MTY2MzEyZWFjYTg0MjI3MDJkM2MwMmRjYmNhOTQzYjQ0OTNiZDNkODc3YTJiZjMwYTRkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uM-WrQ6iMzoGodr8W1EOoVKoQvqmXwvvsTKGB48e6lY)

found it thanks, it's: 192.168.0.132

**Comment by Diordany** [comment]
> found it thanks, it's: 192.168.0.132

Is the subnet mask also `255.255.255.0` on your iPad?

**Comment by MurilloDaniel** [comment]
> > found it thanks, it's: 192.168.0.132
> 
> Is the subnet mask also `255.255.255.0` on your iPad?

yes

**Comment by Diordany** [comment]
> yes

Then at least we can confirm that they're on the same network.

**Comment by Diordany** [comment]
Maybe try `ping -c 1 192.168.0.132` on your PC? And post the output.

**Comment by MurilloDaniel** [comment]
> Maybe try `ping -c 1 192.168.0.132` on your PC? And post the output.

"PING 192.168.0.132 (192.168.0.132) 56(84) bytes of data."

**Comment by electronstudio** [comment]
Ping response doesn’t work on iOS unfortunately so you need to use other tools to diagnose. I would check the router configuration and then if there’s no setting there you can change perhaps find a subreddit that specialises in home network configuration and ask them to help.

**Comment by Diordany** [comment]
And I'd suggest you also close this issue, since it turned out not to be an issue with Weylus (you were able to connect from a browser on the same machine).

**Comment by H-M-H** [comment]
Closing as this is not an issue with Weylus itself. Thanks to everyone who's helped out!
