### ISSUE TITLE
Using Weylus to mirror my PC screen on my notebook through a cable?

### ISSUE THREAD

**Issue by MurilloDaniel** [H-M-H/Weylus#285]
It's possible to do that? I have the cable that I use to charge my phone and it does have the proper plug in option.

**Comment by H-M-H** [comment]
This may be possible but I am not entirely sure. You will have to do some research yourself. If you can get Ethernet/IP to work with your cable, it will work. Basically you need to connect your computer and notebook via the Internet Protocol.

If you have Ethernet ports on both devices this is easy, if you only have a USB cable, you may need an adapter.

As this is not an issue with Weylus but a support request I am closing this issue. If you get this to work, feel free to share what you did so others can benefit as well.
