### ISSUE TITLE
Can't capture screen with access code set

### ISSUE THREAD

**Issue by Diordany** [H-M-H/Weylus#286]
I tried to use Weylus with an access code, but this breaks with commit cd3d91f . After applying it, I'm unable to capture any screens/windows:

![image](https://github.com/user-attachments/assets/d5886f55-9813-446f-a8b0-e0c938a25d5d)

I tried it by connecting to:

- 127.0.0.1 on the same machine
- 127.0.0.1 on my Android tablet through ADB
- My LAN IP on the same machine
- My LAN IP from my Android tablet, connected to Wi-Fi

In all cases I used both Brave Browser and Firefox, with the same results.

**Comment by Diordany** [comment]
I also tried the refresh button.

**Comment by H-M-H** [comment]
Thanks for the report, fixed on master!

**Comment by Diordany** [comment]
I can also confirm that it works now, thanks!
