### ISSUE TITLE
Wayland not supported

### ISSUE THREAD

**Issue by victorliu-sq** [H-M-H/Weylus#294]
I just switched to Cosmic Desktop, which is based on wayland. And it turns out weylus for wayland does not work with it well since the error message "fail to init screen cast" show up all the time. Is there any way to fix this error to advance the weylus? Any suggestion on that will be appreciated!

**Comment by aalvarell** [comment]
Same here (Ubuntu 24.04). The video is just a black image. I can move and draw (using a tablet with a pen) but I don't see my Laptop display mirrored on the tablet.

**Comment by H-M-H** [comment]
@Iey4iej3 is correct, Wayland is only partially supported. Make sure you have enabled the checkbox for Wayland support or that you have started weylus with the `--wayland-support` flag. Also, feel free to try latest master: https://github.com/H-M-H/Weylus/actions/runs/11330368044#artifacts

Closing in favor of #3
