### ISSUE TITLE
TLS proxy and WebSocket

### ISSUE THREAD

**Issue by beroal** [H-M-H/Weylus#297]
Hi. I can't get Weylus to work through a TLS proxy. I understand that a TLS proxy wraps an HTTP connection on port 1701. Does a WebSocket connection (port 9001) need to be wrapped? If not, how the client (a webbrowser) is supposed to access the WebSocket if Weylus binds to 127.0.0.1 only?

**Comment by H-M-H** [comment]
If the proxy binds on 0.0.0.0 and proxies web and websocket to Weylus, which binds to 127.0.0.1, everything is fine. And yes, you are correct, the latest release requires that both ports 1701 and 9001 are proxied. You can also try the latest master which works with one port only.

See https://github.com/H-M-H/Weylus/blob/master/weylus_tls.sh (latest master) or https://github.com/H-M-H/Weylus/blob/c724afc92264b78e88e8f0fd2b92069cfce27804/weylus_tls.sh (v0.11.4) for a script that starts Weylus with a TLS proxy.

**Comment by beroal** [comment]
Now I understand. I installed Weylus from Arch Linux AUR, but used `weylus_tls.sh` from the Git repository which is for the different version of Weylus.
