### ISSUE TITLE
doesn't work for me, Ubuntu 18.04

### ISSUE THREAD

**Issue by ZoltanPalagyi** [H-M-H/Weylus#30]
Hi, I installed Weylus_0.8.0_amd64.deb. Actually, I did have the same issue as in https://github.com/H-M-H/Weylus/issues/24 which I could fix by opening port 1701 in ufw. Now I can connect to Weylus fom my tablet (tried Firefox, Opera, Chrome).  Nothing appears in the "capture window" box. (When I connect to Weylus from my computer, the "capture window" box offers a bunch of windows open in my computer, and lets me select a window.) Am I missing something obvious? Thanks for your help!

**Comment by H-M-H** [comment]
Did you also open the websocket port (9001 by default)?

**Comment by ZoltanPalagyi** [comment]
Now I did, thanks! The stylus only works in Gimp, but not in Xournal++ or Write.

**Comment by H-M-H** [comment]
Great! About Xournal++: I use it regularly and it works fine for me (version 1.0.18), maybe you need to tweak some settings from Xournal++ regarding inputs.

**Comment by jjlarkin** [comment]
Hi Thank you for making this really looking forward to using it 

I keep getting this error when starting weylus 

ERROR weylus::websocket: Failed binding to socket: Cannot assign requested address (os error 99)
thread '<unnamed>' panicked at 'error binding to 192.168.1.59:1701: error creating server listener: Cannot assign requested address (os error 99)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/server/mod.rs:124:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
