### ISSUE TITLE
Which build to use?

### ISSUE THREAD

**Issue by arcxne** [H-M-H/Weylus#312]
I would like to know which build to use for the latest features for my M1 Mac. The official release is 3 years old so it might not have the most features although it is stable for me. I tried a few from the "actions" (especially the most recent one) but they show a blank screen on my iPad and the cursor is not being controlled (WARN Could not move mouse: Out of bounds)

Edit: Build I tried (it's the latest one with a Tick): https://github.com/H-M-H/Weylus/actions/runs/11982101788

**Comment by H-M-H** [comment]
I do not have a Mac at the moment, but you can try the build from this PR https://github.com/H-M-H/Weylus/pull/289 which has been reported to work on macOS, hopefully also on their new processors.

**Comment by arcxne** [comment]
Still facing the same issue :/
Used this build: https://github.com/H-M-H/Weylus/actions/runs/11592909762

**Comment by arcxne** [comment]
I'll just stick with the community edition latest release for now, works on my iPad though it misses parts of my strokes
