### ISSUE TITLE
Screen mirroring not working in Chrome on iPad

### ISSUE THREAD

**Issue by rannbaron** [H-M-H/Weylus#35]
I can't see anything in the browser window when I connect. I can write, but the window is empty. I'm on Linux -- I initially thought it was a Wayland issue (I saw that open issue), but I logged into an Xorg session and it's the same. Help please! Happy to give any info needed.

**Comment by H-M-H** [comment]
You can check if this is a problem with your tablet by connecting to Weylus from your computer via localhost. Additionally you can enable debug logging by starting Weylus like this: `WEYLUS_LOG_LEVEL=TRACE weylus`. What kind of tablet do you use?

**Comment by rannbaron** [comment]
It worked fine from my computer! I'm using Chrome on an iPad. Here's my output from the trace:

$ WEYLUS_LOG_LEVEL=TRACE weylus 
Aug 13 17:20:41.920  INFO weylus::gui: http://192.168.101.7:1701?password=testpass
Aug 13 17:20:41.921  INFO weylus::web: Webserver listening at 192.168.101.7:1701...
Aug 13 17:21:00.159 TRACE hyper::proto::h1::conn: Conn::read_head
Aug 13 17:21:00.159 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy }
Aug 13 17:21:00.161 TRACE hyper::proto::h1::conn: Conn::read_head
Aug 13 17:21:00.161 DEBUG hyper::proto::h1::io: read 428 bytes
Aug 13 17:21:00.161 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 428])
Aug 13 17:21:00.161 TRACE hyper::proto::h1::role: Request.parse Complete(428)
Aug 13 17:21:00.161 DEBUG hyper::proto::h1::io: parsed 8 headers
Aug 13 17:21:00.161 DEBUG hyper::proto::h1::conn: incoming body is empty
Aug 13 17:21:00.161  INFO weylus::web: Client authenticated: 192.168.101.140:64431.
Aug 13 17:21:00.161  INFO weylus::web: Client connected: 192.168.101.140:64431
Aug 13 17:21:00.161 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2679)), req_method=Some(GET)
Aug 13 17:21:00.161 DEBUG hyper::proto::h1::io: flushed 2797 bytes
Aug 13 17:21:00.161 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Aug 13 17:21:00.386 TRACE hyper::proto::h1::conn: Conn::read_head
Aug 13 17:21:00.387 DEBUG hyper::proto::h1::io: read 362 bytes
Aug 13 17:21:00.387 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 362])
Aug 13 17:21:00.387 TRACE hyper::proto::h1::role: Request.parse Complete(362)
Aug 13 17:21:00.387 DEBUG hyper::proto::h1::io: parsed 7 headers
Aug 13 17:21:00.387 DEBUG hyper::proto::h1::conn: incoming body is empty
Aug 13 17:21:00.387 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2587)), req_method=Some(GET)
Aug 13 17:21:00.387 DEBUG hyper::proto::h1::io: flushed 2704 bytes
Aug 13 17:21:00.387 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Aug 13 17:21:00.410 TRACE hyper::proto::h1::conn: Conn::read_head
Aug 13 17:21:00.410 DEBUG hyper::proto::h1::io: read 344 bytes
Aug 13 17:21:00.410 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 344])
Aug 13 17:21:00.410 TRACE hyper::proto::h1::role: Request.parse Complete(344)
Aug 13 17:21:00.410 DEBUG hyper::proto::h1::io: parsed 7 headers
Aug 13 17:21:00.410 DEBUG hyper::proto::h1::conn: incoming body is empty
Aug 13 17:21:00.410 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(12603)), req_method=Some(GET)
Aug 13 17:21:00.410 DEBUG hyper::proto::h1::io: flushed 12728 bytes
Aug 13 17:21:00.410 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
[libx264 @ 0x7ff5b0001a40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7ff5b0001a40] profile Constrained Baseline, level 6.2, 4:2:0, 8-bit
[libx264 @ 0x7ff5b0001a40] 264 - core 159 r2999 296494a - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=12 keyint_min=1 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to '(null)':
    Stream #0:0: Video: h264, yuv420p, 2560x1440, q=2-31

**Comment by H-M-H** [comment]
Hmm, how old is your iPad and does Safari also fail? Currently the video is not scaled and the logs tell me that the video resolution is 2560x1440 which might be too much for older iPads (it does work fine for more recent ones though). Can you select a window in the capture menu, it might work like that already?

**Comment by rannbaron** [comment]
It works with Safari! Thank you! Any way I can help make it work on Chrome?

**Comment by H-M-H** [comment]
It looks like chrome can display the javascript console: https://blog.chromium.org/2019/03/debugging-websites-in-chrome-for-ios.html in a new tab `chrome://inspect`. If you can get a log from there that would probably be helpful.

Also you might be interested into adding Weylus to your home screen to enable fullscreen: https://github.com/H-M-H/Weylus#fullscreen

**Comment by rannbaron** [comment]
Oddly, I get nothing at all in that log. Other webpages do make stuff appear in the log. This is weird!

The fullscreen is awesome!

**Comment by H-M-H** [comment]
This is indeed rather weird, I guess I will add improved debugging capabilities to the browser side in the next release.

**Comment by rannbaron** [comment]
Let me know and I'll be happy to help then! Thank you for this wonderful program and your incredible responsiveness!

**Comment by H-M-H** [comment]
Thanks for your praise! I will probably have some time next weekend to get this done.

**Comment by DavidVentura** [comment]
I'm having the same issue but with chrome on android.

```
$ WEYLUS_LOG_LEVEL=TRACE ./weylus
Aug 27 10:44:19.236  INFO weylus::gui: Found more than one IP address for browsers to connect to,
Aug 27 10:44:19.236  INFO weylus::gui: other urls are:
Aug 27 10:44:19.236  INFO weylus::gui: http://192.168.122.1:1701
Aug 27 10:44:19.236  INFO weylus::gui: http://192.168.250.1:1701
Aug 27 10:44:19.236  INFO weylus::gui: http://172.17.0.1:1701
Aug 27 10:44:19.236  INFO weylus::web: Webserver listening at 0.0.0.0:1701...
Aug 27 10:44:27.668 TRACE hyper::proto::h1::conn: Conn::read_head
Aug 27 10:44:27.669 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy }
Aug 27 10:44:27.669 TRACE hyper::proto::h1::conn: Conn::read_head
Aug 27 10:44:27.669 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy }
Aug 27 10:44:27.838 TRACE hyper::proto::h1::conn: Conn::read_head
Aug 27 10:44:27.838 DEBUG hyper::proto::h1::io: read 482 bytes
Aug 27 10:44:27.838 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 482])
Aug 27 10:44:27.838 TRACE hyper::proto::h1::role: Request.parse Complete(482)
Aug 27 10:44:27.838 DEBUG hyper::proto::h1::io: parsed 8 headers
Aug 27 10:44:27.838 DEBUG hyper::proto::h1::conn: incoming body is empty
Aug 27 10:44:27.838  INFO weylus::web: Client connected: 192.168.2.133:53852
Aug 27 10:44:27.838 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2677)), req_method=Some(GET)
Aug 27 10:44:27.838 DEBUG hyper::proto::h1::io: flushed 2795 bytes
Aug 27 10:44:27.838 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Aug 27 10:44:27.903 TRACE hyper::proto::h1::conn: Conn::read_head
Aug 27 10:44:27.903 DEBUG hyper::proto::h1::io: read 392 bytes
Aug 27 10:44:27.903 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 392])
Aug 27 10:44:27.903 TRACE hyper::proto::h1::role: Request.parse Complete(392)
Aug 27 10:44:27.903 DEBUG hyper::proto::h1::io: parsed 8 headers
Aug 27 10:44:27.903 DEBUG hyper::proto::h1::conn: incoming body is empty
Aug 27 10:44:27.903 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2587)), req_method=Some(GET)
Aug 27 10:44:27.903 DEBUG hyper::proto::h1::io: flushed 2704 bytes
Aug 27 10:44:27.903 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Aug 27 10:44:27.904 TRACE hyper::proto::h1::conn: Conn::read_head
Aug 27 10:44:27.904 DEBUG hyper::proto::h1::io: read 374 bytes
Aug 27 10:44:27.904 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 374])
Aug 27 10:44:27.904 TRACE hyper::proto::h1::role: Request.parse Complete(374)
Aug 27 10:44:27.904 DEBUG hyper::proto::h1::io: parsed 8 headers
Aug 27 10:44:27.904 DEBUG hyper::proto::h1::conn: incoming body is empty
Aug 27 10:44:27.904 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(12618)), req_method=Some(GET)
Aug 27 10:44:27.904 DEBUG hyper::proto::h1::io: flushed 12743 bytes
Aug 27 10:44:27.904 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
[libx264 @ 0x7f9269503e40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7f9269503e40] profile Constrained Baseline, level 6.0, 4:2:0, 8-bit
[libx264 @ 0x7f9269503e40] 264 - core 160 r3011 cde9a93 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=6 lookahead_threads=6 sliced_threads=1 slices=6 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=12 keyint_min=1 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to '(null)':
    Stream #0:0: Video: h264, yuv420p, 808x686, q=2-31
[libx264 @ 0x7f9268001a40] frame I:57    Avg QP:17.42  size:886122
[libx264 @ 0x7f9268001a40] frame P:617   Avg QP:20.92  size:  4380
[libx264 @ 0x7f9268001a40] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0x7f9268001a40] mb P  I16..4:  0.2%  0.0%  0.0%  P16..4:  1.2%  0.0%  0.0%  0.0%  0.0%    skip:98.6%
[libx264 @ 0x7f9268001a40] coded y,uvDC,uvAC intra: 32.1% 18.5% 15.1% inter: 0.4% 0.4% 0.0%
[libx264 @ 0x7f9268001a40] i16 v,h,dc,p: 60% 34%  5%  1%
[libx264 @ 0x7f9268001a40] i8c dc,h,v,p: 77% 17%  5%  1%
[libx264 @ 0x7f9268001a40] kb/s:631592.62
[swscaler @ 0x7f926ad79e00] Warning: data is not aligned! This can lead to a speed loss
```

Can draw but not see anything.
Just to be clear - I did not re-configure X11 to have a virtual screen - I expected the window to be mirrored without more setup than being in the uinput group, running `./weylus` and opening the webpage in the android tablet

**Comment by H-M-H** [comment]
Alright, I got around to implement some more debugging on the browser side and from the looks of it chrome on iOS/iPadOS just does not support [Media Source Extensions](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API) and thus can not work. The strange thing is, I can not find any docs on what chrome even implements on iOS/iPadOS.

Chrome on Android should work though. You can try the latest build of weylus and see if the debug log is more useful, also note that I added a debug window to the browser side: https://github.com/H-M-H/Weylus/actions/runs/232946468

**Comment by DavidVentura** [comment]
Will you make a release? takes a while to build, i can wait until next release otherwise

**Comment by H-M-H** [comment]
You should be able to download the artifacts I linked above (if you are signed in).

**Comment by DavidVentura** [comment]
Missed that. 
I have to type the error because I can't get the clipboard of the tablet into this network


lib.js:L264:31: Uncaught TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.

**Comment by H-M-H** [comment]
Thanks, this is indeed helpful. Please try if this works already: https://github.com/H-M-H/Weylus/actions/runs/234368661

**Comment by DavidVentura** [comment]
Now it's a lot less clear:

The browser console says
undefined:Lundefined:undefined: undefined
!
```
WEYLUS_LOG_LEVEL=TRACE ./weylus
Sep 01 15:51:25.693  INFO weylus::gui: Found more than one IP address for browsers to connect to,
Sep 01 15:51:25.693  INFO weylus::gui: other urls are:
Sep 01 15:51:25.693  INFO weylus::gui: http://192.168.122.1:1701
Sep 01 15:51:25.693  INFO weylus::gui: http://192.168.250.1:1701
Sep 01 15:51:25.693  INFO weylus::web: Webserver listening at 0.0.0.0:1701...
Sep 01 15:51:25.693  INFO weylus::gui: http://172.17.0.1:1701
Sep 01 15:51:26.901 TRACE hyper::proto::h1::conn: Conn::read_head
Sep 01 15:51:26.901 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy }
Sep 01 15:51:26.901 TRACE hyper::proto::h1::conn: Conn::read_head
Sep 01 15:51:26.901 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy }
Sep 01 15:51:26.902 TRACE hyper::proto::h1::conn: Conn::read_head
Sep 01 15:51:26.902 DEBUG hyper::proto::h1::io: read 508 bytes
Sep 01 15:51:26.902 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 508])
Sep 01 15:51:26.902 TRACE hyper::proto::h1::role: Request.parse Complete(508)
Sep 01 15:51:26.902 DEBUG hyper::proto::h1::io: parsed 9 headers
Sep 01 15:51:26.902 DEBUG hyper::proto::h1::conn: incoming body is empty
Sep 01 15:51:26.902 DEBUG weylus::web: Got request: Request { method: GET, uri: /, version: HTTP/1.1, headers: {"host": "192.168.2.100:1701", "connection": "keep-alive", "cache-control": "max-age=0", "upgrade-insecure-requests": "1", "save-data": "on", "user-agent": "Mozilla/5.0 (Linux; Android 10; SM-T510) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", "accept-encoding": "gzip, deflate", "accept-language": "en-GB,en;q=0.9,en-US;q=0.8,es-AR;q=0.7,es;q=0.6,nl;q=0.5"}, body: Body(Empty) }
Sep 01 15:51:26.902  INFO weylus::web: Client connected: 192.168.2.133:56538
Sep 01 15:51:26.902 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2792)), req_method=Some(GET)
Sep 01 15:51:26.902 DEBUG hyper::proto::h1::io: flushed 2910 bytes
Sep 01 15:51:26.902 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Sep 01 15:51:27.107 TRACE hyper::proto::h1::conn: Conn::read_head
Sep 01 15:51:27.107 DEBUG hyper::proto::h1::io: read 392 bytes
Sep 01 15:51:27.107 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 392])
Sep 01 15:51:27.107 TRACE hyper::proto::h1::role: Request.parse Complete(392)
Sep 01 15:51:27.107 DEBUG hyper::proto::h1::io: parsed 8 headers
Sep 01 15:51:27.107 DEBUG hyper::proto::h1::conn: incoming body is empty
Sep 01 15:51:27.107 DEBUG weylus::web: Got request: Request { method: GET, uri: /style.css, version: HTTP/1.1, headers: {"host": "192.168.2.100:1701", "connection": "keep-alive", "save-data": "on", "user-agent": "Mozilla/5.0 (Linux; Android 10; SM-T510) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36", "accept": "text/css,*/*;q=0.1", "referer": "http://192.168.2.100:1701/", "accept-encoding": "gzip, deflate", "accept-language": "en-GB,en;q=0.9,en-US;q=0.8,es-AR;q=0.7,es;q=0.6,nl;q=0.5"}, body: Body(Empty) }
Sep 01 15:51:27.107 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2840)), req_method=Some(GET)
Sep 01 15:51:27.107 DEBUG hyper::proto::h1::io: flushed 2957 bytes
Sep 01 15:51:27.107 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Sep 01 15:51:27.108 TRACE hyper::proto::h1::conn: Conn::read_head
Sep 01 15:51:27.108 DEBUG hyper::proto::h1::io: read 374 bytes
Sep 01 15:51:27.108 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 374])
Sep 01 15:51:27.108 TRACE hyper::proto::h1::role: Request.parse Complete(374)
Sep 01 15:51:27.108 DEBUG hyper::proto::h1::io: parsed 8 headers
Sep 01 15:51:27.108 DEBUG hyper::proto::h1::conn: incoming body is empty
Sep 01 15:51:27.108 DEBUG weylus::web: Got request: Request { method: GET, uri: /lib.js, version: HTTP/1.1, headers: {"host": "192.168.2.100:1701", "connection": "keep-alive", "save-data": "on", "user-agent": "Mozilla/5.0 (Linux; Android 10; SM-T510) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36", "accept": "*/*", "referer": "http://192.168.2.100:1701/", "accept-encoding": "gzip, deflate", "accept-language": "en-GB,en;q=0.9,en-US;q=0.8,es-AR;q=0.7,es;q=0.6,nl;q=0.5"}, body: Body(Empty) }
Sep 01 15:51:27.108 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(12998)), req_method=Some(GET)
Sep 01 15:51:27.109 DEBUG hyper::proto::h1::io: flushed 13123 bytes
Sep 01 15:51:27.109 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Sep 01 15:51:27.267 TRACE weylus::websocket: Got: GetCapturableList
Sep 01 15:51:27.270 TRACE weylus::websocket: Got: ClientConfiguration { stylus_support: true, faster_capture: true, capturable_id: 0, capture_cursor: true }
[libx264 @ 0x7fb964001a40] MB rate (28800000) > level limit (16711680)
[libx264 @ 0x7fb964001a40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7fb964001a40] profile Constrained Baseline, level 6.2, 4:2:0, 8-bit
[libx264 @ 0x7fb964001a40] 264 - core 160 r3011 cde9a93 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=6 lookahead_threads=6 sliced_threads=1 slices=6 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=12 keyint_min=1 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to '(null)':
    Stream #0:0: Video: h264, yuv420p, 5120x1440, q=2-31
```

**Comment by DavidVentura** [comment]
The error happens in `on_message`:

`        if (video.buffered.length > 0 && video.buffered.end(video.buffered.length - 1) - video.currentTime > 0.01)`

where video.buffered.length == 0, the error (yay for android remote debugging) is

```
Uncaught DOMException: Failed to execute 'end' on 'TimeRanges': The index provided (4294967295) is greater than the maximum bound (0).
    at eval (eval at webSocket.onmessage (http://192.168.2.100:1701/lib.js:263:9), <anonymous>:1:17)
    at WebSocket.webSocket.onmessage (http://192.168.2.100:1701/lib.js:263:9)
```

**Comment by H-M-H** [comment]
I have to admit, this is getting weird and thanks for your help! It looks like short circuit logic does not work the way I think it would here and for some reason the second condition is checked, even though `video.buffered.length == 0`. The index `4294967295` is clearly the result of an underflow (`4294967295 == 2^32-1`). Maybe restructuring the check helps, please tell me if this build works: https://github.com/H-M-H/Weylus/actions/runs/234635195

**Comment by H-M-H** [comment]
Build of https://github.com/H-M-H/Weylus/commit/ca725290a031fbdd8579bf74672ed43e83736ea7 for people without a Github account: [Linux-exec.zip](https://github.com/H-M-H/Weylus/files/5213245/Linux-exec.zip) (Unfortunately artifacts are only available if you are logged in...).

**Comment by PrathamSoni** [comment]
Hello, I am having a similar error on Safari, however.

After authenticating, the screen is completely white and there are no captures available to switch to. What is the fix here?

**Comment by H-M-H** [comment]
I am afraid you need iOS/iPadOS 13 or later. Some required browser features are just not available with older versions.

**Comment by PrathamSoni** [comment]
I see.

Thanks for your prompt response and all the great work you've done!

**Comment by H-M-H** [comment]
Closing this as the original issue has been resolved. Feel free to open a new issue if you encounter similar problems.
