### ISSUE TITLE
error ultima versão

### ISSUE THREAD

**Issue by MarceloMachadoxD** [H-M-H/Weylus#36]
Hy guy, im get problem to install the last version on ubuntu 19.10

`fmachado@machado:~/Downloads$ sudo dpkg -i Weylus_0.9.0_amd64.deb 
[sudo] senha para fmachado: 
dpkg: erro ao processar o arquivo Weylus_0.9.0_amd64.deb (--install):
 a interpretar o ficheiro '/var/lib/dpkg/tmp.ci/control' perto da linha 9 pacote 'weylus':
 campo 'Depends', erro de sintaxe após referência a pacote 'diversion'
Erros foram encontrados durante o processamento de:
 Weylus_0.9.0_amd64.deb
fmachado@machado:~/Downloads$ 

`

**Comment by H-M-H** [comment]
Thanks for the report, this is a know issue and will be fixed in the next version, see #33. In the mean time, just download Weylus via [linux.zip](https://github.com/H-M-H/Weylus/releases/download/v0.9.0/linux.zip).
