### ISSUE TITLE
Enable ability to disable video?

### ISSUE THREAD

**Issue by zeptic99** [H-M-H/Weylus#38]
I'm sorry if this feature already exists but I'd like to have a way to disable the video / screen capture so that I can use my phone as a graphics tablet with just a blank screen on it

**Comment by H-M-H** [comment]
This is not possible yet but I will look into it once I have some more time.

**Comment by shubhampaul** [comment]
Yeah, this would be really useful to reduce resource consumption on slow CPUs (without GPU acceleration). Especially when we need that resource for things like Zoom meetings etc.

**Comment by H-M-H** [comment]
If CPU consumption is a problem try increasing the `Frame Interval` to something like `500`ms. Like that Weylus only encodes two frames per second.

**Comment by shubhampaul** [comment]
Thanks. That is very good advice.

**Comment by H-M-H** [comment]
Implemented with https://github.com/H-M-H/Weylus/commit/dffe0389513a60043092cada2d1290596b2d2322.

There is still room to improve this, maybe something like https://github.com/H-M-H/Weylus/issues/57#issuecomment-785005936:
> I was thinking about a canvas element that shows the last few strokes and have those fade away.

**Comment by H-M-H** [comment]
First version of fading strokes is implemented here: https://github.com/H-M-H/Weylus/tree/webgl_canvas, feel free to try it and provide feedback: https://github.com/H-M-H/Weylus/actions/runs/717713511#artifacts

**Comment by Cris70** [comment]
Does not seem to work unfortunately on my old iPad with iOS 10.x.
I tried with Chrome (I know this is not supposed to work), Firefox, Safari. 
The browser correctly connects to Weylus, but the dropdown is always empty.

**Comment by H-M-H** [comment]
Does the log inside the browser window display anything? I am probably using some APIs or syntax that is too recent for iOS 10, perhaps you can find the problem using web inspector, see: https://github.com/H-M-H/Weylus/issues/57#issuecomment-784615490. These dropdowns are initialized pretty early, so I am curious what's breaking things this early.

If you want to experiment with JavaScript yourself, check out these options when running Weylus ([latest builds](https://github.com/H-M-H/Weylus/actions/runs/719276614#artifacts) only) via commandline:
```
--print-lib-js     Print lib.js served by Weylus.
--custom-lib-js    Use custom lib.js to be served by Weylus.
```

Also note, that `PointerEvents` apparently are a very recent addition to Safari on iOS, according to [caniuse](https://caniuse.com/?search=Pointerevent), they are not supported for iOS 10, so even if video playback is removed, iOS 10 devices will still not work :/
You or anyone else could try implementing their own client using https://github.com/jquery-archive/PEP or plain [TouchEvents](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent). Have a look at [src/protocol.rs](https://github.com/H-M-H/Weylus/blob/master/src/protocol.rs) to get an overview about what messages to send over websockets.

I don't think I will support anything else but PointerEvents, it's just too much of a hassle.

**Comment by Cris70** [comment]
@H-M-H thank you for your explanation.
If I understand correctly, even if I find the problem with initializing the drop down, Weylus will not work anyway because of the lack of support for PointerEvents on iOS 10. If so, I'm not going to waste mine and your time investigating it any further, as my objective was to be able to use my old iPad as a drawing pad during videoconferencing (for shared chalkboard).
Thank you BTW for all your efforts @H-M-H, Weylus is a great piece of software!

**Comment by H-M-H** [comment]
Yes, you understand correctly, it still won't work. You can consider the above documentation for anyone who really wants to get this working.

**Comment by H-M-H** [comment]
This is now implemented and merged into the master branch.
