### ISSUE TITLE
Having trouble setting up NVENC hardware acceleration

### ISSUE THREAD

**Issue by highfellow** [H-M-H/Weylus#39]
Hi,

I have just installed Weylus on my Linux Mint machine. It is nice to see it working and it is just about fast enough to play with, but not really for serious use, as the refresh rate seem to be only a few frames a second at best. I would like to set up hardware acceleration but I am having trouble with this. My graphics card is a GeForce GTX 970. I have tried installing two of the libnvidia-encode libraries that are listed in the repository. With the -435 version, a message comes up in the weylus error messages saying that the driver does not support NVENC. With the -450 version, this message does not appear, so I assume that this is the right version. There is no specific message to say that NVENC has been enabled though. Installing this doesn't seem to increase the frame rate of the mirrored screen, which lags up to a second or two behind the desktop screen when I am drawing freely.

Do you know how I can check if NVENC has been enabled, and if it is not, what I need to do to get it working?

**Comment by H-M-H** [comment]
Hello,

if you start Weylus inside your terminal there will be some additional messages from ffmpeg. Once you connect your tablet you should see one of the following messages:
- `Stream #0:0: Video: h264, yuv420p, 1920x1080, q=2-31` -> software encoding
- `Stream #0:0: Video: h264 (High), vaapi_vld, 1920x1080, q=2-31` -> hardware encoding via VAAPI
- `Stream #0:0: Video: h264 (Main), bgr0, 1920x1080, q=2-31` -> NVENC

To check if NVENC is working at all you can try this ffmpeg command that tries to encode a video from a testsource via NVENC: `ffmpeg -f lavfi -i testsrc2=size=1920x1080 -t 10 -c h264_nvenc test.mkv`

**Comment by highfellow** [comment]
I have managed to get this working now. I tried the following command to encode 5 seconds of video from the desktop:
`ffmpeg -t 0:5 -video_size 200x200 -framerate 25 -f x11grab -i :0.0+100,200 -c h264_nvenc output.mkv`

Initially, this failed with an error saying no CUDA capable device detected. However I found out that my system was running the open source nouveau nvidia driver, not the proprietary nvidia driver. (Using this command to detect the graphics driver: `lspci -k | grep -EA3 'VGA|3D|Display'`). With the proprietary driver installed (see: https://linuxconfig.org/install-the-latest-nvidia-linux-driver ), this command runs okay, with the output including the line:
`Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_nvenc))`

Unfortunately, the frame rate of the video on my tablet is not much better. I have set the frame interval in the Weylus settings tab to be 5 ms. When I draw a simple shape like the letter A, the picture on the tablet lags by as much as a couple of seconds compared to the desktop's screen. The mouse on the desktop machine does respond quite quickly to the movements of the pen though. I think the reason for this is that my tablet is not capable of handling the video stream from the desktop. With weylus running and the tablet connected, a CPU monitor shows the tablet's CPU is fully loaded. My tablet is a Samsung Galaxy Tab S3. I guess there is no way around this apart from getting a more up to date tablet.

One question I have is what format is used to send the video from the desktop to the tablet? Is it sent as raw video or in a compressed format? I am wondering if a change to the compression settings in weylus might enable the tablet to cope better with the video stream.

Thanks a lot for helping me get as far as I have.

**Comment by highfellow** [comment]
I would like to add that I have checked how much it loads the CPU on my tablet to play full screen video from YouTube, and it seems to be about 30-50%. Also, when I am running Weylus with the tablet connected, the CPU load on the desktop is pretty low - under 10%.

Something I am wondering is if it is possible for Weylus to include an option for the user to specify custom ffmpeg settings, so people can experiment with different options to handle problems like this?

**Comment by highfellow** [comment]
Specifically, I am wondering if the tablet I am using has hardware acceleration to decode some but not all video sub-formats, so that it can cope okay with the video from YouTube, but not with the video sent by Weylus?

**Comment by H-M-H** [comment]
Ok, so hardware accelerated encoding works but encoding speed apparently was not the problem in the first place. You could verify this by opening the link to weylus on your computer and just connect to localhost.

> the picture on the tablet lags by as much as a couple of seconds compared to the desktop's screen.

This definitely should not be the case, I tested end to end latency some time ago and 10-20ms is possible, so a couple seconds is really bad.

> One question I have is what format is used to send the video from the desktop to the tablet? Is it sent as raw video or in a compressed format?

The video is encoded as AVC/H.264 inside an mp4 container. I chose this format as it is highly optimized and one of the most widely supported formats. You should be able to create a file very similar to what weylus streams with the following ffmpeg command:
```
ffmpeg -f x11grab -i :0.0+0,0 -c:v h264_nvenc -g 12 -bf 0 -preset llhq -zerolatency 1 -rc vbr_hq -cq 21 -t 10 -movflags frag_keyframe+empty_moov+default_base_moof test.mp4
```
You can try to record a video like that and then serve it from a web server (for example with https://github.com/svenstaro/miniserve) to check if your tablet also chokes on that. I am not too convinced of that though, as long as your are not streaming 4K there should be no trouble playing the video.

> Something I am wondering is if it is possible for Weylus to include an option for the user to specify custom ffmpeg settings, so people can experiment with different options to handle problems like this?

I think this would be a bit cumbersome and I wanted to keep things simple, but you can easily play with the options yourself (in case video decoding is really the bottleneck) by changing them here: https://github.com/H-M-H/Weylus/blob/ca725290a031fbdd8579bf74672ed43e83736ea7/lib/encode_video.c#L60-L62 , https://github.com/H-M-H/Weylus/blob/ca725290a031fbdd8579bf74672ed43e83736ea7/lib/encode_video.c#L186-L189 and here https://github.com/H-M-H/Weylus/blob/ca725290a031fbdd8579bf74672ed43e83736ea7/lib/encode_video.c#L255

Thanks to the docker image, compilation should not be a problem, it only takes some time.

> Specifically, I am wondering if the tablet I am using has hardware acceleration to decode some but not all video sub-formats, so that it can cope okay with the video from YouTube, but not with the video sent by Weylus?

If it's got any hardware acceleration, I am sure H.264 is among them.

What I suspect, is that either for some reason your tablet tries to buffer too much and does not like playing every frame immediately on arrival or receiving every frame separately (which is what is done to keep latency minimal) in JavaScript is slow for some reason.

**Comment by H-M-H** [comment]
Please try again with the latest build of Weylus: https://github.com/H-M-H/Weylus/suites/1610746727/artifacts/29483847 this probably fixes this issue.
