### ISSUE TITLE
Doesn't seem to work.

### ISSUE THREAD

**Issue by someone7070** [H-M-H/Weylus#42]
Hello. I followed the instructions in the readme. I installed the .deb package, and followed the instructions for uinput. The program runs on my computer, but when I connect to the ip address given by the program on my phone, I am greeted with a settings screen, and nothing changes from there. It says the device makes a connection, but it doesn't appear to do anything afterward. Am I doing something wrong, perhaps?

**Comment by H-M-H** [comment]
I will need some more information to help you.

- Does it work if you open the URL on your computer in the browser so you have a connection to localhost?
- Is there any kind of firewall running?
- Which browser are you using?
- Which phone are you using?
- What's the output if you start Weylus like this: `WEYLUS_LOG_LEVEL=TRACE weylus`

**Comment by someone7070** [comment]
Sorry if there are any formatting issues with my reply.

>Does it work if you open the URL on your computer in the browser so you have a connection to localhost?

If I start Weylus on my computer and open a browser to the IP address it tells me to open on my tablet, it does seem to work. It shows my screen within the browser, though there is some odd behavior with it. Going back to the phone (and now my tablet) while the browser window is still open has no effect though.

>Is there any kind of firewall running?

While I was at work, possibly. I'm at my apartment now, and the only address it is telling me to connect to is the 192.168 address, and it still doesn't work on my phone or tablet.

>Which browser are you using?

Firefox on all devices (computer, phone and tablet).

>Which phone are you using?

I am using an old Huawei Honor 8, I believe, and the tablet is some brand called Voorca, I think.

>What's the output if you start Weylus like this: WEYLUS_LOG_LEVEL=TRACE weylus

Here it is:
`*****@*****:~/Desktop/$ WEYLUS_LOG_LEVEL=TRACE weylus
Oct 25 08:35:19.403  INFO weylus::gui: Found more than one IP address for browsers to connect to,
Oct 25 08:35:19.403  INFO weylus::gui: other urls are:
Oct 25 08:35:19.403  INFO weylus::gui: http://192.168.199.127:1701
Oct 25 08:35:19.403  INFO weylus::gui: http://25.52.162.33:1701
Oct 25 08:35:19.404  INFO weylus::web: Webserver listening at 0.0.0.0:1701...
Oct 25 08:35:28.206 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:35:28.206 DEBUG hyper::proto::h1::io: read 344 bytes
Oct 25 08:35:28.206 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 344])
Oct 25 08:35:28.206 TRACE hyper::proto::h1::role: Request.parse Complete(344)
Oct 25 08:35:28.206 DEBUG hyper::proto::h1::io: parsed 8 headers
Oct 25 08:35:28.207 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:35:28.207  INFO weylus::web: Client connected: 192.168.199.194:57138
Oct 25 08:35:28.207 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2677)), req_method=Some(GET)
Oct 25 08:35:28.207 DEBUG hyper::proto::h1::io: flushed 2795 bytes
Oct 25 08:35:28.207 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Oct 25 08:35:28.293 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:35:28.293 DEBUG hyper::proto::h1::io: read 317 bytes
Oct 25 08:35:28.293 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 317])
Oct 25 08:35:28.293 TRACE hyper::proto::h1::role: Request.parse Complete(317)
Oct 25 08:35:28.293 DEBUG hyper::proto::h1::io: parsed 8 headers
Oct 25 08:35:28.293 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:35:28.293 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2587)), req_method=Some(GET)
Oct 25 08:35:28.294 DEBUG hyper::proto::h1::io: flushed 2704 bytes
Oct 25 08:35:28.294 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Oct 25 08:35:28.300 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:35:28.301 DEBUG hyper::proto::h1::io: read 299 bytes
Oct 25 08:35:28.301 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 299])
Oct 25 08:35:28.301 TRACE hyper::proto::h1::role: Request.parse Complete(299)
Oct 25 08:35:28.301 DEBUG hyper::proto::h1::io: parsed 8 headers
Oct 25 08:35:28.301 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:35:28.301 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(12618)), req_method=Some(GET)
Oct 25 08:35:28.301 DEBUG hyper::proto::h1::io: flushed 12743 bytes
Oct 25 08:35:28.301 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Oct 25 08:35:47.896 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:35:47.896 DEBUG hyper::proto::h1::io: read 344 bytes
Oct 25 08:35:47.896 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 344])
Oct 25 08:35:47.896 TRACE hyper::proto::h1::role: Request.parse Complete(344)
Oct 25 08:35:47.896 DEBUG hyper::proto::h1::io: parsed 8 headers
Oct 25 08:35:47.896 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:35:47.896  INFO weylus::web: Client connected: 192.168.199.194:57138
Oct 25 08:35:47.897 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2677)), req_method=Some(GET)
Oct 25 08:35:47.897 DEBUG hyper::proto::h1::io: flushed 2795 bytes
Oct 25 08:35:47.897 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Oct 25 08:35:47.976 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:35:47.976 DEBUG hyper::proto::h1::io: read 317 bytes
Oct 25 08:35:47.976 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 317])
Oct 25 08:35:47.976 TRACE hyper::proto::h1::role: Request.parse Complete(317)
Oct 25 08:35:47.976 DEBUG hyper::proto::h1::io: parsed 8 headers
Oct 25 08:35:47.976 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:35:47.976 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2587)), req_method=Some(GET)
Oct 25 08:35:47.976 DEBUG hyper::proto::h1::io: flushed 2704 bytes
Oct 25 08:35:47.976 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Oct 25 08:35:47.984 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:35:47.984 DEBUG hyper::proto::h1::io: read 299 bytes
Oct 25 08:35:47.984 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 299])
Oct 25 08:35:47.984 TRACE hyper::proto::h1::role: Request.parse Complete(299)
Oct 25 08:35:47.984 DEBUG hyper::proto::h1::io: parsed 8 headers
Oct 25 08:35:47.984 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:35:47.984 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(12618)), req_method=Some(GET)
Oct 25 08:35:47.984 DEBUG hyper::proto::h1::io: flushed 12743 bytes
Oct 25 08:35:47.984 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Oct 25 08:36:51.394 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:36:51.394 DEBUG hyper::proto::h1::io: read 0 bytes
Oct 25 08:36:51.394 TRACE hyper::proto::h1::io: parse eof
Oct 25 08:36:51.394 TRACE hyper::proto::h1::conn: State::close_read()
Oct 25 08:36:51.394 DEBUG hyper::proto::h1::conn: read eof
Oct 25 08:36:51.394 TRACE hyper::proto::h1::conn: State::close_write()
Oct 25 08:36:51.394 TRACE hyper::proto::h1::conn: State::close_read()
Oct 25 08:36:51.394 TRACE hyper::proto::h1::conn: State::close_write()
Oct 25 08:36:51.394 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
Oct 25 08:36:51.394 TRACE hyper::proto::h1::conn: shut down IO complete
Oct 25 08:37:29.515 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:37:29.515 DEBUG hyper::proto::h1::io: read 339 bytes
Oct 25 08:37:29.515 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 339])
Oct 25 08:37:29.515 TRACE hyper::proto::h1::role: Request.parse Complete(339)
Oct 25 08:37:29.515 DEBUG hyper::proto::h1::io: parsed 7 headers
Oct 25 08:37:29.515 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:37:29.515  INFO weylus::web: Client connected: 192.168.199.147:56866
Oct 25 08:37:29.515 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2677)), req_method=Some(GET)
Oct 25 08:37:29.515 DEBUG hyper::proto::h1::io: flushed 2795 bytes
Oct 25 08:37:29.515 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Oct 25 08:37:29.792 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:37:29.792 DEBUG hyper::proto::h1::io: read 283 bytes
Oct 25 08:37:29.792 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 283])
Oct 25 08:37:29.792 TRACE hyper::proto::h1::role: Request.parse Complete(283)
Oct 25 08:37:29.792 DEBUG hyper::proto::h1::io: parsed 7 headers
Oct 25 08:37:29.792 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:37:29.792 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(12618)), req_method=Some(GET)
Oct 25 08:37:29.792 DEBUG hyper::proto::h1::io: flushed 12743 bytes
Oct 25 08:37:29.792 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Oct 25 08:37:29.792 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:37:29.792 DEBUG hyper::proto::h1::io: read 301 bytes
Oct 25 08:37:29.792 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 301])
Oct 25 08:37:29.792 TRACE hyper::proto::h1::role: Request.parse Complete(301)
Oct 25 08:37:29.792 DEBUG hyper::proto::h1::io: parsed 7 headers
Oct 25 08:37:29.792 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:37:29.792 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2587)), req_method=Some(GET)
Oct 25 08:37:29.792 DEBUG hyper::proto::h1::io: flushed 2704 bytes
Oct 25 08:37:29.792 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Output #0, mp4, to '(null)':
    Stream #0:0: Video: h264 (Main), bgr0, 1920x1080, q=2-31
Oct 25 08:37:46.088 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:37:46.088 DEBUG hyper::proto::h1::io: read 344 bytes
Oct 25 08:37:46.088 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 344])
Oct 25 08:37:46.088 TRACE hyper::proto::h1::role: Request.parse Complete(344)
Oct 25 08:37:46.089 DEBUG hyper::proto::h1::io: parsed 8 headers
Oct 25 08:37:46.089 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:37:46.089  INFO weylus::web: Client connected: 192.168.199.194:57148
Oct 25 08:37:46.089 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2677)), req_method=Some(GET)
Oct 25 08:37:46.089 DEBUG hyper::proto::h1::io: flushed 2795 bytes
Oct 25 08:37:46.089 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Oct 25 08:37:46.179 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:37:46.179 DEBUG hyper::proto::h1::io: read 317 bytes
Oct 25 08:37:46.179 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 317])
Oct 25 08:37:46.179 TRACE hyper::proto::h1::role: Request.parse Complete(317)
Oct 25 08:37:46.180 DEBUG hyper::proto::h1::io: parsed 8 headers
Oct 25 08:37:46.180 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:37:46.180 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2587)), req_method=Some(GET)
Oct 25 08:37:46.180 DEBUG hyper::proto::h1::io: flushed 2704 bytes
Oct 25 08:37:46.180 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Oct 25 08:37:46.184 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:37:46.184 DEBUG hyper::proto::h1::io: read 299 bytes
Oct 25 08:37:46.184 TRACE hyper::proto::h1::role: Request.parse([Header; 100], [u8; 299])
Oct 25 08:37:46.184 TRACE hyper::proto::h1::role: Request.parse Complete(299)
Oct 25 08:37:46.184 DEBUG hyper::proto::h1::io: parsed 8 headers
Oct 25 08:37:46.184 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:37:46.184 DEBUG hyper::proto::h1::conn: incoming body is empty
Oct 25 08:37:46.184 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy }
Oct 25 08:37:46.184 TRACE hyper::proto::h1::role: Server::encode status=200, body=Some(Known(12618)), req_method=Some(GET)
Oct 25 08:37:46.185 DEBUG hyper::proto::h1::io: flushed 12743 bytes
Oct 25 08:37:46.185 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Oct 25 08:37:51.199 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:37:51.199 DEBUG hyper::proto::h1::io: read 0 bytes
Oct 25 08:37:51.199 TRACE hyper::proto::h1::io: parse eof
Oct 25 08:37:51.199 TRACE hyper::proto::h1::conn: State::close_read()
Oct 25 08:37:51.199 DEBUG hyper::proto::h1::conn: read eof
Oct 25 08:37:51.199 TRACE hyper::proto::h1::conn: State::close_write()
Oct 25 08:37:51.199 TRACE hyper::proto::h1::conn: State::close_read()
Oct 25 08:37:51.199 TRACE hyper::proto::h1::conn: State::close_write()
Oct 25 08:37:51.199 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
Oct 25 08:37:51.199 TRACE hyper::proto::h1::conn: shut down IO complete
Oct 25 08:38:48.399 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:38:48.399 DEBUG hyper::proto::h1::io: read 0 bytes
Oct 25 08:38:48.399 TRACE hyper::proto::h1::io: parse eof
Oct 25 08:38:48.399 TRACE hyper::proto::h1::conn: State::close_read()
Oct 25 08:38:48.399 DEBUG hyper::proto::h1::conn: read eof
Oct 25 08:38:48.399 TRACE hyper::proto::h1::conn: State::close_write()
Oct 25 08:38:48.399 TRACE hyper::proto::h1::conn: State::close_read()
Oct 25 08:38:48.399 TRACE hyper::proto::h1::conn: State::close_write()
Oct 25 08:38:48.399 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
Oct 25 08:38:48.399 TRACE hyper::proto::h1::conn: shut down IO complete
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: Conn::read_head
Oct 25 08:39:25.231 DEBUG hyper::proto::h1::io: read 0 bytes
Oct 25 08:39:25.231 TRACE hyper::proto::h1::io: parse eof
Oct 25 08:39:25.231 DEBUG hyper::proto::h1::io: read 0 bytes
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: State::close_read()
Oct 25 08:39:25.231 TRACE hyper::proto::h1::io: parse eof
Oct 25 08:39:25.231 DEBUG hyper::proto::h1::conn: read eof
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: State::close_write()
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: State::close_read()
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: State::close_read()
Oct 25 08:39:25.231 DEBUG hyper::proto::h1::conn: read eof
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: State::close_write()
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: State::close_write()
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: State::close_read()
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: State::close_write()
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: shut down IO complete
Oct 25 08:39:25.231 TRACE hyper::proto::h1::conn: shut down IO complete
`

**Comment by H-M-H** [comment]
Alright, looks like there is no firewall problem, the video starts streaming fine but is not displayed. You mentioned you use firefox, do you use the latest version, because everything below version 80 does not work. So make sure you have the latest version installed or try if chrome works.

**Comment by someone7070** [comment]
>You mentioned you use firefox, do you use the latest version, because everything below version 80 does not work.

That did the trick! Problem solved on my phone, but I don't think my tablet can handle the newer versions of Firefox.
