### ISSUE TITLE
Screen Mirroring not working on chrome for android

### ISSUE THREAD

**Issue by AKuederle** [H-M-H/Weylus#43]
First of all thank you very much for this awesome software!

I wanted to test it using my Android phone and my quite old Samsung tablet. However, on both devices, I can not any video feed. I tested it in a browser window on my PC, which seems to work. So it seems to be an issue with the client device.

Do you have any idea about the minimum requirements for the clients?

Thanks in advance!

**Comment by H-M-H** [comment]
Even though there is not much code that runs on the browser side it is really hard to tell with which browsers Weylus is compatible. I tried to find some tools to analyze the code and check against browser compatibility data like that of https://caniuse.com/ and https://github.com/mdn/browser-compat-data but weirdly any such tool does not seem to exist. For the next version I will at least add some log that will display JavaScript errors.

The video codec used is H.264 with pixel format YUV420p inside an mp4 container, which is one of the most common formats around and should be supported by nearly any device. You could try to record a video using the command `ffmpeg -f x11grab -i :0.0+0,0 -pix_fmt yuv420p -c:v libx264 -g 12 -bf 0 -preset ultrafast -tune zerolatency -crf 23 -t 10 -movflags frag_keyframe+empty_moov+default_base_moof test.mp4` which is nearly the same thing Weylus sends over websockets and serve it with a web server like https://github.com/svenstaro/miniserve to check if video decoding is the problem.

**Comment by H-M-H** [comment]
Please try again with the latest build: https://github.com/H-M-H/Weylus/suites/1610746727/artifacts/29483847 this is probably fixed now.
