### ISSUE TITLE
The list "Capture" is empty

### ISSUE THREAD

**Issue by effepivi** [H-M-H/Weylus#45]
Hi there,
I installed the bin file for Linux. It runs well, no error/warning. I can connect from my iPad. However the list in "Capture" is empty. When I click on "Refresh list", nothing happens.

**Comment by H-M-H** [comment]
The things I can think of right now:

- Check your firewall is open on both of the required ports (1701 and 9001 by default)
- You are not running Wayland, which unfortunately is not supported at the moment
- There is a problem with your window manager, you could install `wmctrl` and check the output of `wmctrl -l`

**Comment by effepivi** [comment]
Silly me. I only opened one port. Opening the second one helped. However the list is disable and I can only see the whole desktop. As I have two monitors everything is small on the iPad.
Thanks for your prompt reply.

**Comment by H-M-H** [comment]
I see, what about the other two things I mentioned? Also what's the output of `xrandr`? Weylus should be able to recognize monitors `xrandr` recognizes and display them in the list.

**Comment by H-M-H** [comment]
Feel free to reopen this if you still have problems, closing for now.
