### ISSUE TITLE
Windows, MacOS, Linux issues

### ISSUE THREAD

**Issue by GamerPlayer888** [H-M-H/Weylus#46]
**I have an iPad from 5th, so it doesn't support the Apple Pencil and I did the following tests with an touch stylus flat-tipped** _(Rather accurate.)_**.**

### Windows 10 (20H2):

> I tried to make it work even though I knew what I was getting into, and the remote touchscreen does not work _(Even if the option is enabled.)_ but mirroring screen does _(Except that it does not show the pointer.)_.
> Running as administrator or changing parameters does not change the result. I can't even select hardware acceleration, I don't use proxy or VPN, maybe it's the DNS? I don't think so, because I use it on all my devices.

### MacOS 10.15 (in VM):

> Executed on the same machine and identical problem. 🤷‍♂️

### Linux Mint 20:

> Tried it on my old laptop and it's really lightweight, ignoring those small defects due to control remote works very well. _(It will be possible to connect via USB to reduce latency?)_
> The first test I did was to go on skribble.io to do some sketches and in drawing a circle, I get an D. 
![IMG_8491 20-11-09 03_48_41](https://user-images.githubusercontent.com/66787796/98495379-491f3c80-223f-11eb-899c-425cf809e882.gif)
> I tried again later on GIMP and it was most close an circle.
![Prova](https://user-images.githubusercontent.com/66787796/98495404-576d5880-223f-11eb-84c4-46cfdeb557b2.gif)

I noticed that the first time I run on each OS from this error:
`ERROR Failed binding to socket: Required address not valid in your context. (os error 10049)`
After that no longer appears.

That's all~

**Comment by H-M-H** [comment]
Thanks for your report!
Some thoughts:

- As mirroring the screen works this means the websocket connection is fine and PointerEvents get through too, so I suspect there is some option you need to find and enable to permit Weylus to control your mouse
- hardware acceleration and other features are unfortunately not available on windows as I just can't properly test it, hardware acceleration specifically should be rather easy to implement as it is just finding the right ffmpeg encoder for windows
- > It will be possible to connect via USB to reduce latency?

  I'd like to do that but this requires writing apps for iOS and Android and I simply don't have the time for this right now, but you can try to setup a peer to peer connection via USB tethering, I know this is possible with Android but I am unsure if this also works with iOS. This should reduce the latency by a few milliseconds but won't bring it down to zero as video encoding takes its time.
- The error you get seems a bit weird, from what I understand Weylus is trying to bind a socket to an invalid IP address, what's in the Bind Address field?

**Comment by GamerPlayer888** [comment]
> The error you get seems a bit weird, from what I understand Weylus is trying to bind a socket to an invalid IP address, what's in the Bind Address field?

0.0.0.0

**Comment by H-M-H** [comment]
You could try to just put the IP address you use to reach your computer from the iPad there, 0.0.0.0 is used to bind the websocket server on all available IP addresses but apparently this doesn't work for all of them.

**Comment by H-M-H** [comment]
Closing this for now.

**Comment by uzielweb** [comment]
How can I change the IP Address to bind. This is impossible after first error.

**Comment by H-M-H** [comment]
You are right, the current release of Weylus gets stuck if the address is already in use. This has been fixed on master and will be fixed with the next release.

**Comment by CoderTeam1** [comment]
same issue with me...doesnt run

**Comment by H-M-H** [comment]
Please open a separate issue with more details, like your operating system, all log messages and an exact description of what you have done and then observed.
