### ISSUE TITLE
Failed to initialize VAAPI connection

### ISSUE THREAD

**Issue by gabrc52** [H-M-H/Weylus#47]
I'm getting this on my Ryzen 5 3500U:

```
[AVHWDeviceContext @ 0x7fd50c001a40] libva: dlopen of /usr/lib/dri/radeonsi_drv_video.so failed: /usr/lib/dri/radeonsi_drv_video.so: wrong ELF class: ELFCLASS32
[AVHWDeviceContext @ 0x7fd50c001a40] Failed to initialise VAAPI connection: -1 (unknown libva error).
```

CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
GPU: AMD ATI 03:00.0 Picasso

Apparently, hardware accelaration works a bit faster on Windows than it does on Linux with my hardware.

It has happened to me on both ~Ubuntu (20.04 and 20.10)~ and Fedora (33)

Edit: it doesn't really happen on an Ubuntu live CD, I probably remembered wrong

**Comment by H-M-H** [comment]
Thanks for the report! It looks like for some reason you have the 32bit version of the amdgpu driver installed, so you should check if you can get the 64bit version installed.

Additionally you could check if ffmpeg is capable of utilizing hardware acceleration with the following command: `ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -f lavfi -i testsrc2=size=1920x1080 -vf 'format=nv12,hwupload' -vcodec h264_vaapi -t 10 test.mkv`, you might need to change `renderD128` to `renderD129` or something higher to make it work. Weylus is using ffmpeg for hardware acceleration, so if you can't get ffmpeg to work, Weylus won't work either.

**Comment by gabrc52** [comment]
On a second look, it seems like it's actually a Fedora issue; I'll ask on their forums

**Comment by H-M-H** [comment]
I see, as this does work on Ubuntu for you I am closing this issue.
