### ISSUE TITLE
The webpage created by the Weylus session does not load on the tablet

### ISSUE THREAD

**Issue by deniskup** [H-M-H/Weylus#48]
All is in the title, the loading bar never finishes, and eventualy a timeout message is displayed.
The part o nthe computer seems to work fine.

I am on Linux Mint, and I tried chrome and firefox on tablet Samsung Galaxy S6, both behave the same.

**Comment by H-M-H** [comment]
This sounds like a firewall issue. Have you made sure ports 1701 and 9001 are opened for TCP?

**Comment by deniskup** [comment]
Ah no, how can I do that ? Is that on the tablet or PC ?

**Comment by H-M-H** [comment]
You might have ufw installed. You can check that by running `ufw status`. If it indeed is installed you can open the ports in question using `ufw allow 1701/tcp` and `ufw allow 9001/tcp`. If that is not the case you can directly check if `iptables -L` reports anything.

**Comment by deniskup** [comment]
Thanks, I got to the "settings" page. Not sure what to do from there though... The ultimate goal is to use this for bigbluebutton, I don't find a page explaining how to interface it with some particular software (like gimp).

**Comment by H-M-H** [comment]
Your screen should immediately be mirrored to your tablet. In the settings you can select to only mirror a specific window or monitor. Basically Weylus just simulates an input device and can be used with any application that accepts touch inputs. Xournal++ is such an application for example.

**Comment by deniskup** [comment]
I dont see the screen mirrored in the tablet

I'm getting an error in Weylus: 
ERROR Failed to create uinput device: CError: code: 1 message: error: UI_ABS_SETUP, code: 0

**Comment by H-M-H** [comment]
Please read the Readme, there is a section on how to setup the uinput system. This is necessary in order to properly simulate touch events.

**Comment by deniskup** [comment]
I had done this but did the undo bit in between. 
After redoing it, I have no longer an error message in Weylus, but it still does not work. I don't get a mirrored image of my computer on the webpage, just a blank page and Settings.

**Comment by deniskup** [comment]
So with Firefox it's a bit better, the capture list is not empty but has te actual list of open applications on my computer.
However, when I try to mirrror one, including Xournal++, I get an error "Failed to create uinput device!"
And on the terminal of my computer, still "ERROR weylus::websocket: Failed to create uinput device: CError: code: 1 message: error: UI_ABS_SETUP, code: 0"

I did the steps from the readme to set up uinput, is there a way to check they took effect as desired ?

**Comment by H-M-H** [comment]
Yes, this looks fine. Did you log out and in again? The commands in the readme create a new group uinput and you need to log out and in again for that to take effect.

**Comment by deniskup** [comment]
Yes I did, even rebooted, and then upgraded to Linux Mint 19 (I was afraid old versions of the libraries were the cause), the problem is still there.

**Comment by deniskup** [comment]
The error might have come from running another software with some goal before, without success: https://github.com/rfc2822/GfxTablet/blob/master/driver-uinput/networktablet.c

When I run it, I get an error : UI_ABS_SETUP ABS_X: Invalid argument

Maybe it messed up this UI_ABS_SETUP parameter ? In any case both programs agree that there is something wrong with this UI_ABS_SETUP value, is there a way to reset it ?

**Comment by H-M-H** [comment]
Hmm, on which kernel does your system run `uname -a`?

**Comment by deniskup** [comment]
I just updated to the last kernel (Linux denis-hp 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
) and I finally don't get this error message, but there are still big problems:
-it makes the wifi connection go off and on every 5 seconds
-for the few seconds when xournal++ appears on the tablet (before the next disconnect), the pen does not work anyway

**Comment by H-M-H** [comment]
Hmm, not much I can do about your WiFi, you can try to increase the update interval in the settings to reduce the required bandwidth. Alternatively you could try to set up a peer to peer connection between your tablet and computer via USB tethering.
About Xournal++: You might need to play around with the input settings first.

**Comment by H-M-H** [comment]
Closing this as the original issue has been resolved.
