### ISSUE TITLE
Use this as a second monitor?

### ISSUE THREAD

**Issue by chabad360** [H-M-H/Weylus#5]
Would it be possible to use make this send the output of a virtual monitor (a la what you can do with vnc)? I've been looking for something that can do that well, and vnc leaves what to be desired.

**Comment by H-M-H** [comment]
I think this is nearly possible already. Looking at https://github.com/kbumsik/VirtScreen (which might also interest you) all one needs to do is to create a virtual screen using xrandr: https://github.com/kbumsik/VirtScreen/blob/master/virtscreen/xrandr.py . Weylus then only needs a way to identify it so it can be selected like a window.
If you get a virtual screen working it looks like Xrandr can be queried for its coordinates. Report back in case you have any luck with this, then this could be added as another section in the Readme.

**Comment by chabad360** [comment]
Ok, so I guess the question is, how do I tell Weylus which coordinates to use? Do I just scroll to the right?

**Comment by H-M-H** [comment]
I think it is possible to do the xrandr stuff via Weylus.  But I am not sure how to properly add virtual output devices and it seems they are not available on all distributions, see https://github.com/kbumsik/VirtScreen/issues/16 .
> Ok, so I guess the question is, how do I tell Weylus which coordinates to use?

Exactly, right now this is probably not possible as the extended screen is not listed as separate window to capture. If you got the virtual screen working, can you tell me if capturing a window and dragging it to the virtual screen works. If that is the case I can indeed just query xrandr for screen coordinates and add screens to the window list.

**Comment by chabad360** [comment]
Alright, so it worked, kinda. This gets a bit weird so I'm going to make a nice list of what worked:

| View | Second Monitor | Worked |
| :----- | :--------------------- | :--------: |
| `Screen - 0` | N/A | Yes |
| `Desktop` | N/A | Yes |
| `Browser` | N/A | Yes |
| `Screen - 0` | `1920x1200` (Tablet Screen Size) | No |
| `Desktop` | `1920x1200` | No |
| `Browser` | `1920x1200` | Yes |
| `Screen - 0` | `1920x1080` (Monitor Screen Size) | Yes (but showed both displays) |
| `Desktop` | `1920x1080` | Yes (but showed both displays) |
| `Browser` | `1920x1080` | Yes |

This would be fine, except input doesn't want to work on remote (did the `uinput` stuff), and strangest of all, every thing works if I open up `localhost:1701` in my browser: I see the second display (only), I can use input...

I.e. Something's not right...

**Comment by H-M-H** [comment]
Thanks for the detailed report, it seems I have some work to do if the second monitor does not match the first one in size. I guess I will try to get a virtual screen working on my machine.

Regarding firefox mobile: You could try firefox beta, this is more likely to work.

**Comment by chabad360** [comment]
I think an easy way to do it would be like `x11vnc`, where you can specify a portion of the screen to show with `-clip`.

**Comment by chabad360** [comment]
> Does sudo libinput debug-events report any problems?

Nope, and in the mean time my inputs are all wanky...

> Maybe this works for you.

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  43 ()
  Value in failed request:  0x380
  Serial number of failed request:  38
  Current serial number in output stream:  39
```

and even then Weylus wants to be blank...

**Comment by H-M-H** [comment]
I am running out of ideas, I just tested creating a proper virtual display like you did (as describe for example here https://wiki.archlinux.org/index.php/Extreme_Multihead#VNC) and everything works fine on my machine.

**Comment by chabad360** [comment]
So after a bit more tweaking, I've managed to get it working without virtual devices, but it's practically unusable if I cant see my mouse...

**Comment by chabad360** [comment]
Also, keep in mind that this is only an issue with the stylus/pen support enabled...

I guess I can live without it... But I am unable to effectively work without having the mouse.

**Comment by H-M-H** [comment]
I see, I just never considered using Weylus as another screen but this is a valid point. Unfortunately capturing the cursor seems _a bit cumbersome_, apparently one is supposed to query the cursor position and image with `XFixesGetCursorImage` and draw it onto the screenshot one already took.

**Comment by chabad360** [comment]
Should that be a separate issue then (also the view is a bit squished, but only due to lack of fullscreen ability)?

**Comment by H-M-H** [comment]
A separate issue is probably better, there is already enough going on here.

About the lack of full-screen:  add a bookmark to your home screen and open Weylus from there, this should enable (except for the status bar) full-screen.
