### ISSUE TITLE
Create a postinstall script in the .deb package

### ISSUE THREAD

**Issue by apandada1** [H-M-H/Weylus#50]
It would be great if a postinstall script in the .deb package automatically configures Weylus by entering the commands in https://github.com/H-M-H/Weylus#linux, and prints a message like "restart your computer and enter the command weylus to start using Weylus"
Not every computer can use hardware accelerations, so those commands does not need to be executed by default in the postinstall script.

This can also be done in the AUR.

**Comment by H-M-H** [comment]
I agree, this would convenient. But there are two things that keep me from doing it:

- I don't want to break existing configurations, that is something else might be using uinput already and by changing the permission Weylus might break it.
- If Weylus is installed via package manager, how is the install script supposed to know which user should be granted the privileges for uinput?

**Comment by apandada1** [comment]
>     * If Weylus is installed via package manager, how is the install script supposed to know which user should be granted the privileges for uinput?
Maybe the user who installs the package? If another user wants to use then they would have install again.
Or, add all users - I can't say if that would be a major security issue, because non-administrator users won't have root access anyway.

**Comment by H-M-H** [comment]
The problem with uinput is that if you have access to it you can emulate a keyboard for example. And if another user logs in this is indeed is a security issue. I think the best I can do is to print the required commands for uinput during installation. What do you think about that?

**Comment by apandada1** [comment]
Yes, that would be a good idea, but the user might miss that they use GUI to install the .deb file.

How about creating a bash script which will fetch the .deb file with wget, install it, and run all these commands one by one (instead of using a postinstall script in the .deb file)? The user will use it at their own risk, so you won't have to worry about the security issues.

It can print that it will add the current user to this group, and there may be security issues if there are multiple accounts. Then the user will have to press `y` to proceed.

**Comment by H-M-H** [comment]
I supposed I could also have Weylus display a message if uinput is not writable. That message could give you the commands to setup uinput.

**Comment by apandada1** [comment]
That is also a good idea
