### ISSUE TITLE
VA-API not working by default

### ISSUE THREAD

**Issue by nilshellerhoff** [H-M-H/Weylus#51]
First of all thanks for the awesome software!

My Laptop is a rather old Thinkpad T440s with an Intel i5 4300U and HD Graphics 4400. VA-API doesn't work out of the box as it seems, only the `/usr/lib/dri` directory is searched for the driver. But on my install (Linux Mint 19.3 based on Ubuntu 18.04) the driver was located in `/usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so`. I was able to solve the problem by creating a symlink by executing `sudo mkdir /usr/lib/dri` and `sudo ln -s /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so /usr/lib/dri`.

Should I create a pull request and add this information to the README?

**Comment by H-M-H** [comment]
Thanks for the report! Actually Weylus itself never specifies the search directory but relies on ffmpeg and in turn on libva. The path for libva to search for drivers can be overridden by setting `LIBVA_DRIVERS_PATH`. I will add a section to the Readme.

**Comment by H-M-H** [comment]
I have updated the Readme.
