### ISSUE TITLE
Using Bluetooth instead of wifi?

### ISSUE THREAD

**Issue by mquinson** [H-M-H/Weylus#52]
Hello,

I would like to use Weylus in a room that has only a wired connection, so it'd be great if it were possible to use bluetooth instead of regular TCP/UDP communications.

I tried to setup an IP over bluetooth connexion to reach this end (using only open-source softwares), but failed. Maybe all I need is a link in the doc to the right tutorial?

Thanks for this great software,
Mt

**Comment by H-M-H** [comment]
Hello,

I wouldn't recommend Bluetooth for this as it tends to be too slow for video streaming. Instead you can try to create a WiFi hotspot or have a look at USB tethering. Like that you should be able to setup a peer to peer connection.

**Comment by mquinson** [comment]
I've found a good solution for my setting. I opened a wifi network in hotspot mode on the computer that has a wired connection, and this allows to use my device on that wifi network.

That's still slow (maybe one sec delay when writing in xournal), but at least it works so I guess that this is enough to close that bug. I'm not closing it myself because you may want to add a hint in the doc about this. Feel free to close without the additional documentation, since that's not really related to weylus.

Thanks for this software,

**Comment by H-M-H** [comment]
> one sec delay when writing in xournal

This seems too slow, I have just fixed an issue with some browsers, please try if the latest build of Weylus is faster: https://github.com/H-M-H/Weylus/suites/1610746727/artifacts/29483847

**Comment by H-M-H** [comment]
> you may want to add a hint in the doc about this

I added a section to the FAQ to point people at creating a hotspot and usb tethering. Closing.
