### ISSUE TITLE
ERROR Failed to create uinput device: CError: code: 1 message: error: failed to open /dev/uinput

### ISSUE THREAD

**Issue by jiy352** [H-M-H/Weylus#54]
Hi, I am trying to use this with Linux and Ipad. The error message is shown as the title. Just wondering what this means, and how to debug this. Here is how I set the Access code and etc.
![image](https://user-images.githubusercontent.com/45738410/100315165-05317480-2f6d-11eb-8f2e-1e639fa0ac3e.png)

First, I installed the package with .deb file, and then, I did 
```
sudo groupadd -r uinput
sudo usermod -aG uinput $USER
echo 'KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"' \
| sudo tee /etc/udev/rules.d/60-weylus.rules
```
and 
```
sudo udevadm control --reload
sudo udevadm trigger
```

**Comment by jiy352** [comment]
both firefox and safari on iPad get the same error.

**Comment by H-M-H** [comment]
Hmm, the FAQ didn't help either?

> Q: Why do I get the error ERROR Failed to create uinput device: CError: code...?
> A: uinput is probably misconfigured, have you made sure to follow all instructions and logged out and in again? You may also be running a very old kernel that does not support the required features. In that case try to upgrade your system or use a newer one.

What does `ls -l /dev/uinput` and `groups` say?

**Comment by H-M-H** [comment]
In case you still have problems, feel free to reopen this issue.

**Comment by alexcoder04** [comment]
Hello, I am experiencing the same problem.

OS: Artix Linux (OpenRC init system, udevd installed and running, kernel 6.1.6) + iPad
My Linux user is in the uinput group.

Tried Safari, Brave and Chrome; neither of those seem to work.
