### ISSUE TITLE
BUilt Docker image... not sure what to do next

### ISSUE THREAD

**Issue by kelsonengineering** [H-M-H/Weylus#55]
Hi. Long-time Linux user, Docker newbie. I'm running Solus, and there's no pre-built executable. My son recommended using the Docker version. I ran the command and docker ground things up for a bit and I got a root bash shell in the docker image. Now what? Can I set this up to run on my computer at startup? How do I do the uinput settings?

I'm just not sure what happens next.

Thanks in advance!
Vic

**Comment by H-M-H** [comment]
The docker image is just meant for building Weylus in a controlled environment with all dependencies properly installed. I have no idea if running Weylus inside a docker container actually works, i.e. if you can pass through uinput and X11 somehow. I don't think this can be done as it basically means breaking all isolation docker provides.

As far as I can tell the binary included in the [linux.zip](https://github.com/H-M-H/Weylus/releases/download/v0.9.1/linux.zip) on the releases page should run, provided all required shared libraries are installed (you can check with `ldd weylus`).
