### ISSUE TITLE
Capture dropdown empty on Chrome/Opera

### ISSUE THREAD

**Issue by Zireael07** [H-M-H/Weylus#58]
(I checked that the websocket is open by using a different device - it is)

As the title says. Samsung Galaxy Tab 2, Chrome 42.0. and Opera 50.6. (Apparently neither Safari nor Firefox are available on the device).

**Comment by H-M-H** [comment]
Please try to update your browsers, I am not surprised Weylus doesn't run on Chrome from 5 years ago. You may also want to try the latest build, it can be found at the actions tab and prints more debug information.

**Comment by Zireael07** [comment]
I cannot update the browser on the device, unfortunately. I literally installed Chrome an hour ago and Google Play and Settings both say no updates available - I am guessing this is due to the fact that the device only runs Android 4.4.2.

**Comment by H-M-H** [comment]
That's unfortunate, if you can't get a more recent version to work, Weylus won't run either. Perhaps you can install a recent browser directly via apk but I suspect this won't work either as Android 4 is really old.

**Comment by Zireael07** [comment]
All right, that is understandable, closing (I managed to connect the tablet with https://github.com/rfc2822/GfxTablet instead), but you might want to add some note on lowest browser versions required in case some more people inherit old devices and run into the same issue :)

**Comment by H-M-H** [comment]
> might want to add some note on lowest browser versions required

I'd like to do that but to be honest, I don't really know myself and it doesn't seem easy to figure that out... That's why in the Readme it says somewhat vaguely "modern browser".

But I am glad you got at least GfxTablet working!
