### ISSUE TITLE
Doesn't really work on macOS Big Sur

### ISSUE THREAD

**Issue by coughingmouse** [H-M-H/Weylus#59]
Not really, 言う通り。

**Comment by H-M-H** [comment]
Unfortunately I can't test this myself and as of now Weylus is primarily targeted at Linux. I keep the MacOS and Windows version around in the hope that someone will improve those with their respective native APIs. Perhaps you would like to contribute? If there is a specific problem you have feel free to open another issue, I am closing this as this is not actionable.
