### ISSUE TITLE
Unable to install on Ubuntu 20.04 ,dependency error 

### ISSUE THREAD

**Issue by Afsalmc** [H-M-H/Weylus#6]
Cannot install the Weylus_0.6.1_amd64.deb in Ubuntu 20.04 .
```
Selecting previously unselected package weylus.
(Reading database ... 268289 files and directories currently installed.)
Preparing to unpack Weylus_0.6.1_amd64.deb ...
Unpacking weylus (0.6.1) ...
dpkg: dependency problems prevent configuration of weylus:
 weylus depends on libstdc++6 (>= 10.1.0); however:
  Version of libstdc++6:amd64 on system is 10-20200411-0ubuntu1.
 weylus depends on libgcc-s1 (>= 10.1.0); however:
  Version of libgcc-s1:amd64 on system is 10-20200411-0ubuntu1.
 weylus depends on libssl1.1 (>= 1.1.1g); however:
  Version of libssl1.1:amd64 on system is 1.1.1f-1ubuntu2.

dpkg: error processing package weylus (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 weylus

```

**Comment by Afsalmc** [comment]
Anu Snap/Flatpak release will cut down your work by half . Love your Concept man 💌

**Comment by H-M-H** [comment]
Hmm this is a bit weird as this is built on Ubuntu 18.04 via a GitHub workflow, does the zipped binary work?

**Comment by Afsalmc** [comment]
yes , zipped binary  works perfectly .

**Comment by H-M-H** [comment]
I use cargo-deb to create the .deb and it seems we just hit this issue: https://github.com/mmstick/cargo-deb/issues/118

Specifying dependencies manually might work.

**Comment by Afsalmc** [comment]
oh ! okey , will try with manually specifying dependencies .Hopes this issue will be solved in the your next release .

**Comment by clemisch** [comment]
FWIW, I'm on 18.04 and get

```
$ sudo apt install ./Downloads/Weylus_0.6.1_amd64.deb
[...]
The following packages have unmet dependencies:
 weylus : Depends: libstdc++6 (>= 10.1.0) but 8.4.0-1ubuntu1~18.04 is installed
          Depends: libgcc-s1 (>= 10.1.0) but it is not installable
          Depends: libssl1.1 (>= 1.1.1g) but 1.1.1-1ubuntu2.1~18.04.6 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

PS: Thanks for this project @H-M-H, I have been annoyed by not being able to use my iPad for my Linux laptop for a long time.

**Comment by H-M-H** [comment]
Thanks for your reports, can you try if this version works: [Linux.zip](https://github.com/H-M-H/Weylus/files/4749334/Linux.zip).
The .deb is inside the zip as GitHub wont let me upload it here otherwise...

**Comment by talebi1** [comment]
> Thanks for your reports, can you try if this version works: [Linux.zip](https://github.com/H-M-H/Weylus/files/4749334/Linux.zip).
> The .deb is inside the zip as GitHub wont let me upload it here otherwise...

yes, the .deb inside the linux.zip worked OK on my ubuntu 20.04. thank you
