### ISSUE TITLE
Mobile not working with resolution too high

### ISSUE THREAD

**Issue by cyanpencil** [H-M-H/Weylus#61]
Thank you for developing this awesome project. 

I noticed that when I try to stream high resolutions, streaming on mobile does not work. 
I have a 2k screen + a virtual monitor I set up just like in the README.

If the virtual screen is set up at 1080p, the sharing does not work.
If the virtual screen is set up at 720p, then it works. 

This is not related with virtual screens, as I tried with a normal external monitor and the issue is the same (streaming works only when the external monitor resolution is 720p )

I suspect this is a problem with the mobile, as if I try to access weylus from my laptop in localhost everything works. 

Is there a way to start weylus and force it to stream only the virtual desktop, not the whole desktop combined (which has a too high resolution apparently? ), without going to the client menu and selecting "VIRTUAL1"? 

Thank you for your time.

**Comment by H-M-H** [comment]
I think you are right, the current release of Weylus doesn't really do any scaling and just sends the complete screen at full resolution. Please try the [latest build](https://github.com/H-M-H/Weylus/actions/runs/555586812#artifacts) which scales the video down according to the screen resolution on mobile.

**Comment by bernardelli** [comment]
This build made it work on my crappy tablet :tada:

**Comment by H-M-H** [comment]
Excellent! I will probably do a release soon then.

**Comment by frohro** [comment]
Hi @H-M-H, and @bernardelli,
On my Android tablet and my phone the browser is blank.  I tried it on my Linux machine and I see the screen of the host computer, but on my Android devices it is just white (no matter if I select a window or the whole screen, which is really two screens (1980x2280 total).  Is this my problem too?
Thanks,
Rob
P.S.  Thanks for making such a useful thing.  My classes are online and I need to use a stylus all the time, and my main computer doesn't have one built in.  :-)

**Comment by cyanpencil** [comment]
Yes I confirm the issue looks like it's fixed!

Thank you very much :)
