### ISSUE TITLE
ERROR weylus::websocket: Failed binding to socket: Cannot assign requested address (os error 99)

### ISSUE THREAD

**Issue by jjlarkin** [H-M-H/Weylus#64]
Hi Thank you for making this really looking forward to using it

I keep getting this error when starting weylus

ERROR weylus::websocket: Failed binding to socket: Cannot assign requested address (os error 99)
thread '' panicked at 'error binding to 192.168.1.59:1701: error creating server listener: Cannot assign requested address (os error 99)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/server/mod.rs:124:13
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

I have seen the related questions but I am not sure what I am doing wrong
-----------------
Also a network issue :(

**Comment by H-M-H** [comment]
Weylus tries to bind to all IP addresses available by default but it seems this has gone wrong. What does `ip a` output? Try replacing the bind address field with one of these and check if that works.

**Comment by jjlarkin** [comment]
> Weylus tries to bind to all IP addresses available by default but it seems this has gone wrong. What does `ip a` output? Try replacing the bind address field with one of these and check if that works.

Yes I ended up changing to one of those IP addresses - I was not understanding what to put in the bind field and was using the computer address

Thanks again :)

**Comment by uzielweb** [comment]
How can I change the Bind Adress in Windows app?

**Comment by H-M-H** [comment]
If it does not work via gui, start Weylus via cmd.exe: `.\weylus.exe --bind-address 0.0.0.0`.
