### ISSUE TITLE
[question] Is it possible to mirror my tablet screen onto my laptop?

### ISSUE THREAD

**Issue by kirk86** [H-M-H/Weylus#65]
Hi and thanks for sharing this excellent project,
I saw in the properties of weylus highlighted that is possible to mirror the laptop screen on the tablet, I was wondering if the opposite is possible as well, meaning mirroring my tablet screen on my laptop?

I have an old ipad 2 2011 and I would like to share/mirror the ipad's screen on my macbook while video-conferencing is that possible with Weylus?

Thanks!

**Comment by H-M-H** [comment]
Hello @kirk86 sharing the screen of the tablet is not possible with Weylus and it also won't be in future. I have heard you can mirror your iPad's screen to a mac using QuickTime, you may want to try that instead but I don't know if your iPad is recent enough for that.

**Comment by kirk86** [comment]
Hi @H-M-H  thanks for the reply

> I don't know if your iPad is recent enough for that.

That's the whole point basically my ipad is old (2011), so no quicktime or sidecar will work, that's why I was initially asking.
