### ISSUE TITLE
mouse courser won't move to virtual screen from primary.

### ISSUE THREAD

**Issue by Benjoban** [H-M-H/Weylus#67]
ubuntu 20.04 dell laptop
The courser gets stuck on the primary screen, I can see the courser on the edge of the second virtual screen where they meet and I can move app windows just about until the courser gets stuck.

all inputs unavailable on iPad pro 12.9 1st gen when the browser is in the virtual1 option from the drop-down menu but work in any other screen or app window is selected.

Had to use /usr/share/X11/xorg.conf.d/30-virtscreen.conf
Section "Device"
	Identifier "nvidiagpu0"
	Driver     "nvidia" 
EndSection

Section "Device"
	Identifier "intelgpu0"
	Driver     "intel"
	# THIS DOSE NOT WORK Option "VirtualHeads" "2"  Ubuntu 20.04 and doesn't work.
EndSection

**Comment by H-M-H** [comment]
Hmm, what's the output of `xrandr`? If I understand things correctly you can't move windows from one to another screen, unrelated to using Weylus. If the VirtualHeads option doesn't work for you I am not exactly sure how this setup even works.

**Comment by Benjoban** [comment]
The screen displays the second screen virtual screen works but the mouse cursor won't move across to that second screen I'll send more info tomorrow thanks for you quick response. BenOn 6 Mar 2021 18:36, HMH <notifications@github.com> wrote:
Hmm, what's the output of xrandr? If I understand things correctly you can't move windows from one to another screen, unrelated to using Weylus. If the VirtualHeads option doesn't work for you I am not exactly sure how this setup even works.

**Comment by H-M-H** [comment]
Closing this for now, feel free to reopen this issue if you still have this problem.
