### ISSUE TITLE
Keyboard support?

### ISSUE THREAD

**Issue by meermanr** [H-M-H/Weylus#69]
I realise that Weylus's goal is to allow the use of a tablet / phone for stylus and touch inputs, but I was wondering if it can be extended to also allow sending keyboard input?

In my case, I want to use a MacBook Air (which has no fans) + Wacom tablet to drive a noisy/powerful desktop in another room. For example, to do sculpting or 2D animation work in Blender. Essentially VNC style app with pen pressure support - Weylus is _so nearly_ this!

**Comment by H-M-H** [comment]
Interesting use case! I definitely see how this would be useful. Sending and simulating key input shouldn't be much of a problem. But the thing that is probably going to be a **huge problem** is getting the mapping from browser keyboard events to the corresponding ones on the computer right.

For reference, this is what I am talking about:
[KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values) --> [Linux Input event codes](https://github.com/torvalds/linux/blob/f296bfd5cd04cbb49b8fc9585adc280ab2b58624/include/uapi/linux/input-event-codes.h#L75-L338) / [autopilot](https://github.com/autopilot-rs/autopilot-rs/blob/master/src/key.rs)

Additionally modifier keys need to be taken into account and even worse, I don't know how to handle localization. Some first look at `KeyboardEvent.code` fired in the browser suggests that for quite some keys the code is left undefined (on my keyboard for example for umlauts: `äöü`) and instead only `KeyboardEvent.key` containing the corresponding unicodepoint is defined. Unfortunately the uinput module on linux is designed to simulate physical key events and can not simulate sending arbitrary unicode.

I am not opposed to adding this but getting it right is probably going to be a lot of work.

**Comment by H-M-H** [comment]
Alright, some very basic keyboard handling (only via uinput for now) is implemented in the [keyboard branch](https://github.com/H-M-H/Weylus/tree/keyboard), a build to test can be found here: https://github.com/H-M-H/Weylus/actions/runs/652127605

So far I only added some obvious key mappings but this still needs more work:
https://github.com/H-M-H/Weylus/blob/2d5eeccff8c0082973b53fee6443ca8330078c88/src/input/uinput_device.rs#L509-L623

Keyboard events look like this:
https://github.com/H-M-H/Weylus/blob/2d5eeccff8c0082973b53fee6443ca8330078c88/src/protocol.rs#L107-L117

Feel free to do some experiments yourself!

**Comment by meermanr** [comment]
Fantastic thanks! This seems to support all the keys I expect I'd need for something like Blender, but in my testing with a Linux server (and a MacOS + Google Chrome client if it matters).

However, it seems to send keys in "bursts". Using `xev` to watch the keystrokes and typing  keys one at a time across my top row (QWERTY) it seems to send "q" and then nothing until I get to about "t" when it sends "w"+"e"+"r"+"t" events all at once.

I can't quite see why it would be doing that, I wonder if events are only sent when there are touch/mouse/stylus events to push, or a buffer gets full?

**Comment by H-M-H** [comment]
I simply forgot adding synchronization events, this should work now: https://github.com/H-M-H/Weylus/actions/runs/653880224

**Comment by meermanr** [comment]
Hi - that build works _much_ better! I can type commands into a terminal window and it feels very responsive.

I found, however, that modifier keys don't work, such as holding SHIFT to type in a capital letter, or Alt+S to trigger a shortcut.

**Comment by H-M-H** [comment]
Please try again with the latest build, I improved a few more things.

If you (or someone else) want(s) to help, have a look at the event codes I mentioned earlier: https://github.com/H-M-H/Weylus/issues/69#issuecomment-798505022 and complete the mapping function here:
https://github.com/H-M-H/Weylus/blob/8908a601bb5f31e996e5533e8b3cbfd69faebf55/src/input/uinput_device.rs#L563

For debugging purposes run Weylus via `WEYLUS_LOG_LEVEL=TRACE ./weylus`, this will print additional debug information about which keyevents were received and if a mapping has been found.

**Comment by H-M-H** [comment]
Mapping browser keyboard input to uinput on Linux is pretty much complete by now. The autopilot backend needs more testing.
