### ISSUE TITLE
All lines are connected when using MyPaint on Manjaro (other apps work properly)

### ISSUE THREAD

**Issue by offray** [H-M-H/Weylus#70]
First thanks for Weylus. It's pretty awesome! And is so good to see a software that is easy to install, easy to use, well documented and that has good error mensajes that guide you to the setup process (as in my case trying to enable pressure sensitivity from my Galaxy Tab S 10). This project is something I have daydreamed of, kind in the same way you implemented: sharing a X server via intranet and making the tablet a "mirror" of the screen providing pen input. But you made it real and better! This has been the quickest star in my personal history using GitHub and feels not enough... Just let me know if you need a Spanish translation for the Readme.

After the inevitable praising, this is my concrete issue. When I use [MyPaint](http://mypaint.org/about/) on Manjaro Linux,
the lines are all conected, like if Weylus or the MyPatint were not able to tell/detect that the pen has been pulled of the tablet screen. When I use other graphical apps, like Gimp or Krita lines are properly drawn. See these two images for reference (first using Weylus + Krita and the second Weylus + MyPaint):

![Weylus + Krita](https://user-images.githubusercontent.com/5748170/111715914-ebb97e80-8822-11eb-9442-13888d9c4e74.png)
![Weylus + MyPaint](https://user-images.githubusercontent.com/5748170/111715980-0db30100-8823-11eb-8b51-ea9430e618a9.png)

For quick notes and workshops I think that the infinite canvas of MyPaint is better suited that the finite one of most graphical apps. There is any workaround or bug fix to be applied to get MyPaint + Weylus properly working?

Thanks again for such great project.

**Comment by H-M-H** [comment]
Thank you for your kind words, it always makes me happy to hear that someone is enjoying my software!

Unfortunately it looks like this is a bug on MyPaint's side:
- https://github.com/mypaint/mypaint/issues/1096
- https://github.com/mypaint/mypaint/issues/586
- https://github.com/mypaint/mypaint/issues/867

From what I have gathered MyPaint relies a little too much on the pressure of the input events and it seems the additional events Weylus fires, that indicate that the pen is not touching the tablet anymore, are more or less ignored by MyPaint. Depending on the pen you use it is however very much possible that the pressure the browser detects and sends to your computer is not exactly 0 when the pen stops touching the tablet and thus MyPaint gets confused and thinks the pen has not been lifted even though it has.
And this finally leads to wrongly connected strokes as MyPaint considers the pen touching the tablet somewhere else again as the continuation of the current stroke.

The first issue in that list recommends adjusting the pressure curve as workaround:
![curve](https://user-images.githubusercontent.com/5107852/88845729-dedd1180-d1e4-11ea-94a8-cef3d06ce35a.png)

**Comment by H-M-H** [comment]
Closing this for now as MyPaint is the culprit.

**Comment by offray** [comment]
Thanks a lot. Haven't had the time to test the MyPaint part of the bugfix, but  I agree with closing the issue.
