### ISSUE TITLE
Step-by-step instructions for USB tethering

### ISSUE THREAD

**Issue by raffaem** [H-M-H/Weylus#71]
Are there Step-by-step instructions for USB tethering?

In the README it's only mentioned

**Comment by raffaem** [comment]
I did it!

1. Connect tablet
2. Mode "File sharing"
3. Activate USB debugging
4. Make sure tablet is visible by `adb devices -l`
5. Rever the ports of webserver and websocket
```
adb reverse tcp:1701 tcp:1701
adb reverse tcp:9001 tcp:9001
```
6. Run Weylus and start server
7. Connect your tablet to `localhost:1701`. __Don't use an IP address__. Only `localhost` will work. Ignore all the IP addresses that Weylus throws at you.
8. 
Enjoy!

**Comment by H-M-H** [comment]
Ohh, this solution is actually kinda cool! USB tethering is something different though and you should be able to find it in your settings under hotspot and tethering. Under normal circumstances tethering is used to share mobile data from your smartphone with another device and to do so it creates a peer to peer connection to said device. Weylus can also use this connection then.

**Comment by raffaem** [comment]
Do you mean something like [this guide](https://www.howtogeek.com/170302/the-htg-guide-to-tethering-your-android-phone/) under the heading "USB tethering"?

I followed those instructions but still was unable to connect the tablet to Weylus. It gies me ERR_ADDRESS_UNREACHABLE

**Comment by H-M-H** [comment]
Yes, this is what I meant. The address Weylus displays in this case may be incorrect though as tethering adds another ip address to your computer (I think with android tethering it's something like 192.168.42.xxx) and that's the one you need to put into your browser.

**Comment by raffaem** [comment]
How can I find the right IP address?

The settings display an IP address of 10.XXX.XXX.XXX

**Comment by H-M-H** [comment]
`ip a` displays the ip addresses of your computer and their interfaces. There should be an interface suspiciously looking like usb tethering.

**Comment by raffaem** [comment]
`ip a` output:

```
8: usb0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 56:f1:91:7b:7a:e6 brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.1/24 brd 10.42.0.255 scope global noprefixroute usb0
       valid_lft forever preferred_lft forever
    inet6 fe80::b4e3:104e:acff:9c03/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

`10.42.0.1` is the same IP displayed by Weylus under
> INFO other urls are:
But connecting to `10.42.0.1:1701` doesn't work (ERR_ADDRESS_UNREACHABLE) and connecting to `localhost:1701` returns `ERR_CONNECTION_REFUSED`

**Comment by H-M-H** [comment]
Hmm, this is a bit weird, I guess this needs some more investigation but I am not too sure what to check now.

**Comment by H-M-H** [comment]
I tested this with my device again and it works just fine. So I am not sure what's wrong with your setup. But as this is not really an issue about Weylus itself, I am closing this. I will probably add some instructions to the readme on how to setup a connection with adb though.

**Comment by zsunberg** [comment]
Note there are instructions here: https://askubuntu.com/questions/1325074/setup-weylus-using-usb-tethering
