### ISSUE TITLE
[BUG] Firefox on the Android tablet doesn't convert pen pressure into mouse button events

### ISSUE THREAD

**Issue by raffaem** [H-M-H/Weylus#74]
The behavior of Weylus changes if you use Google Chrome or Firefox on the Android tablet.

If you use Google Chrome, touching the tablet with the pen issue a mouse button event. This allows you to write on Xournal++.

It you use Firefox, touching the tablet with the pen _does not_ issue mouse button events. This _prevents_ you from writing in Xournal++. If you use Firefox, you are only able to scroll the page in Xournal++ but not to write on it.

You can check the type of events issued by running `xinput test-xi2 --root | grep "EVENT type"`

**Comment by H-M-H** [comment]
Thanks for the report! Sadly Firefox on Android doesn't implement the pointertype pen and just reports a normal touch event, see https://github.com/H-M-H/Weylus/issues/66#issuecomment-799006598

This means Weylus will only be able to simulate touch events on the computer even though you are using a pen. Chrome does this better and pen events are properly reported. If you want to keep using Firefox you can configure Xournal++ to accept touch input for drawing.

**Comment by H-M-H** [comment]
There isn't really anything I can do about it here, so I am closing this.
