### ISSUE TITLE
Does not work with my triple-monitor setup

### ISSUE THREAD

**Issue by NicoWeio** [H-M-H/Weylus#78]
I "used" the latest version of Weylus on Linux Mint and Manjaro, but would always get a blank screen along with error messages like 
`Uncaught TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.  at WebSocket.webSocket.onmessage (lib.js:312)`. Switching to another _Capture_, increasing the _Frame interval_ (btw, it was on **0** by default, which I found rather confusing) or experimenting with the other checkboxes did not improve anything.

Meanwhile, Weylus worked on my Manjaro laptop. 
Indeed, I found that disabling two of my monitors resulted in Weylus working on my PC as well. 

A suspicious log line that appears with all monitors enabled reads: 
`[libx264 @ 0x7f48fc001a80] MB rate (22440000) > level limit (16711680)`.

I do not know much about the inner workings of Weylus, but I think error-handling could be improved here. I would be okay with not being able to stream my complete desktop, but upon changing the _Capture_ to a (smaller) window, Weylus should work again, while currently, it's just stuck somehow.

**Comment by H-M-H** [comment]
Thanks for the report! This looks very much like a problem with the video resolution. Please check if you can get things working with the latest build: https://github.com/H-M-H/Weylus/actions/runs/714287278#artifacts

> Frame interval (btw, it was on 0 by default, which I found rather confusing)

I guess I should explain this a little better. Weylus has very fine grained control over the video frame rate and this setting controls the minimum interval between two video frames. This can be used to throttle the frame rate to reduce CPU load for example. The default has been changed to 16ms.

**Comment by NicoWeio** [comment]
Thanks for the quick response! 
I tried the latest build, but while the new version does log `Failed to seek to end of video`, switching from my large desktop (selected by default) to a window does not do anything to the blank screen. 

No idea why I didn't mention this earlier, but I played around with Chrome's DevTools and found some things that _might_ help: 
- mediaSource.readyState is `"closed"` after some time / the error
- `video.seekable.length` seems to be always `0`
- I also get this sometimes: `ERROR: Failed to obtain resource, target: [object HTMLVideoElement] type: error src: blob:http://192.168.2.123:1701/223ae476-ffa4-4c21-8490-bd1e148abfeb Error object: {"isTrusted":true}`

**Comment by H-M-H** [comment]
Hmm, what does the FPS counter display? Does this happen with Firefox too? Does reducing the max video resolution (and possibly reloading the page) help? At what resolution is Weylus encoding the video (displayed in the log).

> ERROR: Failed to obtain resource, target: [object HTMLVideoElement]...

This means that the browser failed to decode the video for some reason. I suspect it happens if the video stream is restarted too rapidly and the browser can't keep up.

**Comment by NicoWeio** [comment]
It works! 🎉 
I am not sure what I did differently this time, but here's what I did:
- open Weylus
- I get a blank screen, but 20-30 fps, while Max Video Resolution is maxed out at 2048x1296
- I lower this setting to 922x583, but still only see a blank screen
- I reload the page, my change of Max Video Resolution persists, and I get an image!
- From there on, I can use Weylus as expected, as long as I don't increase the Max Video Resolution too much. If I did, I would need to reload again.

Regarding your questions: 
- I get 20-30 fps or more, depending on video size.
- I did not try Firefox yet.

**Comment by H-M-H** [comment]
Excellent, the latest version might work even without the user manually reducing the resolution on first start. The problem with better error messages is that the browser only tells us that the video can't be decoded but not why, nonetheless I added some hints as to what to try if such an error occurs.

**Comment by NicoWeio** [comment]
> I added some hints as to what to try if such an error occurs.

For future reference: cc14bf10bc619a746320e1dc3eeffd7dd53c8520

Again, thank you!
