### ISSUE TITLE
[IOS 10.3.3] the "Capture" drop down is empty and the screen is not mirrored.

### ISSUE THREAD

**Issue by Kira060200** [H-M-H/Weylus#79]
On iPad 4 (IOS 10.3.3) the "Capture" drop down is empty and the screen is not mirrored.
I have tried the approach in the FAQ, but still no change. I have tested the app and it works on my android phone.
Browsers that I tried: Safari, Chrome, Edge (Mozilla won't install because it requires IOS 11)
Any chance this might be related to way too old software on my iPad?

**Comment by H-M-H** [comment]
Sadly iOS 10 is indeed just too old. Some features required to make Weylus work are simply not implemented on iOS 10.
