### ISSUE TITLE
Show mouse cursor

### ISSUE THREAD

**Issue by chabad360** [H-M-H/Weylus#8]
As a follow up to #5 it would be a huge plus to have the mouse cursor be visible (optionally) in stream.

**Comment by H-M-H** [comment]
Ok, it is done. Please try if it works for you: https://github.com/H-M-H/Weylus/releases/tag/v0.7.0-rc3

**Comment by chabad360** [comment]
Perfect!

P.s. are there any good ways (other than not using wifi) to decrease latency/increase fps?

**Comment by H-M-H** [comment]
You can always capture a smaller window :P but other than that there is not much you can do right now. I might add hardware encoding some day but this probably requires quite some work.

**Comment by chabad360** [comment]
I wonder if its possible to get the mouse position and instead of adding it to the image, show it in the browser view (would be slightly less CPU heavy just to show the cursor)?

**Comment by H-M-H** [comment]
Just did some benchmarks on how capturing the cursor influences the speed of screen capturing:
- without cursor: `1,269,828 ns/iter (+/- 72,316)`
- with cursor: `1,349,325 ns/iter (+/- 104,926)`

This is a difference of about 0.1 milliseconds and barely measurable, so I do not think it is worth it.

**Comment by chabad360** [comment]
but combined with tweening it could make for a nicer feel, as at least the mouse doesn't feel slow...

**Comment by H-M-H** [comment]
I am not sure I like this, things would get quite a bit more complicated. For example the cursor image can change (normal curser, marking text, ...), how should that be handled? I'd rather focus on improving the latency of video encoding.

**Comment by chabad360** [comment]
Fair enough, although I don't think most (if not any) remote solutions handle that, so it might just not be possible...

**Comment by barkoder** [comment]
First time trying Weylus.

Host: Windows (Weylus v0.11.4)
Client: Android 6.0: Bromite Web Browser

Option to show mouse cursor is no longer visible on client(web browser). This [capture cursor option](https://miro.medium.com/1*FXe4oPdCw0icrdvnWexc6w.webp)(as shown in #193) doesn't seem to exist anymore.

Tried both USB Tethering and Wifi. Please add this option back as I really need it.

Thank you for your work, @H-M-H !
