### ISSUE TITLE
Installation on IPAD

### ISSUE THREAD

**Issue by schulzchristian** [H-M-H/Weylus#80]
Hi,

how do I actually install the app on my ipad pro? After unzipping, the file is not executable, setting it to executeable using chmod a+x Weylus.app doesnt help.

Thanks!
Christian

**Comment by H-M-H** [comment]
There is no app! You only need to install Weylus on your computer. Weylus then acts as web server and you can use Firefox or Safari on your iPad to connect to Weylus. There is no need to install anything on the tablet.

**Comment by schulzchristian** [comment]
Ahhh i see, thx!
