### ISSUE TITLE
Second screen documentation assumes Intel video and Xorg

### ISSUE THREAD

**Issue by jmou** [H-M-H/Weylus#82]
I just wanted to make a note that the "Weylus as Second Screen" documentation has some unstated assumptions that the video driver is intel on Xorg. I think the second screen problem is actually quite complicated unfortunately. While looking for a solution I stumbled upon [this megathread](https://github.com/pavlobu/deskreen/discussions/86) (which is how I actually learned about Weylus!). The other options I saw for Linux are an nvidia Xorg config and using a physical dummy HDMI plug (what I am doing for now). On Wayland it seems it is [possible with sway](https://www.reddit.com/r/swaywm/comments/g3kk8t/wayland_headless_renderers/) and being added to [the next Gnome release](https://www.phoronix.com/scan.php?page=news_item&px=GNOME-40-Headless-Virtual).

I think it would be fine to clarify that the documentation only covers intel on Xorg. But I also wanted to mention the range of possibilities in case you wanted to reorganize to accommodate more configurations.

Really like what you've done and hope to play around with it more! Thanks for working on #3 and #20 also ;)

**Comment by H-M-H** [comment]
I guess you are right. At the moment it only says `if your hardware supports it`. I will clarify that these instructions indeed are only for intel GPUs on Xorg.

> I think the second screen problem is actually quite complicated unfortunately.

You are absolutely right, it is quite a mess!
