### ISSUE TITLE
iPad: window resizing

### ISSUE THREAD

**Issue by ZhenyaHanson** [H-M-H/Weylus#84]
I've noticed that the window in the browser can get weirdly zoomed, and I'm unable to fix it without repeatedly refreshing and occasionally I have to restart weylus. Specifically, the the settings pane, when it's expanded, is something I can pinch on to zoom in and out and to pan, but if the zoom&pan get's moved in such a way that the settings pane if off screen, I cannot return to full zoomout.

**Comment by H-M-H** [comment]
Thanks for the report, when exactly does this happen, only with settings opened?

I disabled pinch zoom for the settings for now, you can try the latest build and check if this already fixes your problems: https://github.com/H-M-H/Weylus/actions/runs/822881033#artifacts

**Comment by ZhenyaHanson** [comment]
Disabling pinch zoom fixed it, it feels very consistent now, I can't quite remember how it happened before but I'll test on the previous build.

I'm wondering if it would be possible to toggle the ability to pinch zoom, and additionally make it so that the settings pane was immune to any zoom on the page. This might be useful to then be able to use the settings pane as a kind of zoom & pan pad, to two finger zoom and pan around the screen from the computer, while keeping the settings pane on the tablet always accessible.

**Comment by H-M-H** [comment]
Excellent!

I think this is a good idea, I will try to implement something similar to it!
