### ISSUE TITLE
Request: stylus hover (iPad)

### ISSUE THREAD

**Issue by ZhenyaHanson** [H-M-H/Weylus#85]
Is it possible to get the stylus hover information, when the apple pencil 2 is close to but not touching the surface, and send it to the computer as a mouse movement without a mouse click?

**Comment by H-M-H** [comment]
Weylus already handles situations like this and it should work just fine. But this is based on the assumption that Safari/Webkit generates PointerEvents if you just hover over the surface (which it should). You can check what PointerEvents the browser generates by running Weylus like this: `WEYLUS_LOG_LEVEL=TRACE weylus`. If you see no events while hovering, consider filing a bugreport at https://bugs.webkit.org.

**Comment by hoamle** [comment]
Would like to report that hover was not working with Apple Pencil 2 and any of the browsers I've tried on my iPad either. Specifically I've tried Safari, Firefox and Opera (all up-to-date) on iOS 14.4.2, connecting to a Ubuntu Weylus server.

It might be worth to note that Windows version of Firefox (x86-64) and Edge (x86-64 and arm64) work as expected though

**Comment by H-M-H** [comment]
Thanks for the report!

> It might be worth to note that Windows version of Firefox (x86-64) and Edge (x86-64 and arm64) work as expected though

What exactly do you mean? Do you have another device with pen input you can test hovering on?

As far as I know it is not possible to support hovering with the Apple Pencil 2 at all at the moment. I may be wrong though, if anyone can find a website/webapp that handles hovering, please point me to it.

**Comment by hoamle** [comment]
> What exactly do you mean? Do you have another device with pen input you can test hovering on?

Yup that was what I meant. I tested pen hovering with Surface pen on a Surface Book and Surface Pro X. Both work correctly with said browsers. Sorry just realized it's not really relevant to this issue

**Comment by H-M-H** [comment]
> Sorry just realized it's not really relevant to this issue

Don't worry, this is actually helpful, as it confirms that Weylus works correctly and Apple is at fault for not implementing hovering properly in Safari/WebKit. Unfortunately all I can do is to recommend filing a bug report here: https://bugs.webkit.org/ or bother Apple's support about implementing this.
