### ISSUE TITLE
Is there a way to just show one monitor output instead of two monitor in tablet display? 

### ISSUE THREAD

**Issue by AlexSeongJu-sr** [H-M-H/Weylus#86]
hi. 
first, thank you for sharing your great work! it is very useful to me. 
Anyway, Is there a way to show just one monitor on my ipad? My laptop is connected to a monitor and ipad is showing 2 monitors. 
I wish I could choose just one monitor to show on ipad display. 
Can I do that? 
thanx.

**Comment by H-M-H** [comment]
Hello! Currently this is only possible on Linux. I assume you are not running Weylus on Linux?

I am considering to add support for pinch-zoom the video, this would probably solve your problem.

**Comment by kregerl** [comment]
I am using Linux, how would I display only one monitor instead of the two split screen?

**Comment by H-M-H** [comment]
You should be able to do that by selecting the screen you want in the browser menu to the right. As long as xrandr recognizes your screens they will appear in said menu.
