### ISSUE TITLE
Access without a web browser

### ISSUE THREAD

**Issue by fabianski7** [H-M-H/Weylus#87]
This may be a stupid question, but is it possible to access streaming directly through any player, such as MPV or VLC?

In this case we would no longer have access to functions such as mouse and keyboard input, but it makes access friendlier for older devices.

At first, it may not make sense to have a second screen in "read only" mode, but it can be used in this way for things like a real-time feedback from an obs studio broadcast, or to read live comments on youtube.

**Comment by H-M-H** [comment]
This is not possible without some extra work. Weylus communicates with the browser via websockets and the protocol used is fairly simple, so it is straight forward to write a client that connects to Weylus and requests a video stream but connecting directly with mpv or vlc won't work.

Can you elaborate on your use case a bit, what is the advantage Weylus gives you over just using some other streaming software?

**Comment by fabianski7** [comment]
> so it is straight forward to write a client that connects to Weylus and requests a video stream

Don't you know of any existing ones that do this?

> Can you elaborate on your use case a bit, what is the advantage Weylus gives you over just using some other streaming software?

Well, I have a potato tablet in my drawer that has a good screen, but it is quite old and has a lousy performance. I only use it to read PDF and watch cartoons because it's the only thing it can do.

Opening a browser is not something it handles very well, and it's on android 4, which has few apps yet compatible.

In short, I think this kind of hardware would benefit from it. But I understand that this is a very specific case. Please feel free to close the issue if this is not something relevant to you.

**Comment by H-M-H** [comment]
> Don't you know of any existing ones that do this?

I do not, but as it is really easy to implement:
```python
#!/usr/bin/env python

import os
import sys
import json
import asyncio
import websockets


async def run(url, password):
    async with websockets.connect(url) as ws:
        await asyncio.wait(
            [
                asyncio.create_task(get_stream(ws, password)),
                asyncio.create_task(handle_messages(ws)),
            ]
        )


async def get_stream(ws, password):
    await ws.send(password)
    await ws.send('"GetCapturableList"')
    cfg = {
        "Config": {
            "uinput_support": False,  # won't ever send input, so this is not required
            "capturable_id": 0,  # 0 is always the desktop
            "capture_cursor": True,
            "max_width": 4096,
            "max_height": 4096,
        }
    }
    await ws.send(json.dumps(cfg))
    while True:
        await ws.send('"TryGetFrame"')
        await asyncio.sleep(0.033)  # 30 fps


async def handle_messages(ws):
    async for msg in ws:
        if isinstance(msg, bytes):
            os.write(1, msg)
        else:
            print(msg, file=sys.stderr)


asyncio.get_event_loop().run_until_complete(run(*sys.argv[1:]))
```
Save this python script as `client.py` and run `./client.py ws://some_address:9001 password | mpv --profile=low-latency --no-cache --untimed -`, this will play the video with mpv. Of course this is no solution for android as you don't have a shell but it demonstrates how to access the video stream.

**Comment by H-M-H** [comment]
Alright, I am closing this then.
