### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by holmesrichards** [H-M-H/Weylus#88]
OS: Linux Mint 20.1 Cinnamon
Weylus: v0.11.1 installed from .deb https://github.com/H-M-H/Weylus/releases/download/v0.11.1/Weylus_0.11.1_amd64.deb
Phone: Android 11
Browser: Chrome 91.0.4472.77

Started Weylus on desktop (with access code set). On my phone, the URL in the QR code did not work but the app said "INFO Found more than one IP address for browsers to connect to," and one of the other two URLs listed there worked. Mousing worked for a few seconds, then seemed to become very laggy. Then log on desktop showed

WARN Could not move mouse: Out of bounds
WARN Could not move mouse: Out of bounds
WARN Could not move mouse: Out of bounds
WARN Error reading message from websocket, closing (WebSocketError: I/O failure)

and on phone, "Connection closed. Reload page?" Reload works, but non responsiveness and lost connection repeats itself.

**Comment by H-M-H** [comment]
This looks like your WiFi connection may be bad. Checkout the the last question of the FAQ to try connecting without WiFi.

To verify the WiFi connection is indeed the culprit, check if everything runs smoothly if you open Weylus in the browser on your computer itself. To reduce the required bandwidth you can alternatively try to disable the video or reduce its resolution.

And finally you can get more detailed logs by running Weylus like this: `WEYLUS_LOG_LEVEL=TRACE weylus`.
