### ISSUE TITLE
[BUG] Crashing on connecting to a MacBook Air M1 having second monitor

### ISSUE THREAD

**Issue by flyinglimao** [H-M-H/Weylus#89]
Hi, thank you for developing this cool tool.

I found that it will crash if I have a second monitor connected. The crash happens after a log `INFO Video: 2560x1600@libx264 pix_fmt: yuv420p`. If I remove the second monitor, it can connect correctly.
I tried to reconnect the monitor after connected. It works sometime but crash in most situations.
For the situations not crashing after reconnect, the `Settings > Capture` have only `Desktop (autopilot), therefore I guess it succeeded because Weylus/Rust not yet detect the second monitor.
I'm using a MacBook Air M1 as server and Firefox 88.0.1 on a Windows 10 Tablet as client.

I'm glad to help.

**Comment by H-M-H** [comment]
Thanks for the report!

Please check if you can produce a backtrace by running Weylus like this: `RUST_BACKTRACE=full WEYLUS_LOG_LEVEL=TRACE ./weylus`. The binary is located at `Weylus.app/Contents/MacOS/weylus`. I suspect the culprit is the library I use for screen capturing on macOS ([autopilot](https://github.com/autopilot-rs/autopilot-rs)). I'd love to replace it with something better but there don't appear to be any better libraries for screen capturing on macOS.

**Comment by flyinglimao** [comment]
[debug.log](https://github.com/H-M-H/Weylus/files/6591300/debug.log)

Here is the log and followed by 
`[1]    22812 segmentation fault  RUST_BACKTRACE=full WEYLUS_LOG_LEVEL=TRACE ./weylus > debug.log 2>&1`

**Comment by H-M-H** [comment]
Unfortunately all this log tells me is that Weylus crashes in some non rust code. I have compiled the [screengrab example](https://github.com/autopilot-rs/autopilot-rs/blob/master/examples/screengrab/src/main.rs) from autopilot for macOS, please check if this crashes as well: https://github.com/H-M-H/autopilot_build/actions/runs/904329516#artifacts

**Comment by flyinglimao** [comment]
> Unfortunately all this log tells me is that Weylus crashes in some non rust code. I have compiled the [screengrab example](https://github.com/autopilot-rs/autopilot-rs/blob/master/examples/screengrab/src/main.rs) from autopilot for macOS, please check if this crashes as well: https://github.com/H-M-H/autopilot_build/actions/runs/904329516#artifacts

It doesn't crash for me and succeeded to take 2 screenshots

**Comment by flyinglimao** [comment]
I tried to build it (master) in my env. It won't crash (both debug and release build) but it seems not forward control (I can see my screen in tablet browser but cannot control from it). Will this info help?

**Comment by H-M-H** [comment]
Awesome, if you can build Weylus yourself, this makes things a lot easier! What is the output of ` RUST_BACKTRACE=full WEYLUS_LOG_LEVEL=TRACE ./weylus` for the debug build?
> but it seems not forward control

Perhaps permission for remote controlling is missing, from my experience the permission system on macOS can be a little wonky at times and double checking is always a good idea.

If you manage to crash Weylus again, try to obtain a backtrace using lldb: `rust-lldb ./weylus`, once lldb is running type `run` to start Weylus and after the crash type `bt` to obtain a backtrace.

**Comment by flyinglimao** [comment]
Log is here: [debug.log](https://github.com/H-M-H/Weylus/files/6597563/debug.log)

The control forwarding problem is solved with granting terminal permission, thanks!

**Comment by H-M-H** [comment]
So the conclusion so far is that the binary from GitHub crashes with another monitor connected but if you build Weylus yourself it runs fine even with another monitor connected?

I just reran the CI pipeline for latest master, perhaps there has been an issue with the build tools from a month ago (I am just speculating now though). Please check if this version crashes too: https://github.com/H-M-H/Weylus/actions/runs/822881033#artifacts

If so, please try to get a backtrace using rust-lldb.

**Comment by flyinglimao** [comment]
> So the conclusion so far is that the binary from GitHub crashes with another monitor connected but if you build Weylus yourself it runs fine even with another monitor connected?  

Yes

> I just reran the CI pipeline for latest master, perhaps there has been an issue with the build tools from a month ago (I am just speculating now though). Please check if this version crashes too: https://github.com/H-M-H/Weylus/actions/runs/822881033#artifacts
>
> If so, please try to get a backtrace using rust-lldb.

Crashed with this build. Log here:
```
(lldb) command script import "/Users/flyinglimao/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/etc/lldb_lookup.py"
(lldb) command source -s 0 '/Users/flyinglimao/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/etc/lldb_commands'
Executing commands in '/Users/flyinglimao/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/etc/lldb_commands'.
(lldb) type synthetic add -l lldb_lookup.synthetic_lookup -x ".*" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)String$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^&str$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^&\\[.+\\]$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(std::ffi::([a-z_]+::)+)OsString$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)Vec<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)VecDeque<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)BTreeSet<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)BTreeMap<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(std::collections::([a-z_]+::)+)HashMap<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(std::collections::([a-z_]+::)+)HashSet<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)Rc<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)Arc<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)Cell<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)Ref<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)RefMut<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)RefCell<.+>$" --category Rust
(lldb) type category enable Rust
(lldb) target create "./weylus"
Current executable set to '/Users/flyinglimao/Downloads/Weylus.app/Contents/MacOS/weylus' (x86_64).
(lldb) run
Process 19654 launched: '/Users/flyinglimao/Downloads/Weylus.app/Contents/MacOS/weylus' (x86_64)
2021-06-05 00:32:00.693610+0800 weylus[19654:380311] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=19654
2021-06-05 00:32:00.694156+0800 weylus[19654:380311] SecTaskCopyDebugDescription: weylus[19654]/0#-1 LF=0
Jun 05 00:32:02.388  INFO weylus::web: Webserver listening at 0.0.0.0:1701...
Jun 05 00:32:06.808  INFO weylus::web: Web-Client authenticated: 192.168.43.252:53132.
Jun 05 00:32:06.808  INFO weylus::web: Client connected: 192.168.43.252:53132
Jun 05 00:32:07.865  INFO weylus::websocket: WS-Client authenticated: 192.168.43.252:53134!
[libx264 @ 0x10c866200] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
[libx264 @ 0x10c866200] profile Constrained Baseline, level 6.2, 4:2:0, 8-bit
[libx264 @ 0x10c866200] 264 - core 161 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=8 lookahead_threads=8 sliced_threads=1 slices=8 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=12 keyint_min=1 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to '(null)':
  Stream #0:0: Video: h264, yuv420p, 2560x1600, q=2-31
Jun 05 00:32:08.102  INFO weylus::log: Video: 2560x1600@libx264 pix_fmt: yuv420p
Process 19654 stopped
* thread #6, stop reason = EXC_BAD_ACCESS (code=1, address=0x1459f5000)
    frame #0: 0x0000000100fd20c5 weylus`___lldb_unnamed_symbol4668$$weylus + 4
weylus`___lldb_unnamed_symbol4668$$weylus:
->  0x100fd20c5 <+4>:  movdqu 0xc(%rsi), %xmm2
    0x100fd20ca <+9>:  movdqa %xmm0, %xmm1
    0x100fd20ce <+13>: pshufb %xmm10, %xmm1
    0x100fd20d4 <+19>: pshufb %xmm7, %xmm0
Target 0: (weylus) stopped.
```

**Comment by H-M-H** [comment]
This doesn't look too good, I built a debug version of Weylus: https://github.com/H-M-H/Weylus/actions/runs/907482512#artifacts, please check again with lldb and make sure to get the full backtrace with the `bt` command inside lldb.

Something else you could try is building with `MACOSX_DEPLOYMENT_TARGET=10.13` as environment variable set and check if this results in Weylus crashing, perhaps this is the problem (this variable is set for the build process with GitHub's CI).

If this doesn't result in any leads, it is waiting for https://github.com/actions/virtual-environments/issues/2187 I guess.

**Comment by flyinglimao** [comment]
Hi, log is here: 
[debug.log](https://github.com/H-M-H/Weylus/files/6603106/debug.log)

It works with the target label for both debug and release build

**Comment by H-M-H** [comment]
To be honest, I do not know what's going on here, especially considering that it works if you build Weylus yourself. All I can tell from the backtrace is that ffmpeg tries to access some invalid memory during video encoding.

But please try the latest master: https://github.com/H-M-H/Weylus/actions/runs/912483723#artifacts, I have added experimental support for capturing windows and individual displays by directly accessing [Core Graphics](https://developer.apple.com/documentation/coregraphics). Perhaps this won't crash :)

**Comment by flyinglimao** [comment]
That build works, and it can find the external monitor now!
There seems have two control forwarding problems. One is that x mapping seems about to doubled. If I touch (100, 100) on my tablet, it will be mapped to about (200, 100). The other one is that control is forwarded to default monitor when capture is set to external monitor.

**Comment by H-M-H** [comment]
> That build works

Awesome!

> One is that x mapping seems about to doubled

This should be fixed with latest master.

> The other one is that control is forwarded to default monitor when capture is set to external monitor.

This may still be a problem, please report back.

**Comment by mattpepin** [comment]
I suffer from the same crash. Do you think you will release a new version soon or I should compile?

**Comment by H-M-H** [comment]
I will probably release a new version within the next weeks, in the meantime you can either compile Weylus yourself or use the latest build from GitHub's CI: https://github.com/H-M-H/Weylus/actions/runs/955319136#artifacts
