### ISSUE TITLE
White screen on old iPad with latest Firefox or Chrome

### ISSUE THREAD

**Issue by sanderheinsalu** [H-M-H/Weylus#90]
Starting weylus on Ubuntu 18, works with Android phone with newest Chrome, but not with >5y old iPad, old OS 12, newest Chrome and Firefox. Navigating to the website the weylus window on the ubuntu displays (http://198...:1701), entering the password leads to a white page with a menu on the right and a log on the bottom right. The log says this browser is not supported. Same-looking page and log for both Firefox and Chrome.

**Comment by H-M-H** [comment]
Sadly everything below iOS / iPadOS 13 just doesn't implement the browser APIs required for Weylus to work :/

**Comment by sanderheinsalu** [comment]
Understandable. There is a limit to how old devices can be supported. Closing thread.
