### ISSUE TITLE
How to use other computer as Second screen for macbook

### ISSUE THREAD

**Issue by ThangaAyyanar** [H-M-H/Weylus#92]

**Comment by H-M-H** [comment]
As of now this is not possible on macOS. There are two things that need to be tackled before this can work:
- Weylus needs to properly handle multiple displays on macOS, as of now this is not supported. But looking at https://docs.rs/core-graphics/0.22.2/core_graphics/display/struct.CGDisplay.html, it seems not too hard to do.
- I have no clue how actually creating virtual monitors/screens on macOS works, this needs to be researched and I can't tell how difficult this is going to be.

**Comment by ThangaAyyanar** [comment]
Thanks for info.
