### ISSUE TITLE
Unable to use stylus in Xournal++

### ISSUE THREAD

**Issue by jwnpoh** [H-M-H/Weylus#93]
Sorry if this has already been documented but I missed it, but how do I configure the input settings in Xournal in order to use the stylus function?

![image](https://user-images.githubusercontent.com/56040656/121173258-2dd6e700-c88b-11eb-8583-22d1a691e6e4.png)

No matter what I try I seem to only be able to use my phone/stylus as a touchscreen/mouse. Does my phone/stylus have to actually have its own stylus/pen input system? I am currently using a Huawei P20 Pro and a random stylus with a rubber nib.

By the way, thanks for this wonderful app. I've been able to use this with Gromit-MPX to annotate on my screencasts for my students and it's made a huge difference.

**Comment by H-M-H** [comment]
> No matter what I try I seem to only be able to use my phone/stylus as a touchscreen/mouse. Does my phone/stylus have to actually have its own stylus/pen input system? I am currently using a Huawei P20 Pro and a random stylus with a rubber nib.

Weylus relies on the browser to properly report what kind of input is received. Some browsers, notably Firefox on Android, do not recognize a stylus/pen as such and just handle it as touch input, see https://github.com/H-M-H/Weylus/issues/66#issuecomment-811897459. It is also possible that your device doesn't recognize your stylus as such at all and in that case Weylus can not distinguish touch and stylus input.
If this is the case you have to configure Xournal++ to handle the Weylus Touch device like a pen.

> By the way, thanks for this wonderful app. I've been able to use this with Gromit-MPX to annotate on my screencasts for my students and it's made a huge difference.

Thanks, I am always happy to hear how Weylus is used!
