### ISSUE TITLE
Need help setting up virtual display

### ISSUE THREAD

**Issue by Judoguy12** [H-M-H/Weylus#97]
I can get it running but can't use more than 1 display, i am running fedora 34 any ideas how to get the virtual display working?

Thanks

**Comment by H-M-H** [comment]
I have documented everything I am aware of here: https://github.com/H-M-H/Weylus#weylus-as-second-screen, if this does not work for you, you will have to do your own research. If you come across something useful I am happy to include it in the Readme.

**Comment by Judoguy12** [comment]
found i need gnome with xorg not wayland. Any idea why browsers filcker bad but all the other windows are fine?

**Comment by H-M-H** [comment]
You may be able to fix this by tweaking your compositor settings. Afair setting the rendering backend in KDE to XRender prevents the flickering you experience. I do not know if something similar is possible under Gnome/Mutter.
