### ISSUE TITLE
Support for h265 nvenc

### ISSUE THREAD

**Issue by shubhampaul** [H-M-H/Weylus#99]
![image](https://user-images.githubusercontent.com/13408216/126202155-ef47d53c-d0e8-4990-8921-a96539362349.png)

So for certain reasons, my device doesn't have an h264 nvenc driver but it supports h265 nvenc but it seems like weylus only tries to use h264 nvenc. Can an option be added to the GUI to select between the type (h264/h265) of encoders with added support for h265 nvenc?

**Comment by H-M-H** [comment]
> So for certain reasons, my device doesn't have an h264 nvenc driver but it supports h265 nvenc

Interesting, I was pretty sure that if h265 is supported, then h264 is as well. Which GPU do you use?

> Can an option be added to the GUI to select between the type (h264/h265) of encoders

While this is certainly possible and probably not even that complicated I'd prefer not to and keep things simple.

If you really need this, have a look at:

https://github.com/H-M-H/Weylus/blob/4679d5220ebfe0ecd79f33368f04353d658b0491/lib/encode_video.c#L248-L279
and
https://github.com/H-M-H/Weylus/blob/4679d5220ebfe0ecd79f33368f04353d658b0491/ts/lib.ts#L723

**Comment by shubhampaul** [comment]
My device has the hardware (3070 mobile) but Lenovo decided to disable it: https://www.notebookcheck.net/Lenovo-laptops-silently-stripped-of-important-feature-in-BIOS-updates.550673.0.html

Yeah as you said, it might be very simple to add. I think the place where you pass arguments for FFmpeg, one needs to add an extra argument for the encoder type. I'll have a look at the references that you mentioned and try to build it. Thank you.

I was suggesting this since it could be better to have this feature for not only people like me ( who had their h264 nvenc disabled ) but also for others. Although, I am not really sure the benefits of h265 over h264, other than smaller file size.

**Comment by H-M-H** [comment]
> My device has the hardware (3070 mobile) but Lenovo decided to disable it

Wow, this is maddening! Apparently the only thing that may work to get h264_nvenc back is a BIOS downgrade.

> benefits of h265 over h264, other than smaller file size

Actually using h265 is rather disadvantageous for streaming. h265 is more complicated than h264 and thus results in higher latency as encoding takes longer. The compression rate h264 offers is sufficient and most importantly h264/avc is supported by all major browsers while [support for h265/hevc](https://caniuse.com/hevc) is pretty poor.

I'd love to switch over to some royalty free encoding like vp8, vp9 or better even av1 that is not riddled with patents like acv or hevc. But sadly there is (nearly) no hardware support for these yet.

**Comment by H-M-H** [comment]
I hope you found a solution or can live with software encoding. I have decided that I won't support hevc_nvenc as hevc is pretty much only supported on iOS/iPadOS and is going to lead to weird errors for other browsers that I do not want to explain to users.

**Comment by shubhampaul** [comment]
Sorry for not responding earlier. It seems like [Lenovo will be unlocking h264](https://forums.lenovo.com/t5/Gaming-Notebooks/Legion-5-Pro-NVENC-Support-Lenovo-Statement-erw%C3%BCnscht/m-p/5089418 ) on their devices.
